### ISSUE TITLE
Enable elasticache logs for GC Notify

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#100]
# Description

As a developer/operator of GC Notify, I would like to be able to review the elasticache/redis logs on AWS Cloudwatch when investigating issues. 

## WHY are we building?

This will aid in the troubleshooting and support of GC Notify

## WHAT are we building?

Create two new cloudwatch groups and enable logging in the elasticache cluster

## VALUE created by our solution

This will contribute to improved troubleshooting and resolution times for issues related to GC Notify.

# Acceptance Criteria

- [ ] Terraform apply works against staging and production with no downtime incurred
- [ ] Engine and Slow logs are sent to their appropriate AWS cloudwatch log groups

# QA Steps

- [ ] Tested in staging and production

**Comment by ben851** [comment]
* Implemented PR for redis logging, approved and merged.

**Comment by ben851** [comment]
* To be released in 1.29

**Comment by ben851** [comment]
* Released to prod yesterday.
*

**Comment by jimleroyer** [comment]
Checked in production and it's enabled in this environment now. 👍
