### ISSUE TITLE
Automate the ACM certificate validation process

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#103]
# Description

As a developer/operator of GC Notify, I would like the infrastructure to be completely automated. Currently there are manual steps involved for validating the TLS certificates for cloudfront. 

## WHY are we building?

This will contribute toward BCP and dynamic environment testings while also increasing the resiliency of notify.

## WHAT are we building?

[Add acm certificate validation to the cloudfront acm certificate](https://dev.to/aws-builders/create-acm-certificate-with-dns-validation-using-terraform-2adf)

## VALUE created by our solution

* Increased resiliency
* BCP readiness
* Dynamic environments for better testing

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] The cloudfront certificate is automatically validated when deploying to a new environment
- [ ] The existing cloudfront certificate is not impacted

# QA Steps

- [ ] Verified in staging and production

**Comment by ben851** [comment]
* Created ACM Cert Validation for Staging to be tested

**Comment by ben851** [comment]
* Came up with a better way to manage these resources, will open a new PR.

**Comment by ben851** [comment]
* PR up for review, hoping to merge to prod today.

**Comment by ben851** [comment]
* Merged to prod, working on DNS migration tomorrow morning. Aiming to have this solved by the afternoon.
*

**Comment by sastels** [comment]
had some issues, Ben is working on it...

**Comment by sastels** [comment]
One PR done, Jimmy reviewing

**Comment by ben851** [comment]
Deployed to prod v1.40

**Comment by jimleroyer** [comment]
I will QA the task.

**Comment by jimleroyer** [comment]
Verified in staging environment and things look good. 👍
