### ISSUE TITLE
Create 15 Minute Soak Test for Staging

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#105]
# Description

As a developer/operator of Notify, I would like to ensure that my changes merged to staging do not have any impact to the system.

## WHY are we building?

When deploying terraform changes, there can be a significant delay before the changes take effect. A simple smoke test may not identify issues as it runs  very quickly.

## WHAT are we building?

Create a new test scenario where the system is run under a sustained load for a period of time (15 minutes?) We may be able to leverage the existing performance test scripts running at reduced load. Integrate the soak test job into the notification-terraform merge to staging. 

## VALUE created by our solution

Increased stability of GC Notify. 

# Acceptance Criteria

- [x] Soak tests are created and configured
- [ ] Soak test is run on merge to staging 

# QA Steps

- [ ] Tests run successfully in staging

**Comment by ben851** [comment]
Ben to QA today in staging during K8s upgrade

**Comment by sastels** [comment]
PR https://github.com/cds-snc/notification-api/pull/1877

**Comment by ben851** [comment]
Verified this is working when upgrading staging to 1.24 k8s. I will just add a bit of documentation on setup.

**Comment by sastels** [comment]
I'll make a "soak test" note in LastPass with good params
