### ISSUE TITLE
Consolidate all terraform variables to TFVars, sourced from 1pass as the golden source for secrets

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#109]
# Description

As a developer of the GC Notify terraform, 
I want all configuration variables in a single location per environment,
So that I can reduce security risks of having secrets spread around,
And increase software maintenance.

## WHY are we building?

This will simplify the administration of the environments, and assist in speeding up troubleshooting of environments. 

## WHAT are we building?

Move variables from env_vars.hcl, terraform.hcl (root), terraform.hcl(Sub-folders) to the environment specific tfvars file, sourced from one password.

## VALUE created by our solution

This will improve time to recovery for support as well as general velocity in developing/deploying new features. This will also reduce the spread of our secrets, make the secrets variable pipeline more straightforward and reduce its current overall complexity.

# Acceptance Criteria

- [ ] All variables for existing environments are relocated to their appropriate TFVars.
- [ ] Variable files options are documented.
- [ ] The variables are fed from the 1password files (1 per environment).

# QA Steps

- [ ] Terragrunt apply/plan shows no changes in existing environments
- [ ] A new environment can be created by duplicating/modifying only the tfvars file.
- [ ] Check that the 1password variables feed the tfvars.

**Comment by P0NDER0SA** [comment]
This is handled/duplicates 410!  WE completed 410 and deployed it to production.
