### ISSUE TITLE
Upgrade Kubernetes to 1.27

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#117]
# Description

As a developer/operator of GC Notify, I would like my infrastructure to be up to date with EKS versions so that we are never racing against the clock to upgrade our systems before their versions are deprecated.

## WHY are we building?

Being several versions ahead of the minimum version will allow us to stay ahead of security patching, features, and prevent situations where we need to upgrade our cluster extremely quickly.

## WHAT are we building?

Upgrade the scratch, staging, and production K8s clusters to 
- [x] 1.24
- [x] 1.25
- [x] 1.26
- [x] 1.27

## VALUE created by our solution

More secure, better reliability, the elimination of tech debt.

# Acceptance Criteria

- [x] Scratch K8s is upgraded to 1.27 and notify still works
- [x] Staging K8s is upgraded to 1.27 and notify still works
- [x] Prod  K8s is upgraded to 1.27 and notify still works

# QA Steps

- [x] Run smoke/soak test against each environment
- [x] verify that the admin / api k8s / dd-api / celery logs are all working as expected
- [x] compare last night's perf test send rate to the previous days to ensure system not degraded
- [x] Run smoke tests in production once deployed in there. (Steve)

**Comment by ben851** [comment]
* Ben to release 1.24 in staging today @ 10am and test for downtime during migration

**Comment by ben851** [comment]
* Ben released 1.24 to staging yesterday, and broke logging
* Ben migrated Fluentd to Fluentbit to fix logging, and created a PR for prod release today.

**Comment by ben851** [comment]
* I'm having problems with celery scratch impacting celery staging and need to debug. (Second card created)

**Comment by ben851** [comment]
* Upgraded staging to v1.25. Will aim for production release Thursday am

**Comment by ben851** [comment]
Staging at 1.26, prod needs to be upgraded

**Comment by jimleroyer** [comment]
Potentially upgrading production today or tomorrow.

**Comment by jimleroyer** [comment]
Blocked until we deploy the DNS propagation.

**Comment by ben851** [comment]
Upon further inspection, staging was only at 1.25. Submitted PR for staging and prod to 1.26.

**Comment by ben851** [comment]
K8s in staging up to 1.26 smoke test is smoking, logs are logging.

**Comment by ben851** [comment]
K8s 1.26 in prod

**Comment by sastels** [comment]
1.27 working in scratch

**Comment by ben851** [comment]
https://github.com/cds-snc/notification-terraform/pull/876

**Comment by ben851** [comment]
- Staging upgraded to k8s 1.27
- To be QA'ed before upgrading prod.

**Comment by sastels** [comment]
Steve will QA this morning

**Comment by sastels** [comment]
QA'd everything looks good in staging

**Comment by ben851** [comment]
Moving from "Done" to "Prioritized" since we haven't pushed to prod yet.

**Comment by ben851** [comment]
K8s 1.27 release to production this morning. We are up to date!
