### ISSUE TITLE
Investigate Celery Errors and Alerts

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#122]
# Description

As a developer/operator of GC Notify, I would like to only be alerted when there are actual issues with our system, and not during false alarms so that I do not get alert fatigue and am able to quickly identify real errors.

This card covers the following alerts in the [alarm review spreadsheet
](https://docs.google.com/spreadsheets/d/1bQH8p_hSh89vqGfC-_gJsxZlmbzjGEc4Em-ooeWc0r0/edit#gid=0)

* logs-1-celery-error-1-minute-warning
* logs-10-celery-error-1-minute-critical

## WHY are we building?

We are receiving a lot of noise in our operations slack channel that are not indicative of actual issues. 

## WHAT are we building?

Investigate the celery 500 errors and determine if they can be fixed or if the alarm needs adjustment

## VALUE created by our solution

Fewer false alarms will increase developer agility and response times to actual issues.

# Acceptance Criteria

- [ ] Celery errors are clearly understood and documented
- [ ] Bugs that cause these alarms are covered with a new task card.

# QA Steps

- [ ] Cards exist for alarms that are triggered in the #notification-staging-ops channel.

**Comment by andrewleith** [comment]
- Most of the alarms were noise; @whabanks and @andrewleith to sync to finish this one off

**Comment by jimleroyer** [comment]
Most alarms are related to fluentd log switch, hence these were false positives in the past month. Also, some were related to a known incidents. It seems there are no adjustments necessary hence on our side.
