### ISSUE TITLE
Investigate Kubernetes 500 Error Alarms

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#123]
# Description

As a developer/operator of GC Notify, I would like to only be alerted when there are actual issues with our system, and not during false alarms so that I do not get alert fatigue and am able to quickly identify real errors.

This card covers the following alerts in the [alarm review spreadsheet
](https://docs.google.com/spreadsheets/d/1bQH8p_hSh89vqGfC-_gJsxZlmbzjGEc4Em-ooeWc0r0/edit#gid=0)

* logs-1-500-error-1-minute-warning

## WHY are we building?

We are receiving a lot of noise in our operations slack channel that are not indicative of actual issues. 

## WHAT are we building?

Investigate the kubernetes 500 errors and determine if they can be fixed or if the alarm needs adjustment

## VALUE created by our solution

Fewer false alarms will increase developer agility and response times to actual issues.

# Acceptance Criteria

- [x] Kubernetes errors are clearly understood and documented
- [x] Bugs that cause these alarms are covered with a new task card.

# QA Steps

- [x] Fewer 500's

**Comment by andrewleith** [comment]
- One more alarm to review, this one is still in progress

**Comment by sastels** [comment]
fix for the contact form 500
https://github.com/cds-snc/notification-admin/pull/1578
