### ISSUE TITLE
Increase log group retention to 1 year in STAGING env

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#130]
# Description

As an ops lead or GCNotify developer,
I would like to increase the data retention to 1 year,
So that I can properly come back on issues of the past, assess and fix.

At the moment, the retention period for some log group is set to 1 month which is too small for our needs. For example:
/aws/containerinsights/notification-canada-ca-staging-eks-cluster/application is set to 1 month.

## WHY are we building?

To debug issues that are older than a month.

## WHAT are we building?

Increased log capacity in STAGING environment.

## VALUE created by our solution

More debugging capacity.

# Acceptance Criteria

- [ ] All log groups for non-sensitive logs have a retention period of 1 year.
- [ ] All log groups for sensitive logs have a the minimal retention period of 7 days.

# QA Steps

- [ ] Check data retention of app log groups in staging environments.

**Comment by sastels** [comment]
We do still have a few app-related logs that have retention less than a year. Possibly we don't care about them?
- [Batch Saving](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/BatchSaving) 1 week
- [/aws/lambda/ses_to_sqs_email_callbacks](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fses_to_sqs_email_callbacks) 2 weeks
- [/aws/lambda/sns_to_sqs_sms_callbacks](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fsns_to_sqs_sms_callbacks) 2 weeks
- [/aws/lambda/ses-receiving-emails](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fses-receiving-emails) 3 months

**Comment by ben851** [comment]
New PR created that splits sensitive and non-sensitive log retention periods. Will get the team to review today.

**Comment by ben851** [comment]
Need to verify what happened two days ago

**Comment by ben851** [comment]
Not sure what I needed to verify before... Lesson learned to be more descriptive.

Can confirm that this has been released and is ready for QA.

**Comment by sastels** [comment]
Steve will take a look!

**Comment by sastels** [comment]
- For the [BatchSaving](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/BatchSaving) log group I see retention "Never expire"
- [/aws/lambda/ses_to_sqs_email_callbacks](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fses_to_sqs_email_callbacks) and [/aws/lambda/sns_to_sqs_sms_callbacks](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fsns_to_sqs_sms_callbacks) are both one week as expected for PII

**Comment by sastels** [comment]
Probably just needs a terraform variable set - Ben to investigate!

**Comment by ben851** [comment]
Ran into operations issues, will try and get to this today.

**Comment by ben851** [comment]
I verified that the callbacks are as expected.

The ses-receiving-emails was empty in staging and didn't exist anywhere else including TF. I deleted the log group in staging.

BatchSaving - I started looking but then had to switch to production release troubleshooting. Will get to this today.

**Comment by ben851** [comment]
@sastels to QA

**Comment by jimleroyer** [comment]
@sastels to QA today!

**Comment by sastels** [comment]
today. I swear. 95%.

**Comment by ben851** [comment]
In prod the retention period is configured to 0, so indefinite so that's expected.... unless this has sensitive info in it? In which case I can change it to the 7 day retention.

The retention period is set correctly in staging, at 12 months... as to why there are only entries from december - that I'm not sure of..

**Comment by sastels** [comment]
makes sense!
