### ISSUE TITLE
Test and fix the in-flight expired alarms

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#136]
# Describe the bug 

The expired in-flight alarms didn't trigger when going through a recent incident, i.e. [2023-06-01-notifications-getting-errors-repeatedly](https://docs.google.com/document/d/1RuHawkzLELYTSR1RqTRWBrR1t6xneIXlarMjLtc0R7o/edit#). 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-2 Major

# To Reproduce

1. Block a redis queue with a faulty notification (such as long content or bad signature).
1. Wait over many 5 minutes iteration for the notification to flip over the inbox, the in-flight and back to the inbox, numerous times.
1. Wait for the alarm to trigger based on its configuration (but it should not trigger), [such as this one](See examples in the documentation).

# Expected behavior

The alarm should trigger.

# Impact

We do not know when our Redis queues are filled up and stop getting processed.

Impact on Notify users: Potential delay of notifications or no sending.

Impact on Recipients: Potential delay of notifications or no reception.

Impact on Notify team: Less awareness on issues and more difficult to troubleshoot.

# Additional context

This behavior was observed during the incident [2023-06-01-notifications-getting-errors-repeatedly](https://docs.google.com/document/d/1RuHawkzLELYTSR1RqTRWBrR1t6xneIXlarMjLtc0R7o/edit#).

**Comment by sastels** [comment]
We don't seem to have an explicit alarm around inflights being expired.

**Comment by sastels** [comment]
Ok, I was wrong we have 4 alarms for expired inflghts! So why weren't these triggered? :thinking:
https://github.com/cds-snc/notification-terraform/blob/main/aws/common/cloudwatch_alarms.tf#L1345-L1461
- expired-sms-created-warning
- expired-sms-created-critical
- expired-email-created-warning
- expired-email-created-critical

**Comment by sastels** [comment]
well, first of all the warning / critical thresholds are set to 100 and 200 which is crazy high for something that only happens when something is going wrong.

However I still don't see any values for that metric during the incident. Investigating more...

**Comment by sastels** [comment]
The AWS queries only work on the last 3 hours of data. Not optimal. Hoewever, another recommended approach is to add a new value for the priority: "any" and save to that metric any time you save to any priority. Then base the overall alarm on this "any" priority. Will make a PR to do this and see how it works...

**Comment by sastels** [comment]
How to expire an inflight:

Go into redis (locally: redis-cli -h localhost -p 6380)

Add junk to an inbox:
	lpush inbox:email:bulk "steve"

See celery error:
	Invalid signature for signed_notification steve

See it in the in-flight:
	 lrange in-flight:email:bulk:<uuid> 0 -1

          1) "...real notifications..."
          2) "steve"

After 10 minutes this inflight will expire back to the inbox

In a few seconds it will go to a new inflight and cause the celery error again

This time find the new inflight and clean it up:
	lrem in-flight:email:bulk:<new uuid> 1 steve

**Comment by sastels** [comment]
[PR to add metric values for any notification type or priority](https://github.com/cds-snc/notification-api/pull/1894)

**Comment by jimleroyer** [comment]
Tested the inflight warning alarm by poisoning the bulk Redis queue with a badly signed notification. The alarm triggered after 5 minutes as expected. I checked the dashboard afterward and it showed as is:

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/5a666f8d-d1dd-4a20-85ae-439040ea69c4)
