### ISSUE TITLE
Modify Kubernetes services to not use external load balancers for services

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#140]
# Description

As a developer/operator of GC Notify, I would like all traffic to the system to come in through a central access point so that we are able to effectively administer and monitor the traffic, as well as protect against security threats.

## WHY are we building?

The K8s services for Notify products are currently exposing themselves directly to the internet via K8s load balancers. These should be changed to internal load balancer services, so that they are not available outside of the cluster.

## WHAT are we building?

Investigate how we are going to do this re: ingress controllers or internal load balancers

Verify that all functionality is intact in scratch account

Create an ADR to document the design decision

Implement solution

## VALUE created by our solution

Increased security and reliability of GC Notify.

# Acceptance Criteria

- [ ] Create an ADR for the task
- [ ] All GC Notify services are exposed only through the API gateway/ALB
- [ ] GC Notify still functions as expected

# QA Steps

- [x] Verified that everything works in staging before merging to production
- [ ] Create a script that demonstrates connectivity publicly and run before and after to verify the change

**Comment by jimleroyer** [comment]
We should check afterward if the issue described in this Slack thread still applies:
https://gcdigital.slack.com/archives/CNWA63606/p1677015136566929

**Comment by sastels** [comment]
PR is is

**Comment by ben851** [comment]
I've added a potential solution to avoiding downtime. For discussion tomorrow.

**Comment by ben851** [comment]
PR With the documentation for no downtime:
https://github.com/cds-snc/notification-manifests/pull/1947

**Comment by sastels** [comment]
Had issues, will need to break the TF PR up and do in stages

**Comment by ben851** [comment]
- Staging is now running against internal load balancers.
- Will let this run while I'm on vacation before merging to production.
- Production has the empty target groups created

**Comment by jimleroyer** [comment]
Deployed secondary services in production, nothing exploded. PR opened to target group to secondary. We can resume that work in the core group work session today.

**Comment by ben851** [comment]
Prod and staging are now running on internal load balancers. The secondary external load balancers are still up in case we need to revert quickly. We will remove them early next week.

**Comment by ben851** [comment]
Ben to remove secondary services today.

**Comment by ben851** [comment]
Secondary services removed in staging and prod, smoke tests passing in both.

Need to create a PR in notification-terraform to remove the secondary target groups.

**Comment by ben851** [comment]
Secondary target groups removed in staging. 

@sastels Please try and hit the service urls in staging.

**Comment by sastels** [comment]
Confirmed that I can't hit the IPs for admin, api, documentation, nor dd-api
```
curl internal-afd896d82c7a54e99848a8305b51ef60-568829761.ca-central-1.elb.amazonaws.com
```
etc
