### ISSUE TITLE
Investigate Evicted Celery Pods in Staging

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#145]
## Describe the bug 

In staging, Celery pods are being evicted without providing any reason. Looking at the node health, it appears as though they are heavily overcommitted with memory requests. We need to investigate the reason for the eviction, and determine a best course of action

The pods are being evicted due to disk pressure. I suspect that this is related to docker image caching on the OS disk of the node.

Message:          Pod The node had condition: [DiskPressure]. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-2 Major

## To Reproduce

Need to verify this wasn't a one time occurence. Kubectl get pods -n notification-canada-ca in staging should not show any evicted pods. 

## Expected behavior

There should be no evicted pods

## Impact

This clutters our K8s namespace and also could introduce potential performance issues

## QA 

Monitor production and staging environments to make sure there are no more evicted pods for 1 week since Sept 7th.

**Comment by ben851** [comment]
* Will have to put this on the back burner since the nodes with disk pressure were replaced when doing the kubernetes upgrade to 1.25

**Comment by ben851** [comment]
* I did some investigation - it appears that log files are potentially taking up space.

**Comment by ben851** [comment]
* Further investigation identifies this as ephemeral storage disk pressure issues.
* It doesn't appear as though any pods are taking up a huge amount of ephemeral storage. Nodes are reporting 0% usage by pods.
* The two biggest culprits could be docker images or host logs. Given that we are not experiencing the same issues in production, I am thinking it's more likely to be docker images than logs.
* I would like to install grafana/prometheus combo into staging to see if I can find some more data.

**Comment by jimleroyer** [comment]
We have to do a bunch of 💩 in staging.

**Comment by sastels** [comment]
Nothing evicted lately, waiting so that we can get some data

**Comment by ben851** [comment]
Reviewed the last weeks worth of data in grafana staging and it did not occur. Moving this to blocked for now, possibly back to ice box?

**Comment by ben851** [comment]
Moving to ice box, will resurface in the event that this issue returns to staging.

**Comment by ben851** [comment]
@ben851 to create an alert when pods are evicted.

**Comment by ben851** [comment]
New PR opened to alert on evicted pod status

**Comment by jimleroyer** [comment]
Moving the task to icebox until we get notified with the new alert setup.

**Comment by ben851** [comment]
Alarms triggered in production today. The pods were evicted due to node disk pressure.

We verified that fluent bit logs are not taking up a huge amount of space, but disks are getting full.

While we can't confirm, we are pretty sure that the image cache is taking up too much space, and not clearing enough room.

We are going to increase the node disk size

**Comment by jimleroyer** [comment]
Disk size is upgraded on the nodes but Terraform didn't recognize it. This will require to recreate the nodes. Steve to drop a link here for the script to recreate the nodes. We need to test in staging environment, especially to catch the 502 errors.

**Comment by jimleroyer** [comment]
Steve and Ben to test the new eviction script in staging environment.

**Comment by sastels** [comment]
- upgraded staging to 80G nodes using the new script to move primary -> secondary -> primary
- ran a soak test doing a GET to `https://staging.notification.cdssandbox.xyz/_status` every second
- no errors

**Comment by sastels** [comment]
- upgraded staging to 80G nodes using the new script to move primary -> secondary -> primary
- ran a soak test doing a GET to `https://staging.notification.cdssandbox.xyz/_status` every second
- no errors

**Comment by ben851** [comment]
- Created PR to enable the secondary nodes w/ 80gb disks in production.

**Comment by sastels** [comment]
need to do a release to get the secondary nodes in prod

**Comment by sastels** [comment]
secondary nodes now in prod

**Comment by sastels** [comment]
application moved to secondary in prod this morning. primary upgrade and move back scheduled for today

**Comment by ben851** [comment]
Primary nodes upgraded, need to delete secondary nodes

**Comment by ben851** [comment]
Will release config to delete secondary nodes tomorrow.

**Comment by jimleroyer** [comment]
Checked production and there are no evited pods so far.

**Comment by ben851** [comment]
If no pods by tomorrow, will move to done.
