### ISSUE TITLE
Set up Quicksight in production

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#147]
# Description

As a Notify team member, I need to be able to easily find data to help with business intelligence needs.

## WHY are we building?

- we need a better way to create dashboards for any team member to use

## WHAT are we building?

- Install AWS QuickSight into our own account.

## VALUE created by our solution

- Better insights into our database data
- Easy to create drag and drop visualizations
- Easy for any non-dev team member to log in and use via SSO / google authentication

# Acceptance Criteria

- [x] A Quicksight account is created in staging/prod
- [x] The account is connected to our RDS instance
- [x] We have created a simple visualization (notification count over time, say)
- [x] This is setup through infrastructure-as-code, i.e. Terraform

# QA Steps

- [x] A non-dev or a manager creates a QuickSight visualization.

# Additional information

We'd need to upgrade to latest AWS provider because it requires latest QuickSight Terraform offering.

Previous PRs work on this:

-  [Security group](https://github.com/cds-snc/notification-terraform/pull/670)

**Comment by sastels** [comment]
Have some terraform code that seemed to add Quicksight to scratch and staging! Will make a PR to staging for now.

**Comment by sastels** [comment]
roughed in a terraform PR on Friday. Still needs work. Will circle around with Ben when he's back.

**Comment by jimleroyer** [comment]
Talked to Steve on current status of this card:

* @ben851 was able to make quicksight work in his scratch account.
* [PR opened](https://github.com/cds-snc/notification-terraform/pull/824) following this work.
* Tests need to be done after PR is merged from scratch account.
* Still need to upgrade our Terraform provider for some missing functionality, Steve to comment further on that.

**Comment by sastels** [comment]
- Terraform code to create QuickSight subscription and data source connected to RDS working in staging
- Next step is to create a data set using the data source

**Comment by sastels** [comment]
Try to add a dataset
https://github.com/cds-snc/notification-terraform/pull/894

**Comment by sastels** [comment]
PR to create the user group and give it access to the new dataset
https://github.com/cds-snc/notification-terraform/pull/899

**Comment by sastels** [comment]
more data sets! https://github.com/cds-snc/notification-terraform/pull/911

**Comment by sastels** [comment]
terraform apply hung for 40 minutes. After being killed, the `templates` data set was in a half created state. In particular, `terraform plan` and `terraform apply` would hang. Also
```
aws quicksight describe-data-set --aws-account-id 239043911459 --data-set-id templates
```
and
```
aws quicksight delete-data-set --aws-account-id 239043911459 --data-set-id templates
```
would result in an InternalFailure error.

We removed quicksight from terraform plan and apply for now, and put in a [support ticket](https://support.console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=13791737241&language=en) to get the data set deleted.

**Comment by sastels** [comment]
AWS Support escalated to next level support to delete the dataset.

**Comment by ben851** [comment]
No response from AWS so far.

**Comment by sastels** [comment]
more datasets moved to staging. bypassing broken dataset for now (creating it with a new name and id)

**Comment by sastels** [comment]
PR to upgrade our terraform AWS provider from version 4 to version 5
https://github.com/cds-snc/notification-terraform/pull/955

**Comment by jimleroyer** [comment]
Ben to look into AWS meeting this week. There was a Quicksight dataset that doesn't exist apparently and we can't delete. It's in a broken state and we need AWS support to push through.

**Comment by ben851** [comment]
provider upgraded to 5 in staging

**Comment by ben851** [comment]
Created a new card to track the provider upgrade. Moving this back to blocked for now.

**Comment by sastels** [comment]
provider plugin crashes now when planning or applying quicksight module.

**Comment by sastels** [comment]
Ben working on a fix but it might need to go to terraform folks to fix the aws provider

**Comment by ben851** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/34199

Issue created for provider issue with quicksight

**Comment by ben851** [comment]
I managed to get a cloudformation template deploying in staging. I will look at integrating it with Terraform today.

**Comment by ben851** [comment]
Integrated into Terraform, deployed to staging.

**Comment by ben851** [comment]
Need to automate the quicksight db user creation before this can be closed.

**Comment by sastels** [comment]
Terraform quicksight code working in dev and staging now. ready to push to prod

**Comment by sastels** [comment]
Add QuickSight to prod plan / apply
https://github.com/cds-snc/notification-terraform/pull/1044

**Comment by sastels** [comment]
subscription and a few datasets added. Problems adding notification_history, need to estimate SPICE requirements first.

**Comment by sastels** [comment]
also need to estimate monthly costs.
- users
- total SPICE
- are there other costs? moving data around for example?

**Comment by sastels** [comment]
- clickops join notifications-services-template in prod and staging
-  wrote terraform to do a notifications-services-template join. Worked except for a provider crash - what we switched to Cloud Formation to fix last time. Will do this next.

**Comment by sastels** [comment]
synced with Beth on Growth query as something to prototype on prod.

**Comment by ben851** [comment]
Calvin has asked Sylvia to see if they can hook up quicksight to sentinel.

PR In for joining notification history with cloud formation template.

**Comment by ben851** [comment]
PR up for review on notification history table. 
Once that's complete, this card can be considered done. A new set of cards can be refined for further steps.

**Comment by ben851** [comment]
Still needs review
