### ISSUE TITLE
Upgrade Hasura

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#148]
# Description

We're using version 1.3.3, and the current version is 2.6.1. We're likely missing out on both improved features as well as security updates.

https://github.com/cds-snc/notification-manifests/blob/main/base/hasura-deployment.yaml#L20

Probably pretty easy since we don't use Hasura for anything too complicated.
https://hasura.io/blog/migrating-from-hasura-v1-3-to-v2-0/

Portal we use for executing sql queries 

# Impact

More secure, more features. We are running the latest version with latest security patches included.

# Acceptance criteria

- [ ] Hasura k8s pod is running latest version via terraform and no problems are reported.

# QA 

- [ ] Test the GraphQL capabilities.
- [ ] Test the SQL capabilities.
- [ ] Test the SQL UI query capabilities.

# Additional Notes

Migration notes on upgrading Hasura:
 https://hasura.io/blog/migrating-from-hasura-v1-3-to-v2-0/

**Comment by ben851** [comment]
Closing this issue since we have introduced the VPN and the ability to connect to the database locally. We will decommission Hasura, and create a new card.
