### ISSUE TITLE
Remove deprecated IAM user from AWS / Terraform

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#157]
# Description

As an ops lead and dev,
I want to get rid of unnecessary permissions, roles and users,
So that I can have a strip down system of unnecessary privileges.

## WHY are we building?

Maintenance, security, and code health.

## WHAT are we building?

Removing bulk_send and inspec-scanner related users, groups and roles.

## VALUE created by our solution

Code quality, security.

# Acceptance Criteria

- [ ] inspect-scanner related user, group and roles are removed.
- [ ] bulk_send related user, group and roles are removed.
- [ ] GCNotify system is not affected.
- [ ] Documentation referring to the users are removed from the [rotation document](https://docs.google.com/document/d/1BkAkz45CVQRGQSNwN018beTebrbTUNpyTpGEaO7Clyc/edit#heading=h.i39s8onstwuk).

# QA Steps

- [ ]  Smoke tests the API.
- [ ]  Smoke tests the Admin.

# Additional information

Related PR to revert:
* https://github.com/cds-snc/notification-terraform/pull/79/files

Code references:

* https://github.com/cds-snc/notification-terraform/blob/d0d142f313c87ec817b33ec6b52dcb4b3dd998f7/aws/common/iam.tf#L133
* https://github.com/cds-snc/notification-terraform/blob/d0d142f313c87ec817b33ec6b52dcb4b3dd998f7/aws/common/iam.tf#L182

**Comment by ben851** [comment]
This was completed here:
https://github.com/cds-snc/notification-terraform/pull/851
