### ISSUE TITLE
Upgrade Flask and Werkzeug

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#158]
# Description

As a notify developer, I need to be able to upgrade our dependancies

## WHY are we building?

The version of Flask that we were using was a blocker to upgrading other packages

## WHAT are we building?

Upgrade Flask. This required other upgrades as well, notable Werkzeug.

## VALUE created by our solution

Can continue to upgrade dependancies as needed

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] All apps / repos are using Flask 2.3.2
- [ ] app still works

# QA Steps

- [x] run smoke test
- [x] In admin: send emails 
- [x] In admin: texts
- [x] In admin: view notifications and reports
- [x] send yourself a file attachment and a file link and verifiy they work

**Comment by sastels** [comment]
PRs:
https://github.com/cds-snc/notification-utils/pull/222
cds-snc/notification-admin#1601
cds-snc/notification-api#1921
cds-snc/notification-document-download-api#141

**Comment by ben851** [comment]
Validated all QA points in staging environment
