### ISSUE TITLE
Create route to error / stack trace on admin / api / dd-api

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#160]
# Description

As a developer, I need to be able to create errors on our apps to test the behaviour in those situations

## WHY are we building?

Want to test what happens where there's an error (in particular, test the logging)

## WHAT are we building?

- a route that generates a stack trace
- some way to prevent other people from triggering it

## VALUE created by our solution

easier to test system behaviour

# Acceptance Criteria

- [ ] route in admin / api / dd-api that causes a stack trace
- [ ] method to prevent others from triggering it

# QA Steps

- [x] Go to https://staging.notification.cdssandbox.xyz/_debug?key=DEBUG_KEY where you can get `DEBUG_KEY` from the manifest repo. This should trigger an exception
- [x] Go to https://staging.notification.cdssandbox.xyz/_debug?key=wrong and you should get a 404 and no exception

**Comment by sastels** [comment]
terraform: [add _debug route to WAF](https://github.com/cds-snc/notification-terraform/pull/826)
manifest: [feat: Add debug key
](https://github.com/cds-snc/notification-manifests/pull/1862)
admin: [add a route that will throw an exception](https://github.com/cds-snc/notification-admin/pull/1613)

**Comment by ben851** [comment]
Completed PR, to review.

**Comment by jimleroyer** [comment]
I will take the QA on this.

**Comment by jimleroyer** [comment]
QA'ed and working. 👏 Moving to done.
