### ISSUE TITLE
FluentBit memory/streaming configuration

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#171]
# Describe the bug 

Because FluentBit has faulty multi-line configuration, we are at risk of accumulating chunks of logs and stop emission of logs to CloudWatch.

# [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major

# To Reproduce

# Expected behavior

# Impact

Describe overall user/system impact to consider when prioritizing this issue.

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team: 

# Additional context

**Comment by sastels** [comment]
work progressing. issues getting stats into correct format for prometheus.

**Comment by sastels** [comment]
have a janky PR to fix the regex

**Comment by ben851** [comment]
PR merged to staging in review for testing.

**Comment by ben851** [comment]
PR did not work, reverted on Friday. Back to the drawing board!

**Comment by ben851** [comment]
Closing in favour of #221
