### ISSUE TITLE
Split SMS tasks into their own pods on staging

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#185]
# Description

As a Notify developer, I need SMS delivery tasks to be run by a dedicated group of pods so that I can treat them differently than email delivery tasks.

## WHY are we building?

The sending rates set by AWS are different for email and sms, and hence we need to be able to tune them separately. We have decided that the best way to do this right now is to have the email and sms delivery tasks run on different groups of pods.

## WHAT are we building?

- Write a new script for just these queues
- make a new deployment that runs this script in a few pods
- This task should not get in production as it requires further optimizations.

## VALUE created by our solution

We will be able to scale up both email and sms sending rates.

# Acceptance Criteria

- [x] `deliver_sms()` running on dedicated celery pods
- [x] staging running new split pods,
- [x] modify SMS dashboard to show status of new queues (should have been done in #186 :/) 
- [x] prod running the old system (verify after prod release) 

# QA Steps
- [x] prod is not running new pods
- [x] smoke tests pass on prod
- [x] smoke tests pass on staging
- [x] sms sending in correct pods (see [this query](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-604800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20kubernetes.container_name*2c*20log*0a*7c*20filter*20*40message*20like*20*2fTask*20deliver_sms*2f*0a*7c*20filter*20kubernetes.container_name*20*21*3d*20*22celery-sms-send*22*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*20200*0a~queryId~'d0de19b5-39d1-47fd-a41d-e1151fb301c4~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-staging-eks-cluster*2fapplication))))

**Comment by ben851** [comment]
How to split out the celery config in k8s:
1. Create a new run_celery script with the appropriate queue config for sms only
2. Remove sms config from old run_celery script
3. In notifications-manifests/base:
     - Make copies of celery-deployment, celery-service, and celery-hpa naming them something like celery-deployment-sms etc.
     - Move these copies to the env/staging folder
     - Modify the "name" in metadata to reflect that they are for sms only in each new file
     - On line 127 of the new celery-deployment-sms.yaml,  modify the script name to be the new sms only script
     - Add references to these files in the staging kustomization.yaml under the resources section

**Comment by sastels** [comment]
WIP PR https://github.com/cds-snc/notification-manifests/pull/1980

**Comment by sastels** [comment]
Didn't get to merging and testing this Monday, will merge and test first thing Tuesday.

**Comment by sastels** [comment]
Using locust sent 3300 SMS to the internal test # at 20 sms / second.
- cluster used 3 pods 
- send rate was approx 160 sms / minute
- - could watch the send-sms-medium queue in the [new dashboard](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#dashboards/dashboard/SMS_V2)

**Comment by sastels** [comment]
PR to add these charts to the SMS dashbaord:
https://github.com/cds-snc/notification-terraform/pull/917

**Comment by sastels** [comment]
not merging the dashboard PR until after we have the sms deployment on prod.

**Comment by sastels** [comment]
ready for QA!

**Comment by sastels** [comment]
Jimmy to QA

**Comment by sastels** [comment]
A better query
```
fields @timestamp, kubernetes.container_name, log, @logStream
| filter @message like /Start sending SMS for notification id/
| filter kubernetes.container_name != "celery-sms-send"
| sort @timestamp desc
| limit 200
```

**Comment by sastels** [comment]
So this query does find one sms sent on the old pods on Sept 20:
https://staging.notification.cdssandbox.xyz/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/notification/77630fd8-61c8-45ac-aaaa-ca5a343b8c8b
This was a 2FA code sent by Notify. (for logging in to Notify)
It's possible (well, likely) that there's some code that's using the old queues that I missed when I moved sms to their own queues.

**Comment by sastels** [comment]
ok! 
```
sms 77630fd8-61c8-45ac-aaaa-ca5a343b8c8b sent to the notify-internal-tasks queue for delivery
```
So! we need to send these sms via the new sms sending queues as well. I'm going to move this card back to In Progress.

**Comment by jimleroyer** [comment]
Steve, Ben and I spoke offline about the SMS notification that goes through the older pod to deliver SMS. We agreed it's okay for now as this is solely meant for GCNotify 2FA. These do not represent a risk for overflooding our SMS rate limit with AWS, so having these SMS going through the scaled up nodes would be fine. 

We will create a card to move the GCNotify 2FA SMS into their own dedicated queue, using the newer SMS dedicated pods.

QA test is approved, because the intended behavior of expected SMS uses the newer SMS dedicated pods. The 2FA of GCNotify is not a risk nor a blocker for scaling up.
