### ISSUE TITLE
Move SMS into their own dedicated queues

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#186]
# Description

As a Notify developer, I need SMS delivery tasks to be in their own queues so that I can treat them differently than email delivery tasks.

## WHY are we building?

The sending rates set by AWS are different for email and sms, and hence we need to be able to tune them separately. We have decided that the best way to do this right now is to have the email and sms delivery tasks run on different groups of pods. This requires they also be placed in different celery queues.

## WHAT are we building?

Move SMS delivery tasks to their own dedicated celery queues. Note that this task does **not** include moving the sms delivery tasks to their own dedicated pool of celery workers (that is the scope of #185)

## VALUE created by our solution

We will be able to scale up both email and sms sending rates.

# Acceptance Criteria

- [x] `deliver_sms()` tasks go through their own celery queues.
- [x] create wait time alarms for the new queues and add to the sms dashboard

# QA Steps
- [x] verify that smoke tests still pass (Steve)
- [x] Verify that the new queues are being used with a cloudwatch query such as [this one](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-604800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20log*2c*20kubernetes.labels.app*20as*20app*2c*20kubernetes.pod_name*20as*20pod_name*2c*20*40logStream*0a*7c*20filter*20pod_name*20like*20*2f*5ecelery*2f*0a*7c*20filter*20log*20like*20*2fqueue*20for*20delivery*2f*0a*7c*20filter*20log*20like*20*2fsms*20*2f*0a*7c*20filter*20log*20not*20like*20*2fsend-throttled-sms-tasks*2f*0a*7c*20parse*20log*20*2f.*2asent*20to*20the*20*28*3f*3cqueue*3e.*2a*29*20queue*20for*20delivery*2f*0a*7c*20stats*20count*28*2a*29*20as*20total*20by*20queue*0a~queryId~'db015112-c736-4ec6-831a-1de9f9528f41~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-production-eks-cluster*2fapplication))) (Jimmy)

**Comment by sastels** [comment]
If we're going to move sms to its own celery pods (under discussion) then they'll need to be using their own queues. [Looking at a week of prod data from 8/2/2023 to 8/9/2023](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-604800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20log*2c*20kubernetes.labels.app*20as*20app*2c*20kubernetes.pod_name*20as*20pod_name*2c*20*40logStream*0a*7c*20filter*20pod_name*20like*20*2f*5ecelery*2f*0a*7c*20filter*20log*20like*20*2fqueue*20for*20delivery*2f*0a*7c*20filter*20log*20like*20*2fsms*20*2f*0a*7c*20filter*20log*20not*20like*20*2fsend-throttled-sms-tasks*2f*0a*7c*20parse*20log*20*2f.*2asent*20to*20the*20*28*3f*3cqueue*3e.*2a*29*20queue*20for*20delivery*2f*0a*7c*20stats*20count*28*2a*29*20as*20total*20by*20queue*0a~queryId~'db015112-c736-4ec6-831a-1de9f9528f41~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-production-eks-cluster*2fapplication))) we see the following queues used to run `deliver_sms`:

| queue | total |
| --- | --- |
| priority-tasks | 19497 |
| send-sms-tasks | 12784 |
| research-mode-tasks | 21 |
| bulk-tasks | 30 |

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-api/pull/1958

**Comment by sastels** [comment]
fixed code for bulk sends and added missing tests

**Comment by sastels** [comment]
PRs ready for review:
use new queues: https://github.com/cds-snc/notification-api/pull/1958
add alarms for new queues: https://github.com/cds-snc/notification-terraform/pull/877

**Comment by jimleroyer** [comment]
The PR for API #1958 should make the column storing the used queue closer to the truth (as this is not 100% reliable at the moment).

**Comment by sastels** [comment]
[Alarms](https://github.com/cds-snc/notification-terraform/pull/877) merged into staging

**Comment by sastels** [comment]
- new alarms released to prod
- new queues merged into staging and tested.

**Comment by sastels** [comment]
new queues in prod

**Comment by jimleroyer** [comment]
Seems to be working as most volume passes through the new queues, but still older queues appear for the last week. I will tweak the query to add days on where the older/newer queues were used to have further details on what's being used now.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajZPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ed1844549119f46fbb7c80d3a50c110bf0c25dc/image.png)

**Comment by jimleroyer** [comment]
Re-running the query for QA'ing the new priority queues, we see that the older queues are only present at day 6th and 7th of the 1 week period that it covers. Afterward, all new queues are used. So that all works good over there.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFdRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b5fb721d587024efecd1988821041efaf27a70d6/image.png)
