### ISSUE TITLE
Review instance types for our Kubernetes pods

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#188]
# Description

As a product owner of GCNotify, 
I want our GCNotify to have bigger instance types for pods that are more capable,
So that GCNotify can send more notification per minute.

## WHY are we building?

More capacity for our pods to scale our sending numbers.

## WHAT are we building?

Review necessary instance types that fit our requirements profile.

## VALUE created by our solution

More capacity

# Acceptance Criteria

- [x] Provide the rationale for picking the instance type.
- [x] Provide the requirements profile we'd have.

# QA Steps

- [x] The rationale was reviewed.
- [x] system is stable with chosen node types

**Comment by ben851** [comment]
We evaluated how notify performs under load and concluded that it is memory intensive, but not CPU intensive. As a result, we have elected to go with the r5.large instance type as our primary node type. The reasoning behind this is that it has twice the memory as m5.large and is only moderately more expensive than m5.large. As a result we should be able to nearly double our scaling capacity.
