### ISSUE TITLE
Switch security scanner to Chekov

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#189]
# Describe the bug 

Our current tfsec scanner fails silently, i.e. the action doesn't actually run but still passes. As the SRE team switched to Chekov some time ago, we can migrate to the tool directly and then in a separate task card, fix the related warnings it will report.

This card does not include fixing the warnings from the security reports. This should be handled in a different card.

For context: see [this Slack discussion](https://gcdigital.slack.com/archives/CS2L5CHKK/p1693500888980269).

# [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

See examples in the documentation

SEV-3 Minor

# To Reproduce

Look at the output of the action (see [the Slack thread](https://gcdigital.slack.com/archives/CS2L5CHKK/p1693500888980269))

## Expected behavior

We migrated to Chekov and it can report issues.

# Impact

Infrastructure code not being scanned, we are unaware of potential security risks.

# Additional context

From the [Slack thread](https://gcdigital.slack.com/archives/CS2L5CHKK/p1693500888980269):

>I haven’t used the tfsec-action in a long time - I switch the TF code I manage over to using checkov:
https://github.com/bridgecrewio/checkov-action
Here’s an example of it doing its thing:
https://github.com/cds-snc/scan-files/blob/main/.github/workflows/terraform-security-scan.yml
You can add inline comments to the *.tf to suppress false-positives, or use a config file like so:
https://github.com/cds-snc/scan-files/blob/main/terragrunt/.checkov.yml

# QA

- [x] Verify that the code issues are being sent to github, and we can begin creating tickets for them.

**Comment by ben851** [comment]
Merged to Staging and therefore production since this is a workflow change...
