### ISSUE TITLE
Create Cloudwatch Alerts for failed Kubernetes Pods

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#19]
## Description

As an ops lead, 
I want to know when K8s pods are failing
So that I can take corrective actions.

### WHAT 
Create AWS cloudwatch alerts when any pod within the kubernetes cluster is in a failed or not-ready state.

###WHY 
Failed pods indicate issues with the system, that could indicate an incident is underway. This is additional infrastructure monitoring to accompany existing system monitoring.

###VALUE
Increasing our visibility into the infrastructure side of the notify system will help us get ahead of incidents, ensure that planned releases complete successfully, and provide additional metrics we can measure against to verify system integrity.

## Acceptance Criteria

- [x] Failed pod alerts are sent to slack
- [x] Pod alerts are generic, not specific to single applications, and are verified to be working across all deployments

## QA Steps
- [x] Manually break each deployment so that pods are failing and verify that we are alerted

## Related Tasks

* [Move database migration logic out of the Kubernetes API pod initialization](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/20)
* [Raise alarm when database migration fails](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/21)
* [Update Dev Container to use correct version of Postgres](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/17)

**Comment by sastels** [comment]
some EKS metrics that might be useful:
- cluster_failed_node_count
- pod_number_of_container_restarts

**Comment by ben851** [comment]
EKS does not natively include kube-state-metrics. I have manually installed it in my scratch cluster, and the installed the AWS Cloudwatch Prometheus agent. I can see the metrics from KSM in the log groups, but they are not translated to CW metrics. This seems to be a known issue with AWS Cloudwatch:
https://github.com/aws/containers-roadmap/issues/548

Options at this point:
1. Look into generating the alerts within newrelic
2. Deploy prometheus and grafana and use that for metric watching/alerting
3. Shelf for now?

**Comment by ben851** [comment]
KMS and cwagent-prometheus are deployed to staging. New alerts leveraging these have been PR'ed to staging.

**Comment by jimleroyer** [comment]
This was deployed in prod. We need to QA. To validate, we can change the image SHA ID to something invalid to see how the pods will report this. Jimmy to QA this one.

**Comment by ben851** [comment]
QA identified that the incorrect value was being leveraged.  PR to go from average to sum has been done

**Comment by jimleroyer** [comment]
Most work in staging, except one in a PR we can merge this morning. Ready to be pushed to production afterward.
