### ISSUE TITLE
Kubernetes resource alarms are being triggered due to insufficient data

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#191]
## Describe the bug 

We are receiving alerts stating that kubernetes cpu and memory usage metrics are reporting insufficient data. It appears as though the cloudwatch agents temporarily stop sending metrics to cloudwatch. This may correspond with the upgrade to k8s 1.27

Sev-2

## To Reproduce

Difficult to reproduce, happens randomly in staging and prod.

## Expected behavior

There should be no interruption of metrics being sent to cloudwatch

## Impact

Impact on Notify team: 

- We may be paged in the middle of the night with false alarms.
- We could miss real alarms due to the insufficient data.

## Additional context

Started happening in staging August 18th, shortly after k8s 1.27 upgrade. Similarly, it started happening in prod after 1.27 upgrade.

## QA

- [ ] leave for 2 weeks to verify that alarms aren't triggered anymore

**Comment by ben851** [comment]
Will open a ticket w/ AWS support to ask if they have any experience with this

**Comment by ben851** [comment]
There have been no insufficient data alarms in staging since deploying the updated version. Will proceed with deploying to production.

**Comment by ben851** [comment]
PR Created to move the upgrade to production.

**Comment by sastels** [comment]
released to prod.
