### ISSUE TITLE
Nuke document-download-frontend kubernetes service

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#192]
# Description

As an ops lead,
I want to get rid of K8s service that are unused,
to reduce vector of attacks against GCNotify.

## WHY are we building?

Deleting the document-download-frontend should reduce security risk overall as we don't need it anymore.

## WHAT are we building?

Destroy the document-download-frontend k8s service and get rid of it in manifests code.

## VALUE created by our solution

Closing doors to potential attacks.

# Acceptance Criteria

- [ ] The document-download-frontend service is nuked
- [ ] Code references to document-download-frontend service do not exist.

# QA Steps

- [x] Check manifest repository for references to the k8s service named document-download-frontend.
- [x] Check if any service is up and running for document-download-frontend.

**Comment by ben851** [comment]
Deleted the document-download-frontend services in both staging and production. There is no code to remove.

**Comment by ben851** [comment]
@sastels will verify that the services no longer exist in staging and production.

**Comment by sastels** [comment]
checked!
