### ISSUE TITLE
Deploy new celery-sms-send pods in prod

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#195]
# Description

As a Notify team member, I need to change our prod sms configuration to be able to scale email and sms independantly.

## WHY are we building?

Need to be able to scale emails and sms independantly.

## WHAT are we building?

deploy the sms-send pods in prod

## VALUE created by our solution

We will be able to keep both emails and sms close peak send rates close to but not over our AWS limits

# Acceptance Criteria

- [x] staging load tests show 2000-3000 emails / min and 500-600 sms fragments / min
- [ ] celery-sms-send pods running on production with this configuration

# QA Steps

- [x] [verify](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20log*2c*20kubernetes.labels.app*20as*20app*2c*20kubernetes.pod_name*20as*20pod_name*2c*20*40logStream*0a*7c*20filter*20pod_name*20like*20*2f*5ecelery*2f*0a*7c*20filter*20log*20like*20*2fqueue*20for*20delivery*2f*0a*7c*20filter*20log*20like*20*2fsms*20*2f*0a*7c*20parse*20log*20*2f.*2asent*20to*20the*20*28*3f*3cqueue*3e.*2a*29*20queue*20for*20delivery*2f*0a*7c*20stats*20count*28*2a*29*20as*20total*20by*20queue*0a~queryId~'db015112-c736-4ec6-831a-1de9f9528f41~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-production-eks-cluster*2fapplication))) that there are no sms sent in the `priority-tasks`, `bulk-tasks`, nor `send-sms-tasks` queues (otherwise the 30 celery pods will be sending them!)
- [x] [verify](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-900~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20kubernetes.container_name*2c*20log*2c*20*40logStream*0a*7c*20filter*20*40message*20like*20*2fStart*20sending*20SMS*20for*20notification*20id*2f*0a*7c*20stats*20count*28*2a*29*20as*20total*20by*20kubernetes.container_name*20*0a~queryId~'9ab0d135629a4aef-a6e5870-480c2a5-89a23d61-8e89bad4bfe8c23048af4294~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-production-eks-cluster*2fapplication))) that almost all sms are sent using the `celery-sms-send` pods
- [x] email send rate on prod between 2000 and 3000 emails / min
- [x] sms peak send rate on prod between 500 and 600 fragments / min

**Comment by sastels** [comment]
Various tests as documented [here](https://docs.google.com/spreadsheets/d/1bAoaO8YDRHq_J158e3y6sxGTNltHPg-QQSvVBTeGcVQ)
Main points:
- increasing concurrency increased resource usage but not send rate
- sms-send pods would scale up but then scale down in the middle of a send

We tweaked the pod requirements in the hope that that would keep them spun up. This seemed to work on 5 pods.

**Comment by sastels** [comment]
promising results on ten pods with tweaked hpa. spun up 10 pods and kept them up. Some strange bumps at the start and end that we might be able to smooth out by lowering the rate limit down to 1/s (current 5/s)
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGZEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da4006974607b9f4b0e00b1ca67974565ec5cc6c/image.png)

**Comment by sastels** [comment]
Configuration:
- 30 max celery pods
- 11 max sms-send pods
- 4 concurrency for everyone, 1/s rate limit for deliver_sms (as in prod now)
- 3 on demand nodes, rest spot instances

Get around 2900 emails / min, 570 sms / min after system ramps up

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d6a0a45eeb0930a2d8fce4f208091246cfa3cc29/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclRGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f04a9810a33a3f9e96d8ab3f4a3d72affdc1ca99/image.png)

**Comment by sastels** [comment]
So I suggest that for V1 we ship the above configuration with constant 7 nodes. (This is what karpenter was scaling up to). After this we can
- test / tweak karpenter in staging
-  slowly ramp up the email pods (for 73 pods will need to go to 10 nodes as per karpenter tests)
-  slowly ramp up sms (and perhaps get some more long codes if that's possible)

**Comment by sastels** [comment]
Possibly too timid, but here's V0.5: release the sms-send-pods but don't scale up the old celery pods yet, keep them at max 10 as they currently are. This will allow us to test that sms are being handled as expected. If all is good we'll up to 30 the next day.

https://github.com/cds-snc/notification-manifests/pull/2041

**Comment by sastels** [comment]
merged to staging!

**Comment by sastels** [comment]
[Test of 40K emails, 60K sms on staging](https://gcdigital.slack.com/archives/C05K8349YCR/p1695739102032089)
Results as expected:
- system spun up to 30 celery pods, 11 celery-send-sms
- constant 8 nodes
- CPU peaked at 62%
- no stalled messages at the end (no pods restarted)
- climbed to expected send rates
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb25aIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--17e1b411bb0bd51e84f865acc588dcfe35e81d46/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3JaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--78b493cb59e413b59a505bf12a603a1cae669d89/image.png)

**Comment by sastels** [comment]
A [double 80K / 12K test](https://gcdigital.slack.com/archives/C05K8349YCR/p1695741304921759) got similar results.

**Comment by sastels** [comment]
Release went pretty well. Two issues:
- email pods wouldn't scale down
- sms pods wouldn't scale all the way up (went 3>4 instead of 3->11)

Email issue fixed, sms to investigate...

**Comment by ben851** [comment]
Ben to QA

**Comment by ben851** [comment]
Verified that the sms sends are in the sms-send-high and medium queues. 
Verified that virtually all sms are being sent by the celery-sms-send pods (there are a few that aren't; these are notify admin 2fa)
Verified over the last 3 days that peak email send rates were approx 2000 per minute
Checked SMS Send over the past week, and it peaked around 300. I'm assuming this is due to lack of load. Will confirm w/ Steve at standup
