### ISSUE TITLE
Upgrade Kubernetes to 1.28

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#203]
# Description

As a developer of notify, I want our EKS infrastructure to be up to date with the latest patches so that the system remains secure, and supported by our vendor.

## WHY are we building?

AWS just released EKS version 1.28

## WHAT are we building?

Patching EKS in scratch/staging/prod to 1.28

## VALUE created by our solution

This will ensure ongoing reliability and security of notify.

# Acceptance Criteria

- [x] Staging upgrade is successful
- [x] All pods run properly on k8s 1.28
- [x] Logging is not interrupted
# QA Steps

- [x] Smoke test
- [x] Verify that logs are still being ingested
- [x] Verify that admin is still running

**Comment by sastels** [comment]
ready to go into prod

**Comment by sastels** [comment]
really ready to go into prod

**Comment by jimleroyer** [comment]
This didn't made it to production as we didn't approve [the PR](https://github.com/cds-snc/notification-terraform/pull/972). About to deploy this morning. 🤞
