### ISSUE TITLE
Add common IP/Firewall use case scenarios for Athena queries

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#204]
# Description

As an ops leads,
I want to have handy reusable Athena queries 
So that I can look into the Firewall data,
And I can investigate / resolve support cases quickly.

## WHY are we building?

To improve investigation speed and ease of use around ingress traffic of GCNotify. 

## WHAT are we building?

Adding and saving pre-existing Athena queries with proper names, that can cover a list of use case that developers will come up with. Sharing back these queries to developers to get feedback on.

## VALUE created by our solution

Faster resolution of Firewall related investigation.

# Acceptance Criteria

- [x] List of use case scenarios is collected following a developers' brainstorm.
- [x] Queries are added to the Athena list of saved collection.
- [x] Share back with developers during a code review meeting.

# QA Steps

- [ ] Tested by developers during the code review meeting or async afterward, getting stamp of approval.

**Comment by sastels** [comment]
Reorging our athena and adding queries here:
https://github.com/cds-snc/notification-terraform/pull/1183

**Comment by sastels** [comment]
merged PR that reorged things a bit. Still need to have a meeting to go over what additional queries / use cases we want to have covered.

**Comment by sastels** [comment]
Going to move this card to blocked until we have the discussion (hopefully the March 5 Dev Review)

**Comment by ben851** [comment]
Spoke at the dev review - Steve will implement some suggestions.

**Comment by sastels** [comment]
Suggestions I noted from meeting:
- Queries to add: more fuzzing attack queries, query to see stuff that isn’t being blocked, ie grouped by ip and / or url
- Also add a bit to retro template to ask if any queries we should make more permanent

Looking at the list of past queries, ones that stand out:
- WAF: Direct IPs hits by hosts, countries, actions and URIs
- WAF: monitor blocked requests	
- WAF: Fuzzing attack
-

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-terraform/pull/1192

**Comment by ben851** [comment]
I checked the queries and they work - two notes:
1. Even though you set the query to the notify athena database, it defaulted to "default" to me... not a big deal
2. The logs are slow to update - the latest in staging is from yesterday. Not sure if that's by design or there's something else I need to do first to update them?

**Comment by sastels** [comment]
Steve and Ben will investigate!
