### ISSUE TITLE
Move email delivery into their own dedicated queues

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#206]
# Description

As a Notify developer, I need email delivery tasks to be in their own queues so that I can treat them differently than other tasks (ex database, callbacks).

## WHY are we building?

Moving email delivery to their own queues will allow us to scale up email delivery without scaling up other tasks such as database operations or callback processing. This will also allow better monitoring and alarming for email delivery issues.

## WHAT are we building?

Move email delivery tasks to their own dedicated celery queues. Note that this task does **not** include moving the email delivery tasks to their own dedicated pool of celery workers.

## VALUE created by our solution

We will be able to scale up email delivery without scaling up other parts of the system.

# Acceptance Criteria

- [x] `deliver_email()` tasks go through their own celery queues.
- [x] wait time alarms for the new queues created
- [x] charts monitoring the new queues added to the email dashboard

# QA Steps
- [x] verify that smoke tests still pass
- [x] Verify that the new queues are being used with a cloudwatch query such as [this one](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-10800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20log*2c*20kubernetes.labels.app*20as*20app*2c*20kubernetes.pod_name*20as*20pod_name*2c*20*40logStream*0a*7c*20filter*20pod_name*20like*20*2f*5ecelery*2f*0a*7c*20filter*20log*20like*20*2fqueue*20for*20delivery*2f*0a*7c*20filter*20log*20like*20*2femail*20*2f*0a*7c*20parse*20log*20*2f.*2asent*20to*20the*20*28*3f*3cqueue*3e.*2a*29*20queue*20for*20delivery*2f*0a*7c*20stats*20count*28*2a*29*20as*20total*20by*20queue*0a~queryId~'db015112-c736-4ec6-831a-1de9f9528f41~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-staging-eks-cluster*2fapplication)))

**Comment by sastels** [comment]
PR to add alarms for the new queues
https://github.com/cds-snc/notification-terraform/pull/962

**Comment by sastels** [comment]
PR to add the queues to the email dashboard
https://github.com/cds-snc/notification-terraform/pull/963

**Comment by sastels** [comment]
These PRs can wait to be merged / released after I'm back (Oct 23)

**Comment by ben851** [comment]
Jimmy approved and improved the PRs!

**Comment by sastels** [comment]
in production

**Comment by jimleroyer** [comment]
Looks like it's working 👍

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeStNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c10b14f0348d1f49e47c47aca5bfeeab3f7e357/image.png)
