### ISSUE TITLE
clean up unused email / sms delivery queues

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#209]
# Description

As a developer, I need to clean up unused code.

## WHY are we building?

Clean up unused code related to the now unused `send-email-tasks` and `send-sms-tasks` queues.

## WHAT are we building?

Delete alarms, variables, and dashboard widgets related to these queues. Also delete code from the api repo related to these queues.

## VALUE created by our solution

Less unused code / alarms / dashboards

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [x] Verify that `send-sms-tasks` and `send-email-tasks` are no longer being used
- [x] Alarms / dashboard widgets / variables are deleted from the terraform repo
- [x] Related code in config.py (api repo) is deleted

# QA Steps

- [x] code deleted
- [x] no alarms go off
- [x] Test the 3 priorities in staging

**Comment by sastels** [comment]
WIP to remove queues from api / celery
https://github.com/cds-snc/notification-api/pull/2148

**Comment by sastels** [comment]
PR to remove queues from api / celery
cds-snc/notification-api#2148

**Comment by P0NDER0SA** [comment]
There's a PR that needs eyes on it to review and get merged.  Steve will send us a notice

**Comment by sastels** [comment]
Corresponding terraform PR!
https://github.com/cds-snc/notification-terraform/pull/1230

**Comment by sastels** [comment]
Also have to delete alarms from the google sheet

**Comment by sastels** [comment]
merged into staging yesterday

**Comment by sastels** [comment]
in production

**Comment by ben851** [comment]
Sent emails in both staging and prod in all 3 queues
