### ISSUE TITLE
Upgrade the AWS Provider in terraform to 5

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#212]
# Description

As a developer of GC notify, I would like my infrastructure code and dependencies to be up to date so that the system is secure and has minimal technical debt.

## WHY are we building?

Maintenance for security and reliability of the GC Notify infrastructure

## WHAT are we building?

Setting the AWS provider requirements to 5 in Terraform

## VALUE created by our solution

Increased security and reliability of GC Notify, reduced technical debt.

# Acceptance Criteria

- [ ] GC Notify continues to operate
- [ ] The terraform code is able to run with the new provider

# QA Steps

- [ ] Smoke Test 
- [ ] Validate Admin
- [ ] Validate that slack alarms still work (A lot of changes on the provider relate to the slack modules)

**Comment by ben851** [comment]
Provider upgraded in staging. Need to test the alarms to make sure they still work.

**Comment by jimleroyer** [comment]
The CI/CD pipeline needs some manual steps to be performed for the release. This should go on today.

**Comment by ben851** [comment]
This has been completed, the PR has the documentation on manual steps.
