### ISSUE TITLE
Build and deploy notify dev AWS and K8s

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#216]
# Description

As a developer of notify, I would like to be able to test infrastructure and kubernetes config changes on a lower state environment than staging so that I can increase the reliability of releases to high state environments (staging and prod).

## WHY are we building?

When doing large infrastructure changes, we can sometimes end up with broken environments. Since staging and prod are both considered critical, it would be good to do the initial work on this in a non critical environment.

## WHAT are we building?

Deploy terraform and manifests to the new AWS dev account

## VALUE created by our solution

Increased reliability and throughput

# Acceptance Criteria

- [X] We are able to deploy the notification-terraform against a new dev environment
- [X] We are able to deploy notification-manifests against a new dev environment
- [ ] Notify system works as expected in the new environment (fully functional)
- [ ]  Any manual steps are documented

# QA Steps

- [ ] Tested in a realistic production scenario

**Comment by ben851** [comment]
Terraform and manifests are deployed to the new AWS account. We need to investigate next steps for getting notify to actually run properly.

**Comment by ben851** [comment]
Dev admin page almost works now
- Assets are in s3 bucket
- Admin pointing to k8s api
- Lambda API new relic errors

**Comment by sastels** [comment]
incoming PR to sync assets

**Comment by sastels** [comment]
PR ready for review

**Comment by sastels** [comment]
assets change merged. Still need to sort out api lambda and New Relic handler

**Comment by jimleroyer** [comment]
Related incidents that we could consider for follow up actions in channel: 
#incident-2023-11-03-images-broken-notify

**Comment by ben851** [comment]
Managed to send emails and SMS in notify dev environment! Had to manually add verified email addresses and phone numbers due to SNS and SES being in sandbox mode.
I have opened tickets with AWS to enable production mode

**Comment by ben851** [comment]
Both are out of sandbox mode... Will do some testing today.

**Comment by ben851** [comment]
Steve has been running soak tests against Dev - QA successful for now! Need to open a card for Lambda and some broken images
