### ISSUE TITLE
Fluent Bit Emitters are paused during high load

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#221]
## Describe the bug 

When running under high load, fluent-bit emitters for celery are being paused due to memory buffer limits, leading to log loss.

## To Reproduce

This is difficult to reproduce but seems to occur when karpenter has provisioned a large single node to run all celery instances at once. The volume of logs coming through the pipeline overloads fluent bit.

## Expected behavior

Fluent bit should continue to process logs even under high load

## Impact

Potential log loss during critical periods

**Comment by ben851** [comment]
In indirect fix would be to ensure there is a split celery across multiple nodes using a pod topology spread constraint.

**Comment by ben851** [comment]
Upped the memory buffer limits of the celery pipeline to 150mb. Seems to have fixed the issue in staging

**Comment by ben851** [comment]
Ready to merge to production, will do so today.

**Comment by ben851** [comment]
Deployed to production, will evaluate over the coming days.

**Comment by ben851** [comment]
No paused emitters over last two days

**Comment by sastels** [comment]
all still looking good after a week.
