### ISSUE TITLE
Split celery between spot and primary instances

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#232]
# Description

As a developer/operator of notify, I want the celery batch processing to autoscale without causing any outages. 

## WHY are we building?

When celery is deployed to spot instances only, it occasionally drops to 0 pods for a minute or two, causing momentary outages.

## WHAT are we building?

Create primary and scalable deployments in k8s manifests for celery. Primary deployments do not scale and are always running on the ON_DEMAND nodes. Scalable only runs on spot instances

## VALUE created by our solution

Increase notify performance and reliability

# Acceptance Criteria

- [X] A new deployment of celery only runs on on demand instances
- [X] A new deployment of celery only runs on spot instances
- [X] We can tune the scalable instances

# QA Steps

- [x] After deployment, verify that the two deployments are only running on their respective instances
- [x] Verify that there are no periods where we send 0 emails - even if scalable is showing 0 pods.

**Comment by ben851** [comment]
Debugging staging - have an intermittent issue with document download pods not being scheduled during nightly perf test. Will continue on this today.

**Comment by ben851** [comment]
PR opened to move this to prod but staging has been super unstable (pretty sure unrelated to these changes) so we're holding off until things calm down.

**Comment by ben851** [comment]
Not quite - we need one more release on Monday to lower the nodes before we can QA it

**Comment by ben851** [comment]
This has been done, Ben to come up with QA steps

**Comment by ben851** [comment]
We had a scenario yesterday in staging where all email pods were on spot instances even though we said don't do that. I have created a new solution with double deployments. Merged to staging, Steve will update the dashboards, Ben has a PR incoming to update the alarms (in dev testing right now)

**Comment by ben851** [comment]
This is in staging, Steve ran rollercoaster tests. The environment was stable even thought scalable pods went down to 0 during node switches... 

This should be released to prod today, will require coordination with OL

**Comment by sastels** [comment]
Steve will QA
