### ISSUE TITLE
Reduce log output of Celery

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#233]
# Description

AS a system op,
I want less logs sent by Celery because it overflows fluentbit/CWAgent,
So that the system works better.

## WHY are we building?

_Why do we need this?_

## WHAT are we building?

_What does that entail?_

## VALUE created by our solution

Less $$$ and easier to read logs

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] reduce logging
# QA Steps

- [ ] Check that the changed logs are not in production

**Comment by ben851** [comment]
Jimmy put in a PR and someone approved it!

**Comment by sastels** [comment]
merged and in production

**Comment by sastels** [comment]
Relevant logging stops after the PR was merged :+1:
