### ISSUE TITLE
Rotating secrets

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#24]
# Description

As a security guardian of GCNotify,
I want to rotate secrets,
So that I can guarantee that fresh rotation prevents reversal of other secrets.

## WHY are we building?

Make sure our secrets are safe with fresh rotations.

## WHAT are we building?

Action plan to change our secrets and execute on it.

## VALUE created by our solution

Safer secrets and working out our secrets rotation muscle.

# Acceptance Criteria** (Definition of done) 

- [x] Write an action plan with detailed steps on secrets rotation.
- [x] Analyze which secrets need to be changed? Is there an order the secrets need to be rotated in?
- [x] Secrets are rotated in production and staging
- [x] Use scripts so that this is automated and straight forward (optional)
- [x] Allow the transition of old to new secrets with overlapping for a certain timeframe
- [x] Secrets ADR up to date
- [x] Ensure that redundant secrets are changed everywhere these are referenced
- [x] [Make sure rotation for all used secrets are documented](https://docs.google.com/document/d/1BkAkz45CVQRGQSNwN018beTebrbTUNpyTpGEaO7Clyc/edit#heading=h.rrmg1rzgyn4w)
- [x] Write a "So you want to add a secret to Notify" guide that requires documentation such as discussed above, and also insists that a plan to rotate without downtime be in place.

# Remaining tasks

- [x] Send communication to users about upcoming password reset once the main salt is rotated. [Related UX team task](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1163).
- [x] Add SalesForce secrets to the secret rotation document and ADR. ( @jimleroyer )
- [x] Write a "So you want to add a secret to Notify" guide that requires documentation such as discussed above, and also insists that a plan to rotate without downtime be in place. Make sure to document proper process to document how to update passwords in LastPass. @ben851 
- [x] [Rotate the _dangerous_ secret key for signing data at rest.](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/96) @sastels 
- [x] Rotate the salt secret key for hashing the users' passwords.
- [x] Update the [Secrets in Notify ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2022-04-14.secrets-usage.md) for updated usage. (@jimleroyer)
- [x] [Polish the next steps section in the secrets ADR.](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/91) @sastels 
- [x] Create Github secrets notes in LastPass for each repository that has these, and optionally not include the ones that are already in the Terraform variables files. @sastels 
- [x] Document in the ADR the Celery task performing secrets rotation.
- [x] Clean up LastPass folders.
- [x] Passwords for other services that might require rotation (such as GCA, opsgenie, etc...)
- [x] Change database username/password in production environment.
- [x] [Ensure Redis buffer queues are signed correctly based on the new keys] @sastels (https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/88)
- [x] Clean up the Google Doc ADR. Optionally convert to an ADR in GitHub @sastels 
- [x] Clean up code that accepted new salts or DANGEROUS_SALT @sastels 
- [x] June 15 or later: rotate SECRET_KEY again create a new k2 and rotate: k0,k1 -> k1,k2
- [x] deactivate old [staging iam user credentials](https://us-east-1.console.aws.amazon.com/iamv2/home?region=ca-central-1#/users/details/notification-staging-tf-user?section=security_credentials)
- [x] after confirming that the deactivation on staging didn't break abything, deactivate old [production iam user credentials](https://us-east-1.console.aws.amazon.com/iamv2/home?region=ca-central-1#/users/details/notification-production-tf-user?section=security_credentials)
- [x] review the [secrets ADR](https://github.com/cds-snc/notification-adr/blob/main/records/2023-05-17.secrets-list.md) and fill in any that are missing
- [x] copy the table to the rotating secrets doc and remove the depreciated secrets from that copy 
 
# QA Steps

- [x] Review of the action plan took place before execution of secrets rotation.
- [x] Tested in a realistic production scenario

# Related tickets

[Quick rotation of SECRET_KEY and DANGEROUS_SALT keys with no downtime](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/720)

**Comment by jimleroyer** [comment]
A few PRs are up and ready to be reviewed. @ben851 to review some (and Jimmy on the OOP refactoring).

**Comment by ben851** [comment]
We have introduced a fix for the new relic lambda api key issue:
##Symptoms
- The secret injection specifically for new relic on the lambda is convoluted and is done in three different places, three different ways.
- For staging and production, the secret was set as an environment variable using the notification-terraform github actions secrets, but it doesn't appear that it was actually used.
- Instead, the notification-manifests .env file also had this value set, and when new deployments were made in this repository, a back end call was made to the lambda function to refresh the function
- The lambda function would then reboot and run a shell script that would attempt to pull the license key from the aws parameter store but ONLY if the environment variable did not exist. There seems to be some sort of conflict in the way that the key is pulled when using the parameter store.
## Fix
- We are now explicitly setting the api key as an environment variable in the notification-terraform code, and referencing the value stored in the aws secret manager
- The secret manager gets its value from terraform as an environment variable. In staging and production, this is set using the github actions secret store. 
- This is a quick fix that will be remediated in a cleaner way when we do secret migration/cleanup (separate card)

**Comment by sastels** [comment]
- [PR with refactored salts](https://github.com/cds-snc/notification-api/pull/1782) ready to merge into staging and test there
- [PR with monthly resigning tasks](https://github.com/cds-snc/notification-api/pull/1789) needs a good local test before sending out to review

**Comment by sastels** [comment]
- Code for signing key rotation is done and tested locally.
- Releasing pieces into prod a bit at a time
- Next going to look at the rotating the remaining secrets as noted on the ADR

**Comment by jimleroyer** [comment]
* A few more secrets are getting rotated.
* Calvin helped us on switching authentication methods for CDS public ECR.
* Latest state in [rotation document](https://docs.google.com/document/d/1RXlbgIlYzVY5DMWix81vIZluTp-FBLMz8HCYi-v7I7s/edit#heading=h.wz9ztt5zelei).
* Clean up is remaining.
* 90% of used secrets are rotated.
* 25% of work remaining.

**Comment by jimleroyer** [comment]
Moving back the task into the refined column as we are in the bug bash week.

**Comment by jimleroyer** [comment]
@sastels defined the following remaining tasks to do:

Re current state of secrets rotation, ie what's left:
2 code-y ones:

* the signing ones where we need to finish up and test the resigning tasks
* the db master password one where we were talking about adding a new superuser but nothing has been coded yet, There's a third party terraform provider that will allow us to do it in terraform
   * this hasn't been coded yet but would be a good one with small parts, ie add a new user, switch the app to use it, rotate the master password

And 3 non-code ones:
* the ops genie api key to track down
* Pat tried to delete the old GCA keys but couldn't so we should figure that out
* we should rotate the FreshDesk key (which will cut our connection to Freshdesk for a bit but we have the "email to helpdesk instead" code working for that)

**Comment by sastels** [comment]
Also, as suggested by SRE, we are [removing the AWS key used to connect to CDS' public ECR and replacing with OIDC](https://github.com/cds-snc/notification-admin/pull/1524). This is still in progress.

**Comment by jimleroyer** [comment]
* Freshdesk API key were rotated yesterday.
* Will look into opsgenie secrets today.

**Comment by jimleroyer** [comment]
[Started a Slack thread](https://gcdigital.slack.com/archives/C011SV2PM1B/p1681922012915279) on upcoming users communication with Yael and Yedida.

**Comment by jimleroyer** [comment]
I think I know how to rotate the opsgenie API key. I will update the documentation. But there are keys I am not sure how they're used; I want to ask Pat or Max.

**Comment by jimleroyer** [comment]
@sastels Using IAM roles instead of identities to connect to public ECR from GitHub actions.

**Comment by jimleroyer** [comment]
To rotate the opsgenie key:

1. In opsgenie, update the API key under our Notify team section,
1. Update the github secret with the whole URL, 
1. Redeploy the SNS module in production to deploy the new API key,
1. Update the LastPass secret notes for tfvars with the new API key.
1. ClickOps an alarm in production to make it trigger a paging alert, such as `documentation-replicas-unavailable` to redirect alarm action to critical SNS ARN and trigger it by taking down one of the pod.

**Comment by jimleroyer** [comment]
The opsgenie API key was rotated succesfully this morning.

**Comment by jimleroyer** [comment]
A meeting with the UUX team will occur next week on the 4th of May to decide when to rotate the secrets related to users' passwords and hence force password reset.

**Comment by jimleroyer** [comment]
Jimmy and Steve to sync on what's left.

**Comment by jimleroyer** [comment]
Meeting at 10 to sync.

**Comment by jimleroyer** [comment]
I wrote the salesforce secrets documentation and will meet Steve about the secrets usage, especially wrt the dangerous salt references.

**Comment by jimleroyer** [comment]
@sastels did create Github secrets notes in LastPass, but not all done, need to sync SRE team.

**Comment by ben851** [comment]
* [Created first iteration of how to store a secret](https://docs.google.com/document/d/1BweaV-41T2e1uUOnHPX6dine7Ka89mTxdET-6AFjcqg/edit#)

**Comment by jimleroyer** [comment]
I opened a PR for updating the secrets rotation ADR with latest changes:
https://github.com/cds-snc/notification-adr/pull/41/files#r1183093931

**Comment by jimleroyer** [comment]
Steve cleaned up some of the unused secrets that are in the Github repositories yesterday.

**Comment by sastels** [comment]
The pr-bot secrets are managed by SRE so we've moved them to org level secrets rather than repo secrets

**Comment by jimleroyer** [comment]
Today we are meeting with Yael to schedule the password reset.

**Comment by jimleroyer** [comment]
@sastels and @jimleroyer to review document for [Created first iteration of how to store a secret](https://docs.google.com/document/d/1BweaV-41T2e1uUOnHPX6dine7Ka89mTxdET-6AFjcqg/edit#)

**Comment by jimleroyer** [comment]
The miro board for password reset process to take in account for the overall user experience:
https://miro.com/app/board/uXjVOAkOvNU=/

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-api/pull/1789 has been tested locally and is ready for someone else to kick the tires. Then we can merge and test in staging.

**Comment by ben851** [comment]
2 Secrets left to do:
* Secrets Key
* Password Salt

**Comment by sastels** [comment]
tweak to utils to remove DANGEROUS_SALT from the invite tokens
https://github.com/cds-snc/notification-utils/pull/204

**Comment by sastels** [comment]
GitHub ADR with public info about our secrets
https://github.com/cds-snc/notification-adr/pull/43

**Comment by sastels** [comment]
DANGEROUS_SALT rotated in staging and production.
SECRET_KEY rotated in staging. Still need to rotate in production

**Comment by sastels** [comment]
Clean up code:
https://github.com/cds-snc/notification-utils/pull/207
https://github.com/cds-snc/notification-api/pull/1878

fix resigning script so it resigns the notifications table in batches:
https://github.com/cds-snc/notification-api/pull/1868

**Comment by ben851** [comment]
* Ben to create a single folder in google drive for secret management and link documentation in there.

**Comment by sastels** [comment]
June 15 or later: rotate SECRET_KEY again

**Comment by ben851** [comment]
* Steve is on vacation, will await his return before deactivating production.

**Comment by sastels** [comment]
deactivated the old iam credential this morning, so far so good.

**Comment by sastels** [comment]
- cleaned up table of secrets doc
- next want to copy this table into the rotating secrets doc and remove the deprecated secrets. Steve and Jimmy will pair on it

**Comment by sastels** [comment]
:tada: Done secrets for now! :tada:
