### ISSUE TITLE
Scan files is timing out

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#25]
# Describe the bug 

Our internal malware detection tool, scan-files, to filter out bad GCNotify's attachments, is timing out more than 11 minutes.

The bug is handled by the SRE team via this ticket:
https://github.com/cds-snc/platform-core-services/issues/297

This ticket is to keep track of the bug and also update our alarms accordingly, before and after the fix is applied.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation
(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

**SEV-3**

## To Reproduce

It's difficult to reproduce on purpose, but at the moment, this happens every business day, as demonstrated by this graph:
![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/1785b6e7-1605-4326-bcd7-210d4133e50b)

## Expected behavior

Timeout with scanfiles to happen rarely, rather than regularly.

## QA

- [ ] Turn alarm back to its previous settings and verify that it is not triggered (much)

## Impact

* Delayed emails with attachments.
* Noise pollution in #notification-ops.

Impact on Notify users: Emails with attachments are delayed.

Impact on Recipients: Emails with attachments are delayed.

Impact on Notify team: Noise pollution for alarms.

## Additional context

We will relax the alarm until the fix is applied ([trackable via this ticket](https://github.com/cds-snc/platform-core-services/issues/297)). Once the fix is applied, we can revert to the initial warning alarm setup.

**Comment by sastels** [comment]
Pat plans to start on this the week of the 22nd

**Comment by jimleroyer** [comment]
Pat investigated for a fix and applied one for scan files module, [upgraded in this PR](tps://github.com/cds-snc/notification-terraform/pull/756).

Potential root cause:
> Update to the latest s3_scan_object module version which increases the transport lambda's timeout to 120s. This is to fix the cases where the transport lambda must wait for a new Scan Files lambda function cold start.

**Comment by jimleroyer** [comment]
We also changed the alarm back to normal for staging environment, warning mode, to see if it would trigger as much now that the fix was applied.

**Comment by jimleroyer** [comment]
What Pat tried didn't work out unfortunately. Still investigating.

**Comment by jimleroyer** [comment]
Pat is still investigating and made new PR yesterday to test it out.

**Comment by ben851** [comment]
* Pat put in a PR to upgrade the object scan to use an sqs queue. This has been approved and should be merged to staging.

**Comment by ben851** [comment]
* @jimleroyer to sync with Pat re: sqs changes.

**Comment by ben851** [comment]
* Released yesterday, Pat is QA'ing by verifying that the execution times are in line with expectations.

**Comment by sastels** [comment]
Still having timeout warning alerts :/

**Comment by jimleroyer** [comment]
Pat and Steve M. are looking into a potential document-download-api bug as the remaining timeout would be a different issue than last time with the AWS setup.

**Comment by ben851** [comment]
* Jimmy to provide an update today.

**Comment by jimleroyer** [comment]
Pat reported:
> happy to report no timeouts since the fix went in for future dates:

![image.png](https://images.zenhubusercontent.com/614b3e364039e00aa3137935/d3813ea3-3d39-496a-993e-d2b94a62900a)

Let's move this task to QA to wait a complete week to monitor on the files scanning timing out (or not).

**Comment by jimleroyer** [comment]
Moving it to done as last event was seen on June 13th. We consider this fixed for good now.
