### ISSUE TITLE
Get count for incident actions, tech debt and bugs and report  in Slack #notify-dev channel

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#259]
# Description

As a project manager,
I want to know how much tech debt I accumulate 💩,
So that I have a barometer on these levels
And kick off special operations to get rid of these.

## WHY are we building?

Lower down our tech debt, bugs and incident actions.

## WHAT are we building?

A counting and reporting mechanism of how we lag behind on known issues (bugs, tech debt and incident actions).

## VALUE created by our solution

Keep track of our known issues levels.

# Acceptance Criteria

- [x] Report count of incidents actions in the Slack #notify-dev channel.
- [x] Report count of tech debt in the Slack #notify-dev channel.
- [x] Report count of bugs in the Slack #notify-dev channel.

# QA Steps

- [x] Manually run the github action and see results in the Slack #notify-dev channel.

**Comment by jimleroyer** [comment]
New PR for this, to test multi-labels tracking:
https://github.com/cds-snc/notification-planning-core/pull/260

**Comment by jimleroyer** [comment]
Several following PRs were approved and merged. We have a working counts of incident action tasks, bugs tasks and technical debt tasks that will get reported every Monday morning in the #notify-dev channel. Let's see what happens on Monday morning for QA but it should be good. 

We can refine this later if we want.

**Comment by ben851** [comment]
Saw this post to notify-dev this morning! Consider it QA'ed!
