### ISSUE TITLE
Re-enable geo location of logged in users with GCNotify

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#261]
# Description

As a security op in CDS,
I want to track users logging into GCNotify admin with their IP and location,
So that I can increase my monitoring coverage that will feed into our security process and tools
And improve overall security of GCNotify.

## WHY are we building?

More security within GCNotify.

## WHAT are we building?

Logging IP and location of logged in users using GCNotify. 

## VALUE created by our solution

We know who's using our software.

# Acceptance Criteria

- [ ] The location and IP of logged in users are tracked in the `login_events` database table.
- [ ] Revive the repository where this was living - it has since been archived, and thus we are running on an older version

# QA Steps

- [ ] Check the `login_events` table in production to see if geolocation and IP are now logged.

**Comment by jimleroyer** [comment]
Related PR:
https://github.com/cds-snc/notification-manifests/pull/2268

**Comment by sastels** [comment]
Jimmy to check with SRE / Core about de-deprecating the CDS geolocation service.

**Comment by jimleroyer** [comment]
Deployed to production. I tested and it works, but someone else should double check with a QA.

**Comment by ben851** [comment]
@sastels to QA
