### ISSUE TITLE
Create AWS budget alerts

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#273]
# Description

As a dev ops,
I want to control budget for each of my environment,
So I do not get bad pricey surprises by end of month.

## WHY are we building?

Control our budget tightly in AWS.

## WHAT are we building?

AWS alarms around total budget in each environment we have (and automated ones).

## VALUE created by our solution

* Better money spending.
* Earlier discovery of bugs.

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [x] Alarm for total AWS budget for each environment (dev, test, QA, production).
- [x] Set in Terraform, for all environments, including new automated ones.

# QA Steps

- [x] Set a very low budget threshold for test and staging environments, wait a bit for these to trigger.

**Comment by ben851** [comment]
TF schema for budgets:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget

**Comment by ben851** [comment]
Was busy with prod releases yesterday. Will aim to do this today.

**Comment by ben851** [comment]
Almost did it yesterday, doing it this morning.

**Comment by jimleroyer** [comment]
An iteration of alerts has been completed where these are sent via emails. We'd like to standardize with Slack alerts for a future iteration.
