### ISSUE TITLE
Blazer needs to move to a dedicated Read Only DB

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning-core#276]
## Description
Move Blazer to its own dedicated read only instance.

- [ ] Determine if there will be additional costs for a new DB and get approvals from @foudamo 
- [ ] Notify-Core is now going to explore the additional work in this ticket (another cluster/ node- other options)

One of the ways to do this:

1. On the RDS Proxy side of things, the best I can find for stoping Notify from using a specific instance in the cluster is involved but should work:
2. Create a new private subnet in the VPC.
3. Create a new dedicated reader instance in the cluster that exists in the new subnet (we’ve never tried to do this before).
4. Do not add the new subnet to the RDS Proxy endpoints.
5. Update Blazer config to only connect to the new reader.

## Acceptance Criteria
Given some context, when (X) action occurs, then (Y) outcome is achieved 

- [ ] Create an ADR that discusses the options on how to best serve the blazer queries
- [ ] Set Blazer up to only use its own dedicated read only instance
- [ ] If blazer doesn't have its own dedicated instance, we need another way to run queries with joins (look into this step, only if the above fails)

**Comment by ben851** [comment]
I've put in a PR that implements a separate read instance in the database cluster.
Notes:

Originally I wanted to create a complete separate cluster with replication enabled, but this doesn't seem to be supported for aurora databases
I also wanted to put in a secondary read only proxy that went to this instance specifically, but that also is not supported
When we upgrade to Postgres 15 we can convert this new instance into a serverless instance to save money. I have left the config for this in this PR but commented out.

**Comment by ben851** [comment]
Further note, aurora read replicas seem to be best practice for this anyway.

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html#Aurora.Replication.Replicas

**Comment by jimleroyer** [comment]
@ben851 to open a ticket with AWS to get their opinion on how we can isolate the GCNotify database exclusively for Blazer.

@jimleroyer to open a ticket on the Blazer github issues forum to inquire on best practices with Blazer in production, i.e. how do they grant access, which queries do they run and how do they isolate queries ran in production from affecting normal production load.

**Comment by ben851** [comment]
https://support.console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=170558991301312&language=en

**Comment by sastels** [comment]
Ben to review AWS' response

**Comment by sastels** [comment]
AWS suggestions probably won't work to well for us (at least, won't work if we want to allow folks to do whatever queries they want).

**Comment by sastels** [comment]
Jimmy will reply to AWS's support ticket response.

**Comment by jimleroyer** [comment]
Replied to aws support with additional context and solutions we are considering. Let's wait and see.

**Comment by jimleroyer** [comment]
AWS support proposed to meet and we suggested for next Monday at 8h30, waiting for confirmation.

**Comment by ben851** [comment]
Meeting confirmed w/ AWS for 8:30 EST on Feb 5

**Comment by jimleroyer** [comment]
Ben met with AWS and they redirected us to the Aurora team. They confirmed that the RDS proxy is limited for what we mean to do.

**Comment by jimleroyer** [comment]
AWS had to respond back to our ticket but there were no updates.

**Comment by jimleroyer** [comment]
Ben has requested for another meeting with AWS for next week.

**Comment by ben851** [comment]
Meeting with AWS on Wednesday.

**Comment by ben851** [comment]
Spoke with AWS yesterday. They recommended setting up logical replication manually. They also suggested that we speak with our AWS Solutions Architect that we have under our support plan with AWS.

**Comment by ben851** [comment]
Need to estimate costs on manual logical replication. 

Could also look into serverless.

**Comment by jimleroyer** [comment]
Jimmy to copy paste the solution that was proposed by the solution architect, if we want to protect our prod env from blazer.

**Comment by jimleroyer** [comment]
Moving to review as we need to show this into one of our code review session.

**Comment by jimleroyer** [comment]
We have no ADR opened for this atm. We can make a short one, not much detailed but describing the options we had along with the cons/pros, and mention we selected the status quo in favor of not letting non-devs choose our blazer instance and rather use the quicksight option.

**Comment by ben851** [comment]
ADR created and submitted for review
