### ISSUE TITLE
Get the generic short code process 

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#278]
# Description

As a product manager,
I want to increase the sending rates for SMS within GCNotify,
And its reliability,
So that I can send faster, from a trusted short code number.

## WHY are we building?

* Faster throughput
* More reliable
* More trust from users

## WHAT are we building?

Migrating our existing 2FA short code into a generic usage. See [details of the process for the 2FA shortcode](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/182) for related information.

## VALUE created by our solution

* Faster throughput.
* More trust.
* Potential 3 numbers short code.

# Acceptance Criteria

- [x] Get generic short code.
- [x] Update the ADR on short code.

# QA Steps

- [x] Review the ADR updates.

**Comment by jimleroyer** [comment]
We met with the CWTA representative yesterday. It went pretty well as she understands our cases and think we could get an exception, given we are gov and depending our guidelines and safety measures. Next steps:

1- Send to the CWTA representative the name of our AWS TAM.
2- Send to the CWTA representative previous reasoning for short code denials from the CWTA.

**Comment by jimleroyer** [comment]
Built up a draft response to the CWTA representative, sent it to our channel for management, product and policy to review:
https://docs.google.com/document/d/1ZMw9Cz9MjkSIabw_UEK1j7oRLjOWTkq_uO_M0-nvg7o/edit

**Comment by jimleroyer** [comment]
I got the document reviewed today by Yael and Ioana. I accepted most of their suggestions and waiting back on a few ongoing thread. I will remind them again tomorrow or setup a sync meeting to get things going (we need to send reply ASAP now).

**Comment by jimleroyer** [comment]
The ADR changes for the short code has been reviewed by Yael and Ben. This has now been merged. It's ready to be moved to done by the kanban master of the universe.

**Comment by jimleroyer** [comment]
We sent the email to the CTA representative with requested information on last Friday. I also gave a heads up to our AWS TAM as he might get contacted by CTA.

**Comment by ben851** [comment]
No response from AWS/CTA

**Comment by ben851** [comment]
Yael has re-sent the email to the generic inbox instead of the direct person.

**Comment by jimleroyer** [comment]
We got an answer from the CTA representative. It looks promising! The suggested 3 letter codes that we asked for would be available, giving us even more trust and legitimacy. Yael and I will work on a new application, except we need to first find the proper format that they want.

**Comment by jimleroyer** [comment]
Jimmy and Yael to work on this today.

**Comment by jimleroyer** [comment]
Yael and I met, we started work on a new application. We also sent questions to CTA about cost and the request itself.

**Comment by sastels** [comment]
Jimmy and Yael to work on this today and/or this week.

**Comment by ben851** [comment]
Jimmy needs to send emails to users of GC Notify to provide screenshots of their registration flow (for consent of sending notifications).

**Comment by jimleroyer** [comment]
Got screenshots from Nova Scotia and Cadets. Put these into the document and will contact Melissa that these are in for final review and translation. 

Beth messaged me though: she thinks there might be better images for contact info registration that we could get. I will speak with her a bit but things should not change too much from here.

**Comment by jimleroyer** [comment]
Got the current request reviewed by Melissa and agreed on changes. Also we got to the conclusion that only one of the two screenshots sent by users for consent approval might be good enough. Hence I went on a hunt for 3 more SMS users and sent them email today to recently logged in team members.

**Comment by jimleroyer** [comment]
We do not have nice enough screenshots for agreements with the users consent, maybe. I need to speak with @yaelberger-commits and sync with her on the topic.

**Comment by sastels** [comment]
CTA sent a different form for us to fill out. Yael leading the effort!

**Comment by jimleroyer** [comment]
I opened a ticket yesterday to ask for AWS form that they sent to CTA, as the latter is requesting the same form to review our amendment. Yael is waiting a bit in the hope we can get it soon and change some information on our to be reviewed doc.

**Comment by jimleroyer** [comment]
Yael didn't sent the email yet. 

We got an reply on the AWS support ticket informing us that they do not have the original short code form filled: that would be the SMS aggregator that fills these apparently. 🤷‍♂️

**Comment by jimleroyer** [comment]
Yael sent the email yesterday. We are waiting on the CTA response at this time.

**Comment by jimleroyer** [comment]
* The CTA representative gave us the official form that was used for our own short code, filled by the aggregators.
* We will have to keep the 6 letter code as a 3 letter code would be considered a new code.
* We will amend the existing 6LC for a generic usage.
* We have to fill the aggregator form and update it again.

**Comment by ben851** [comment]
Jimmy, Melissa, and Yael met and modified the original form sent by telecoms and reviewed it. It will be sent back to  the CTA.

**Comment by sastels** [comment]
Waiting for CTA to get back to us.

**Comment by jimleroyer** [comment]
CTA got back to us this morning, validating our request as good. 

I sync'ed with our new AWS TAM to give him a heads up for the amendment, as we need to send the request through our AWS provider.

I opened an AWS ticket with the amendment request to explain the situation and ask them to forward it to our agggregators. I expect a few back and forth most likely between us and AWS.

**Comment by sastels** [comment]
AWS giving our request to their SMS expert.

**Comment by jimleroyer** [comment]
Still waiting on AWS response who will contact us once they got the aggregator response on their end.

**Comment by jimleroyer** [comment]
AWS got back to us yesterday evening to say that they didn't get a response yet from the aggregators and telecoms but are keeping an eye on it.

**Comment by jimleroyer** [comment]
AWS responded that our amendment has been approved by the telecoms and aggregators! We can move this to QA just to see if there is anything else to do before closing this one but chances are we will move it to done tomorrow.
