### ISSUE TITLE
Setup AWS VPN for database access

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning-core#28]
## Description

As a developer,
I want a secure way to access the Notify database instance locally,
so that I can troubleshoot issues Notify data without worrying about unauthorized access to the data.

## Acceptance Criteria** (Definition of done) 

- [x] Setup [AWS VPN for Staging and Production accounts](https://docs.google.com/document/d/1uFZ2josUt9-3fbohwauR8n2ACzel5wNqHtEgN8xepvE/edit#heading=h.8y8kbj277q9j).
- [x] [Configure VPN access for each team member](https://aws.amazon.com/premiumsupport/knowledge-center/client-vpn-multiple-users-same-endpoint/) that requires access to the database.
- [x] Remove the jumpbox
- [x] [ADR for the VPN choice and options](https://github.com/cds-snc/notification-adr/pull/57).

## QA Steps

- [x] Connect to the Staging and Production VPN using your credentials.
- [x] Test that you can access the database while connected to the VPN.
- [x] Test that you can access Redis while connected to the VPN.
- [x] Check that the jumpbox pods are no longer deployed to Kubernetes.

## Additional context

We currently have hasura to audit the manually executed SQL statements in production by developers but it's limited in some ways:

* Admin shared account: there is no way to exactly identify who executed what, i.e. we only have the what.
* There are times when we need to bypass hasura as the tool is limited. For example, to download the `notifications` table in its entirety (or dump the whole database to debug locally) is difficult with Hasura.

Hence this card would increase the overall security on how we access the database.

**Comment by ben851** [comment]
Note that the VPN adds $200/month in costing to each AWS account.

**Comment by ben851** [comment]
Merged to staging. Need to test.

**Comment by ben851** [comment]
Running into some DNS issues in dev. Debugging

**Comment by ben851** [comment]
Will take a look at the DNS issues today. 

I've been working on the internal DNS (unrelated) and have put a PR here
https://github.com/cds-snc/notification-terraform/pull/1133

**Comment by ben851** [comment]
Did some more internal DNS refining yesterday. Switched nginx to an existing load balancer to better align with our releases.

**Comment by jimleroyer** [comment]
Ben is planning to roll out the Helm changes into staging this week. The migration only includes the Hasura utility and its dependencies, hence this is a relatively safe and incremental migration.

**Comment by jimleroyer** [comment]
Ben needs a review on this PR:
https://github.com/cds-snc/notification-manifests/pull/2340

**Comment by ben851** [comment]
Created two PRs for blazer. Will get reviewed today

**Comment by ben851** [comment]
Refactored DNS to comply with Google OAuth requirements
Blazer working in dev! Waiting on PR for staging

**Comment by ben851** [comment]
Blazer working in staging. Will put in a PR to move this to prod.

**Comment by ben851** [comment]
Workflows added in prod, will test with next release.

**Comment by ben851** [comment]
Added documentation and debug pod script to notification-attic
https://github.com/cds-snc/notification-attic/pull/62

**Comment by jimleroyer** [comment]
We just need to remove the jump box to get this card in qa.

**Comment by ben851** [comment]
https://github.com/cds-snc/notification-manifests/pull/2508

**Comment by ben851** [comment]
Merged, jump box manually removed in staging and prod

**Comment by ben851** [comment]
@P0NDER0SA to QA

**Comment by P0NDER0SA** [comment]
QA nearly complete.  All steps worked except for the fact that there is still a hasura pod.
