### ISSUE TITLE
Use the shortcode for GCNotify SMS

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#280]
# Description

As a Notify developer, I need to use the shortcode for GCNotify SMS messages

## WHY are we building?

Start using the shortcode for important texts

## WHAT are we building?

use the shortcode for all GCNotify SMS

## VALUE created by our solution

Verify that the shortcode will work, and also a more reliable way to get GCNotify's 2FA

# Acceptance Criteria

- [ ] 2FA SMS from GCNotify sent using the shortcode

# QA Steps

- [x] log into Notify using SMS 2FA
- [x] verify that the short code was used to send the SMS
- [x] verify that the notification is correct in the database

**Comment by ben851** [comment]
@ben851 to QA

**Comment by ben851** [comment]
Confirmed SMS was sent by short code in both my phone and database.
