### ISSUE TITLE
Move celery workers to AWS Lambdas

### ISSUE THREAD

**Issue by stephenyates-gc** [cds-snc/notification-planning-core#29]
### Task Description
What task needs to be done?

### Task Outcome
Why are we doing this? What will be the outcome?

### Acceptance Criteria
- [ ] List of what needs to be completed.

**Comment by jimleroyer** [comment]
I will close this one as moving all Celery workers is deemed unrealistic with current resources and constraints. The ADR for explaining differences between lambdas and kubernetes should cover why in task #254. There are a few components we could move to lambdas though but we will have more specific tasks for these, such as processing receipts from SNS (potentially -- not certain).
