### ISSUE TITLE
ADR for the phone pool system

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#290]
# Description

As a technical steak holder 🥩  ,
I need to understand and review our options on how we can isolate SMS codes,
so that we have consensus on the needs, requirements and solutions.

## WHY are we building?

Provide technical analysis and review of how we isolate codes. This is needed for us to dedicate certain code to certain usage by users. For example the short needs to be exclusively reserved for 2FA usage, or the dedicated long codes need to be reserved for certain services.

## WHAT are we building?

We are building an abstraction for pool of codes that can be associated per service or per template or by default (as a fallback).

## VALUE created by our solution

For the ADR, 

* this provides a track record for the organization of our technical decision,
* this provides a platform for review and consensus.

# Acceptance Criteria

- [ ] Review by notify core team.
- [ ] Review by notify product manager and app core dev lead.
- [ ] Review or heads to the platform core team.
- [ ] Review or heads to the security team.

# QA Steps

- [ ] Signed off by steak holders 🥩✋

**Comment by ben851** [comment]
Jimmy used a cool mermaid graph!

**Comment by jimleroyer** [comment]
@sastels reviewed and left a comment. There is a confusing part that I will fix today.

**Comment by jimleroyer** [comment]
I will make changes to fix the bad copy/paste text I introduced and that led to confusion.

**Comment by ben851** [comment]
Jimmy is working on it!

**Comment by jimleroyer** [comment]
Just pushed the ADR fix to the PR.

**Comment by sastels** [comment]
Steve will go take a look!
