### ISSUE TITLE
Move Manifests Secrets to 1Password and Terraform AWS Secrets Manager Code

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#297]
# Description

As a developer of GC Notify, I would like all of our kubernetes secrets to be accessible using in a common way so that we can standardize the creation and management of secrets. 

## WHY are we building?

We are looking to standardize our approach to storing and reading secrets from a single Golden Source.  This source is 1password.

## WHAT are we building?

- We will be identifying and consolidating any secrets being used in the manifests repository and moving them to our TFVars files in 1password
- We will write Terraform variables to read the values from 1password and then add them as terraform AWS Secrets Manager code (to be created/managed by terraform releases)

## VALUE created by our solution

- Creates a single source of truth for any and all secrets used by the manifests repository
- Makes the repository, and code for GC Notify as a whole much easier to maintain and understand

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [x] When we do a terraform release with an updated secret in 1pass, they get stored properly in the AWS Secrets Manager

# QA Steps

- [x] See if the new secrets are in AWS secrets manager (staging and prod)

**Comment by P0NDER0SA** [comment]
Investigating Variables and Secrets in the Admin Portion (Helmfile) in manifests.

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-terraform/pull/1593

**Comment by P0NDER0SA** [comment]
Merged PR -- now we're adding acouple more PRs today to fix those variables:
cds-snc/notification-terraform#1604
cds-snc/notification-terraform#1602

Also - added blank variables to the 1pass notes for prod and dev so that our CI will pass without asking for missing variables!

**Comment by sastels** [comment]
Terraform side is done, now need to change manifest so that it uses these secrets. That will be done in different cards.

**Comment by sastels** [comment]
Steve will check out the secrets in secrets manager and the associated actions.
