### ISSUE TITLE
Warn when blazer is down

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#300]
# Description

An an ops lead, I want to know when the ECS task Blazer is down so that I can fix it as soon as I know, especially given it is a production support tool. 

## WHY are we building?

Know when Blazer is down.

## WHAT are we building?

A CloudWatch Container Insights warning alert telling us when Blazer is down.

## VALUE created by our solution

Quicker responsiveness to our support tool being down.

# Acceptance Criteria

- [x] Warning alarm for the ECS task being at a count of 0.

# QA Steps

- [x] Alarm is triggered.

**Comment by jimleroyer** [comment]
The TF PR was failing on a missing input variable. I made some changes to fix this.
https://github.com/cds-snc/notification-terraform/pull/1171

**Comment by sastels** [comment]
QA'd on staging by Steve and Jimmy (scaled down the # blazer tasks to zero, verified alarm)
