### ISSUE TITLE
Put latest notification data in QuickSight

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#302]
# Description

As a member of CDS, I need to be able to use QuickSight to all notifications sent one day or more ago to perform analyses.

## WHY are we building?

Need to run analyses on all data from previous day and older

## WHAT are we building?

notifications are moved to the `notification_history` table after the retention period (ie when they are removed from the `notification` table. This is generally after 3 or 7 days. This means that the past week of data in the `notification_history` table (and hence also the QuickSight dataset) is spotty. We should investigate how we can improve this.

## VALUE created by our solution

More accurate reports

# Acceptance Criteria

- [x] QuickSight has a dataset of past notifications that contains all notifications sent more than 1 day ago.

# QA Steps

- [x] verify that the QuickSight dataset contains notifications sent one day ago for a service with a 7 day retention period.
- [ ] switch any old analyses that used the `notification_history` dataset to the new `notifications` dataset and verify the results.

**Comment by sastels** [comment]
verified that we can use a SQL query to create QuickSight datasets rather than the gui dataset builder.
replicated the current QuickSight notification_history dataset qith sQL that unions with the notifications table to get the latest notifications.

**Comment by jimleroyer** [comment]
Steve opened a PR to try out the SQL version of the data import into QuickSight:
https://github.com/cds-snc/notification-terraform/pull/1175/files

**Comment by sastels** [comment]
Will QA and show to folks when it's in production
