### ISSUE TITLE
Null Text Message Sender causing 500 error on dashboard

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#305]
## Describe the bug 

Got a 500 error going to the dashboard of the JLR - Short code test | Test petit code service

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

~SEV-2 : not affecting production but we have to fix this before we can rely on being able to use the short code~

Update: SEV-4: it wasn't the shortcode

## To Reproduce

1. Go to https://notification.canada.ca/services/9b37c2b1-e96a-4fcc-8e76-a095be97845b

Note that doing this 5 times will cause an OpsGenie page

## Expected behavior

no 500s

## Impact

~Can't reliably use short code~ Actually no impact for normal use cases (you have to manually edit the database to cause the bug)

## Additional context

[Slack discussion](https://gcdigital.slack.com/archives/CV38DBNVA/p1709140745735479)

## QA

Unfortunately, we click-ops fixed the issue by setting the "Text message senders" in the admin settings to "CANADA.CA". We have tried and cannot re-break it.

**Comment by sastels** [comment]
IT turned out that the problem was that the Text Message Senders was set to `None`
<img width="1219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e81a09cc96ee31d6864e0eb7ef1deff185af006/image.png" alt="image.png" />

However the code that is crashing is supposed to not crash even if the input is invalid, so we should fix this in any case.

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-utils/pull/279

**Comment by ben851** [comment]
@ben851  to review today

**Comment by ben851** [comment]
Approved and merged!

**Comment by ben851** [comment]
@ben851  to QA

**Comment by sastels** [comment]
Two PRs:
[use new utils in admin](https://github.com/cds-snc/notification-admin/pull/1768)
[use new utils in api](https://github.com/cds-snc/notification-api/pull/2131)

**Comment by ben851** [comment]
Ben to review

**Comment by jimleroyer** [comment]
All PRs are approved. We can move this to QA.
