### ISSUE TITLE
Prod core celery pod crashes most night at 4:01 / 5:01

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#307]
## Describe the bug 

A `core-primary` or `core-scalable` pod in prod is crashing at 4:01 most nights.
The celery pod is receiving a SIGKILL

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV-3 doesn't seem to be impacting sending notifications

This is causing a buildup of jobs that aren't being archived. Additionally, the CSV's are not being deleted, as these are tied to this particular job. This would normally raise the severity, but the S3 bucket has an auto-delete to ensure that we meet our privacy restrictions.

## To Reproduce

1. Create 35k jobs in the jobs table to see if we can get celery to crash

## Expected behavior

Celery should not crash on large queries

## Impact

possibly csv files in S3 (including ones with PII) aren't being cleaned up within retention period. Note however the the csv bucket in S3 has a [one week lifecycle expiry](https://s3.console.aws.amazon.com/s3/management/notification-canada-ca-production-csv-upload/lifecycle/view?region=ca-central-1&bucketType=general&id=expire) so we won't have PII older than one week.

## QA

- [ ] Should see 5:01 am crashes go away

## Additional context

Getting SIGKILLs(possibly because of this task OOMing over a bad job).

[Slack discussion here](https://gcdigital.slack.com/archives/CV38DBNVA/p1709148023544659).

**Comment by sastels** [comment]
Extra logging added [here](https://github.com/cds-snc/notification-api/pull/2125/files)

**Comment by sastels** [comment]
Running in prod:
```
select count(*), min(created_at), max(created_at) from jobs
where archived = false
```
We get

```
count        min                                           max
560,431	2024-02-07 05:03:45 UTC	2024-03-04 13:25:14 UTC
```
Probably we have so many unarchived jobs that it's overwhelming and OOMing the query :/

**Comment by sastels** [comment]
PR to fix
https://github.com/cds-snc/notification-api/pull/2127

**Comment by ben851** [comment]
@ben851 to review

**Comment by sastels** [comment]
merged to staging

**Comment by jimleroyer** [comment]
Let's release to production and see if that issue is getting past. Also, the errors now happen at 5:01 now with the recent time change.

**Comment by sastels** [comment]
ok, it works, but it's slow. We should be able to batch up the database and s3 operations.

WIP PR
https://github.com/cds-snc/notification-api/pull/2139

**Comment by sastels** [comment]
batching up merged. should:
- check Wednesday on staging to see what happened and revert if something went sideways
- check Thursday on prod to see what happened and revert if something went sideways
- on prod (or staging tbh) could get a rough idea of how many we are processing per minute and compare to the non-batched 230 / minute we say before

**Comment by jimleroyer** [comment]
There was no release yesterday unfortunately and hence the old code logic did not stop, hence processing all jobs in production. So this is good news as this issue should not surface for the time being. The bad news is that the new code did not run in production in a faster manner.

**Comment by jimleroyer** [comment]
There was no release yesterday unfortunately and hence the old code logic did not stop, hence processing all jobs in production. So this is good news as this issue should not surface for the time being. The bad news is that the new code did not run in production in a faster manner.

**Comment by jimleroyer** [comment]
One thing to note is that when I check for the number of pending jobs in the database, there were always 20 of them instead of 0.

**Comment by sastels** [comment]
There were  a few errors on staging last night - will investigate if they're related...

**Comment by sastels** [comment]
yeah... the task has been having a `psycopg2.errors.InvalidRowCountInLimitClause` every night exactly since my PR merged into staging :confused: reverted the batching PR out and investigating...

**Comment by sastels** [comment]
This is rather confusing and hard to test.... 
- it involves new relic? 
- Is the error in the query that we lowered the limit from 20000 to 100?
- basically, where do we have a negative limit in a query?

Plan: 
- leave the reverted code in there for a night and see if we no longer get the error in staging
- if we don't, add the PR back in with additional logging to help pinpoint where the problem is in the task

**Comment by sastels** [comment]
ok, there's some bad calculations going on [here](https://github.com/cds-snc/notification-api/blob/main/app/dao/jobs_dao.py#L132), in particular we [have a loop where we could repeatedly add `limit` jobs](https://github.com/cds-snc/notification-api/blob/604ec61e5c835b143d0b6647ca510e02e5ee07a5/app/dao/jobs_dao.py#L138-L152), then down below we [compute a limit with limit - len(jobs)](https://github.com/cds-snc/notification-api/blob/604ec61e5c835b143d0b6647ca510e02e5ee07a5/app/dao/jobs_dao.py#L168) which could be negative if we've added too many jobs above.

I'll make a PR to fix these limits. I believe that the reason this wasn't an issue before was because previous 20K limit was high enough that the jobs array didn't get too big. I would have thought it would on prod though? Possibly we don't have services with 3 day retention on prod sending too many jobs.

**Comment by sastels** [comment]
Fix https://github.com/cds-snc/notification-api/pull/2143

**Comment by sastels** [comment]
Just making a few more changes to the PR

**Comment by sastels** [comment]
Had an issue with code deploying to staging so the fix wasn't in last night. code properly deployed to staging now.

**Comment by P0NDER0SA** [comment]
Did we have any 5:01 crashes?  I'll verify.

**Comment by P0NDER0SA** [comment]
verified the logs in slack and the dashboard in AWS and the last instance of this error was march 21
