### ISSUE TITLE
Investigate  Why New Relic 8.11 Causes Pods To Take Too Long to Start

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#313]
# Description

The API pods are taking longer to start and require more CPU because of the NewRelic new version.  We should determine why that is in order to safely upgrade that dependency. 

## WHY are we building?

Because we want latest version of NewRelic agents.

## WHAT are we building?

Bumping up the NewRelic dependency to version `8.11` or more. Consider jumping to version 9 directly if the minors of version 8 caused this issue. Look at the versions on the [Github repository of python agent](https://github.com/newrelic/newrelic-python-agent).

## VALUE created by our solution

Have latest monitoring agents installed in our Python stack. We might lose backward compatibility at some point by not upgrading.

# Acceptance Criteria

- [x] The NewRelic Python agent is upgraded.
- [x] Root cause of the slow down when upgrading the NewRelic Python agent is found (optional -- if the major upgrade worked, this is the most important)
- [x] ~Support ticket if slow down persists is opened with NewRelic.~

# QA Steps

- [x] Investigation identified root cause and has been reviewed by the team.
- [x] Testing a solution with fixed root cause has been done with one of the component (API).

**Comment by P0NDER0SA** [comment]
Version has been upgraded to 9.12.0.  The Pod started up perfectly fine and NR is recognizing the latest version.  Interesting that it still thinks there are two versions on the pod (min and max versions) -- you can see these in the meta data.  But when you verify the pod and agent in the environment section -- it indeed only has one agent and it is up to date.  Will see if it is lagging behind for some reason and if it updates by Tuesday.

**Comment by P0NDER0SA** [comment]
Verified this mornign that it's just a lag!!! :) everythign worked.

**Comment by P0NDER0SA** [comment]
Will look at upgrading the admin portion and investigate the Lambdas today.

**Comment by P0NDER0SA** [comment]
Lambdas are looking ok -- they dont show up as "agents" per se and seems to work perfectly fine.  Investigating Admin

**Comment by P0NDER0SA** [comment]
finally -- pinning the versions for both admin and api at 9.12.0

**Comment by P0NDER0SA** [comment]
After all of this -- The Pod decided to restart on Prod and Staging (bwecause the health check took too long) -- but the pod is running just fine.  we have to decide where we want to go.  I've:

- Tried the new relic diagnostics tool and it didn't show me any thing
- scoured the internet for others that are experiencing the same thing, haven't seen anything helpful
- built and compared both versions in pods, and compared the logs.  Nothing stands out
- Apparently NewRelic wont offer support in our situation so....

We either have to adjust our K8s settings to allow for the slow startup, or roll-back our version and live with the version banner it shows us. :(

**Comment by P0NDER0SA** [comment]
We might be able to get support from New Relic after Jimmy speaks with them.

**Comment by P0NDER0SA** [comment]
Did a million tests... nothing stood out.  We deployed v8.10.0 to Staging and it's twice as fast starting the pod.  Admin and API are now both in parity for versions.

**Comment by P0NDER0SA** [comment]
Also -- nothing in the release notes indicate any reason why this would happen -- hopefully NR support can help us on this.  One more test to verify if 8.11 is the introduction of the culprit could be helpful!

**Comment by P0NDER0SA** [comment]
We actually tried version 8.11.0 and 8.10.1 today and BOTH failed completely.  Something with those images is breaking our setup.

**Comment by jimleroyer** [comment]
Analyzing the changes brought in 8.11, there is one [for the structlog instrumentation](https://github.com/newrelic/newrelic-python-agent/pull/685/files). There is a list of settings in the tests of this PR that we could play with to see if that changes the startup time:
```
_default_settings = {
    "transaction_tracer.explain_threshold": 0.0,
    "transaction_tracer.transaction_threshold": 0.0,
    "transaction_tracer.stack_trace_threshold": 0.0,
    "debug.log_data_collector_payloads": True,
    "debug.record_transaction_failure": True,
    "application_logging.enabled": True,
    "application_logging.forwarding.enabled": True,
    "application_logging.metrics.enabled": True,
    "application_logging.local_decorating.enabled": True,
    "event_harvest_config.harvest_limits.log_event_data": 100000,
}
```

**Comment by jimleroyer** [comment]
The changes between 8.10.0 and 8.10.1:
https://github.com/newrelic/newrelic-python-agent/compare/v8.10.0...v8.10.1

**Comment by P0NDER0SA** [comment]
Still hopeful we can secure support from NR on this which would be very very helpful.

**Comment by ben851** [comment]
We were unable to receive support from Newrelic.
Next steps should be to try and profile the bootups of the old vs new.

**Comment by jimleroyer** [comment]
I've setup my local environment to attack the profiling angle between NewRelic 8.10 and 8.11.

**Comment by jimleroyer** [comment]
I ran a few tests locally but unfortunately, the bootup time when ran locally is not slowed down with any version of NewRelic.

**Comment by jimleroyer** [comment]
I tested locally to enable NewRelic and I was able to make it work for Celery, but not for the API which I was targeting. 

Also, I enlisted Ben's help to enable NewRelic in our dev environment.

**Comment by P0NDER0SA** [comment]
Jimmy is going to try this today locally -- and then when Dev is rebuilt -- try it there again as well and see if any new info comes out of it.

**Comment by jimleroyer** [comment]
I re-ran locally with New Relic enabled (and reported to work this time with a custom name of `notification-api-local`). There is a noticeable slow down when hitting the API endpoint after bootup with the faulty New Relic version of 8.11, more specifically, a second endpoint hit seems to take several seconds, up to 15 seconds (but first seems to pass fine). 

The API with the New Relic version 8.10 has very minimal delay of 1 second with several consecutives hit on the endpoint straight after boot up.

### New Relic 8.10 graph chart of the boot up chart
<img width="408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEZSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f4467e4c26a264c32cd43e9852660fd20eb81b2/image.png" alt="image.png" />

### New Relic 8.11 graph chart of the boot up chart
<img width="408" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32ccf58a41b83672a8091127648abf1a569aa7ac/image.png" alt="image.png" />

I will keep on exploring the profiling options to see if I can put the finger on where the API might waste on that sleep time with New Relic v8.11.

**Comment by jimleroyer** [comment]
Jimmy screwed his docker environment. He spent some time on it and reinstalled with colima instead of docker desktop.

**Comment by jimleroyer** [comment]
Reworked code, setup NR activity, ran a few tests and produced graphs. Will refine today to pinpoint issue.

**Comment by jimleroyer** [comment]
I regenerated the graphs and I need to investigate these.

**Comment by P0NDER0SA** [comment]
we'll try and pair up on  this today

**Comment by jimleroyer** [comment]
Ran a few tests with different settings. I was seemingly able to get past the slowdown of New Relic 8.11 as I was disabling options. I need to run more tests though because I was not able to put back the slow down resetting the options back to original values so there might have been mistakes done. I was not able to put exact finger on what worked and didn't.

**Comment by jimleroyer** [comment]
Identified the breaking points yesterday where code spends most time. Tried new and better tools for debugging the profiling (kcachegrind) and wrote a script to compute time differences between two profiling snapshots.

**Comment by ben851** [comment]
Jimmy tried the debugging route bu this doesn't seem to work with gunicorn. The issue can't be replicated wtihout gunicorn.

**Comment by jimleroyer** [comment]
After enabling debugging locally successfully (with gunicorn), I think these lines are the exact cause of the slowdown in the diff between 8.10.0 and 8.10.1:
https://github.com/newrelic/newrelic-python-agent/compare/v8.10.0...v8.10.1#diff-936ae7b541681b74a46abebe048a9048771093ce5e18e18aed9d355301cc7bd5R78-R82

I can check a) if there is a way to avoid this execution or to make it fast and b) how to increase the gunicorn worker timeout that triggers a restart (if that's possible -- but it should be) and which makes the setup takes a longer time to bootup.

**Comment by ben851** [comment]
Jimmy will fiddle with delays this morning

**Comment by jimleroyer** [comment]
I brought up a few tweaks to increase the gunicorn timeout and made new startup API k8s probe in addition to change the existing ones to be nearer to latest initialization time.  I also disabled the package detection feature of New Relic in staging.

Next for me is to potentially lower down the gunicorn timeout (as I increased it too much), put some logs to track the restarts when workers are caught in a timeout loop, make a query to graph this and disable package reporting in all environments.

**Comment by jimleroyer** [comment]
PR for [Added total running time to gunicorn shutdown hooks](https://github.com/cds-snc/notification-api/pull/2365)

**Comment by sastels** [comment]
Will rework card slightly to account for different repos

**Comment by jimleroyer** [comment]
Before closing this issue, we want to get back on the investigation that took place for this issue.

## Root cause

a) New Relic implemented new logic to grab more package metadata starting on version 8.10.1. This is used for vulnerability detection by New Relic and alert users when a dependency is affected. That new logic involves looping through the list of dependencies and potentially reading file on the filesystem. 
b) This New Relic new logic can be resource intensive in the context of the application start up and delay it by a matter of 20-60 seconds, leading to our Kubernetes ready and live probes to fail and reboot the application after a given timeout.
c) There is also a gunicorn worker timeout that is configured at 20 seconds by default. 

## New Relic Python Agent Fixed related to the performance degradation

New Relic team made these changes to the Python agent to counteract this loss of performance:
[Version 9.1.1](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90101/)

> Add caching to get_package_version to address performance issues

[Version 9.1.2](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90102)

> Fix package version performance regression Addressed issue that was introduced in 8.10.1 where there is increased CPU usage and time on startup and when using certain libraries at runtime.

[Version 9.2.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-90200/)

> Add new configuration option package_reporting.enabled. This option allows users to disable capturing package and version information at agent startup. On some applications with a high number of packages some users were seeing a spike in CPU usage. Disabling this setting provides a workaround for that issue.

## Conclusion

The performance improvements make the New Relic initialization time similar to the ones pre 8.10.1, but not exactly. Disabling the feature via the `package_reporting.enabled` option would make it faster though. As we do not need vulnerability detection by New Relic as this is covered by other tooling we use, we can disable that feature altogether and make the initialization quicker.

**Comment by jimleroyer** [comment]
Jimmy to submit a few useful artifacts in the attic which helped to debug this issue. Also to add the final profile graphic (light edition) under the explanation.

**Comment by sastels** [comment]
LGTM. Agree that we can disable since packaged vulnerability detection is already covered.

**Comment by jimleroyer** [comment]
Got this PR in the attic to submit the time compare profile files:
https://github.com/cds-snc/notification-attic/pull/70

**Comment by ben851** [comment]
Read the final report - makes sense and looks good!
