### ISSUE TITLE
Fix AWS Lambda on Dev

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#315]
# Description

As a developer of Notify, I would like the dev environment to be the same as the staging and production environments. Currently, we must use the K8s api instead of the lambda API because the lambda API throws an error.

## WHY are we building?

Aligns dev with our other environments.
Increases reliability of development work.
Aligns with BCP requirements for setting up a new environment

## WHAT are we building?

Fix the AWS lambda function in dev

## VALUE created by our solution

Better integration with other environments
Increases our ability to recover in BCP scenarios

# Acceptance Criteria

- [x] api lambda working in dev (accepts notifications and they are eventually sent)

# QA Steps

- [x] smoke test api-lambda.dev (should be the same as api.dev)

**Comment by ben851** [comment]
The issue was that the ENVIRONMENT_VARIABLES set in aws parameter store was not being managed by Terraform. Apparently this is required for the lambda function to work. I've created a new version of this file that is managed by terraform and created during bootstrap. This is an ugly fix but will suffice until we address a better way to manage these values in AWS to begin with. (Separate card)

**Comment by ben851** [comment]
Will point dev to the lambda function today to verify it works.

**Comment by ben851** [comment]
Lambda function is throwing an error, investigating.

**Comment by ben851** [comment]
There was a misconfig in the sql alchemy postgres URIs for dev. Fixed, lambda is working. Dev is working w/ lambda

**Comment by sastels** [comment]
smoke test throwing error
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::800095993820:user/notification-dev-tf-user is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::notification-canada-ca-dev-csv-upload/service-f316aa6b-38dd-4d9e-83f8-b6ee3e1d428f-notify/ee076e37-79f6-4171-85c7-2d14662c12d5.csv" because no identity-based policy allows the s3:PutObject action
```

but I think it's because there's a missing database user maybe?
