### ISSUE TITLE
Subnet IDs are not working on the VPN module in Terraform when creating a new environment

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#318]
## Describe the bug 

When apply terraform/aws/common in a new environment, the VPN module crashes, complaining about an invalid string type on subnet_ids. This works fine on existing environments

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3

## To Reproduce

Terragrunt apply in common folder against scratch account

## Expected behavior

Terragrunt should apply properly

## Impact

The system is not in a ready state for disaster recovery
## Additional context

Discovered as part of BCP

## QA
- [x] Make sure TF still applies in production
- [x] Verify connectivity to staging K8s and VPN
- [x] Verify connectivity to production K8s and VPN

**Comment by ben851** [comment]
It looks as though Terraform/Terragrunt has problems computing potential values if they don't exist for subnet IDs. 

I have moved the vpn module to the eks folder so that the subnet IDs already exist. 

While doing this, I broke dev VPN when trying to migrate state. [I found a solution here](https://www.maxivanov.io/how-to-move-resources-and-modules-in-terragrunt/#:~:text=What%20happens%20if%20you%20just,in%20the%20managed%20infrastructure%20really.) that I need to try out.

**Comment by P0NDER0SA** [comment]
Need to write up a procedural on this.  still working on it.

**Comment by ben851** [comment]
I was QA'ing my own work in dev to make sure that it worked, and it did not. Will have to investigate more.

**Comment by ben851** [comment]
Created a new PR with the final migration steps.

**Comment by ben851** [comment]
Merged - state migrated in both staging and production

**Comment by P0NDER0SA** [comment]
QA'ed this and it works.  connectivity with and without prod vpn connection works as expected
