### ISSUE TITLE
Tracing / correlate requests through the Notify components (AWS X-Ray)

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning-core#319]
# Description

As an ops lead,
I want to link all requests going through the Notify stack that was triggered by the same user / same origin IP,
So that I can quickly analyze their behavior and actions on our stack.

## WHY are we building?

Better tracing support through our stack.

## WHAT are we building?

Implementing correlation / trace IDs through the various Notify components. Potentially [using aws x-ray](https://aws.amazon.com/xray/). This should activate X-RAY through the components but not have these wired altogether by passing the request ID necessarily.

## VALUE created by our solution

Quicker support and incident response. Better routing / behavior analysis of the requests made against Notify.

# Acceptance Criteria** (Definition of done) 

- [x] Filter correlated logs in various Notify components coming from the same request.

# QA Steps

- [x] API has X-RAY enabled and working.
- [x] DD-API has X-RAY enabled and working.
- [x] Admin has X-RAY enabled and working.

# Additional info

* [AWS X-Ray](https://aws.amazon.com/xray/)
* Notify used [zipkin](https://zipkin.io/) in the past and it has traces of it in the code. Look into the [utils component](https://github.com/cds-snc/notification-utils/blob/623d109f9145996d7f32eacdada190384d8a5ffa/notifications_utils/request_helper.py#L16) among others. That might facilitate the implementation as the feature is present for another product. Ideally we can just tweak and enable it.

## Celery integration with X-Ray:

The one area I am uncertain with xray is how we will plug this with Celery. This and that seems interesting.

* [celery-aws-xray-sdk-extension](https://pypi.org/project/celery-aws-xray-sdk-extension/)
* [Celery support Github Issue Thread](https://github.com/aws/aws-xray-sdk-python/issues/92)

**Comment by P0NDER0SA** [comment]
https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python-middleware.html

**Comment by P0NDER0SA** [comment]
https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-python.html

**Comment by P0NDER0SA** [comment]
API Code to include middleware/recorder!
https://github.com/cds-snc/notification-api/pull/2231
EKS IAM for K8s/Terraform
https://github.com/cds-snc/notification-terraform/pull/1471

**Comment by sastels** [comment]
Isn't finding new traces for api lambda :/ Work ongoing...

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-terraform/pull/1475

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-manifests/pull/2799

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-manifests/pull/2805

**Comment by P0NDER0SA** [comment]
Terraform for lambdas are pushed and it's showing metrics!  Daemonset is deployed for K8s -- but somethi9ng still not working there

**Comment by P0NDER0SA** [comment]
K8s API is now working!  needed to adjust the IAM.  Working on getting the document download api to start pushing metrics successfully now as well.

**Comment by P0NDER0SA** [comment]
Admin, API and Doc Download are all running in K8s/Lambda Xray.  More tasking could be created to configure/manage the actual tracing in the future.

**Comment by P0NDER0SA** [comment]
Flurry of PRs for XRay -- to be merged in the same order they're listed :slightly_smiling_face: I'll be watching each one closely to ensure everything is healthy before moving to the next.
Adding Env Vars to Remaining deployments in Manifests:
https://github.com/cds-snc/notification-manifests/pull/2833
Removing useless code from Doc Download API:
https://github.com/cds-snc/notification-document-download-api/pull/180
Adding Xray Middleware to Admin! :
https://github.com/cds-snc/notification-admin/pull/1919

**Comment by P0NDER0SA** [comment]
Small bug introduced with the implementation in Admin.  Rolled it back from staging -- will investigate before moving on to Celery.

**Comment by P0NDER0SA** [comment]
to Merge and Test!
https://github.com/cds-snc/notification-admin/pull/1923

**Comment by jimleroyer** [comment]
Paired with Steve to setup the admin locally yesterday. Fixed the setup and some other misc issues. We got a PR to test to see if admin will work today.

**Comment by jimleroyer** [comment]
Checked the request IDs in production environment and everything is in place. The QA steps won't apply per the updated scope of this ticket though as we cannot trace IDs through multiple components yet (except for the API gateway). Overall, X-Ray does work as expected so far, present and functional in API, admin and DD-API.
