### ISSUE TITLE
Complete quicksight vs superset eval

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#321]
# Description

As a future BI tool user, 
I want to provide feedback on a superset vs QuickSight product evaluation,
So that I have the best option for me picked up in the future. 

## WHY are we building?

Platform wants our recommendations

## WHAT are we building?

Complete the [existing BI tool document](https://docs.google.com/document/d/1HKPx-ZDjQ69JoPRiC_VQx9-aM2jbjv1RHsk9WLSmMJs) with missing evaluation criteria and move over Pat's evaluation in it. 

Move some of our existing QuickSight analysis into SuperSet and reference these comparisons into the eval documents.

## VALUE created by our solution

Platform is able to pick a tool with maximum awareness.

# Acceptance Criteria

- [ ] Steve and Jimmy have provided their advice
- [ ] The existing BI eval document has been filled 
- [ ] Core team reviewed the revised eval document
- [ ] We have 1 to 1 analysis between superset and quicksight

**Comment by sastels** [comment]
Comparison ideas:


Affects on analyses / dashboards:
- Adding new field
- Changing dataset fields
- Changing dataset name


Adding new calculated fields

Reproducing Notify dashboards:
- QuickSight Scavenger Hunt
- Blazer send rate dashboard

**Comment by sastels** [comment]
**QuickSight Scavenger Hunt in Quickight vs SuperSet**

- Easy to reconstruct 3 analyses
- Renaming service_id column in table might need to be done globally in superset by editing the dataset?
    - https://stackoverflow.com/questions/62280475/how-do-i-change-the-column-names-of-a-table-in-apache-superset

**Comment by sastels** [comment]
SMS Send rate

```
with data_nh as (
    select
        id,
        sent_at, sent_at::date as day, round_minutes(sent_at, 1) as sent_minute,
        billable_units
    from notification_history
    where sent_at is not null and notification_type = 'sms'
),
data_n as (
    select
        id,
        sent_at, sent_at::date as day, round_minutes(sent_at, 1) as sent_minute,
        billable_units
    from notifications
    where sent_at is not null
       and notification_type = 'sms'
),
data as (
    select * from data_nh
    union
    select * from data_n
),
rollup as (
    select day, sent_minute, sum(billable_units) as fragments_per_minute
    from data
    group by day, sent_minute
)
select day, max(fragments_per_minute) as max_fragments_per_minute from rollup
group by day
order by day
```

**Comment by ben851** [comment]
So many meetings, and reviews!

**Comment by jimleroyer** [comment]
I reset the previous document by Bryan to remove the additions we added, and started a new one for us, which is more of an impression document rather than criteria. This will be faster that way.

**Comment by jimleroyer** [comment]
Started document is over there:
https://docs.google.com/document/d/1A4G5GUXYFgXZS4JztmxON5FVgyjKyhaoN89zzMNC46s/edit

Will fill in specifics on products tomorrow.

**Comment by jimleroyer** [comment]
I completed the product sections yesterday. I would like to polish it more but I think a review by Steve and Pat would be  at this time.

**Comment by ben851** [comment]
@ben851 to review the doc
