### ISSUE TITLE
Keep SMS usage data longer

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#325]
# Description

As a Notify team member, I need to see all the SMS costing data.

## WHY are we building?

We would like to know what services have been spending on SMS in the long term. Currently we keep a one week snapshot of the data.

## WHAT are we building?

We are modifying the current system so that we do not delete the SMS usage data after a week. Note that currently the data contains destination phone numbers. We will need to remove those before we can keep the data long term.

## VALUE created by our solution

Better estimate on service costs.

# Acceptance Criteria

- [x] Sanitize the destination phone number in the sms usage report and save into a new bucket.
- [x] The SMS usage report is still deleted from S3 after a period of 3 days.
- [x] The sanitized SMS usage report in a new S3 bucket is never deleted.
- [x] QuickSight `SmsUsage` and `Notifications with SMS pricing` datasets have all the usage data collected so far, using the sanitized S3 report instead of the one with sensitive data, but still including the reference ID and the cost per SMS fragment. 

# QA Steps

- [x] Verify that the destination phone number does not appear in the sanitized S3 SMS usage report files.
- [x] Verify that the destination phone number does not appear in QuickSight datasets.
- [x] Create analyses with the `Notifications with SMS pricing` dataset and verify that the amount of data grows continuously, past the 3 days of data retention period.
- [x] Find a service with a fixed us-west number and check that their notifications are in the `Notifications with SMS pricing` dataset.
- [ ] Verify that there are no duplicate message ids in the dataset

**Comment by sastels** [comment]
Started with a script that will sanitize the usage logs and move to a different bucket that has no retention policy.
https://github.com/cds-snc/notification-terraform/pull/1256

**Comment by sastels** [comment]
pr merged, ran the script, new sanitized files in new bucket :tada:
Have to see what happened overnight in QuickSight...

**Comment by sastels** [comment]
The manifest file, which I smartly moved to the new bucket so it wouldn't expire, still points to the old bucket. Will fix after more caffeine...

**Comment by sastels** [comment]
Fix the manifest file
https://github.com/cds-snc/notification-terraform/pull/1276

**Comment by sastels** [comment]
ok, remaining is to have a GitHub actio run this script every day

**Comment by P0NDER0SA** [comment]
This one is approved as well! moving to QA

**Comment by sastels** [comment]
PR for github action https://github.com/cds-snc/notification-terraform/pull/1294

**Comment by P0NDER0SA** [comment]
Jimmy will QA

**Comment by sastels** [comment]
PR approved, will be merged today

**Comment by sastels** [comment]
merged in, will release today and then we can QA

**Comment by ben851** [comment]
Needs to be released to prod and QA'ed

**Comment by sastels** [comment]
- everything automated
- data in QuickSight from Apr 14 - May 4
<img width="795" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenU2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7f26f89b8a8c789b95e4708382f51bb49462f92/image.png" alt="image.png" />

**Comment by sastels** [comment]
One thing we haven't done yet is use the us-west-2 data. We should see if we can get the initial SMSUsage dataset to use that bucket along with the ca-central-1 bucket. ie can you create a dataset from 2 buckets? :thinking:

**Comment by sastels** [comment]
merged and ready for release.

Aft this has been released we can manually refresh the datasets to check if the us-west-2 data has been added.

**Comment by ben851** [comment]
We haven't done a Terraform release recently. Need to get this in there.

**Comment by sastels** [comment]
I think all is in prod now :tada:

Ready for QA

**Comment by sastels** [comment]
Brought back from Done - SMSUsage dataset has duplicate rows. We need to dedup them (ie one line per message id). Started a PR to do this as part of removing the PII
https://github.com/cds-snc/notification-terraform/pull/1335

**Comment by P0NDER0SA** [comment]
will be merged soon then we can QA it.

**Comment by sastels** [comment]
Update the prod sanitizer script:
https://github.com/cds-snc/notification-terraform/pull/1345

**Comment by sastels** [comment]
all merged and running

**Comment by ben851** [comment]
@sastels to run the de-duplicate data in prod, and will be qa'ed

**Comment by sastels** [comment]
- verified in production Quicksight that we have duplicate rows in the SMSUsage dataset (ie for same message id)
- manually ran the sanitize / dedup script on the old production sms usage s3 buckets (ie to depup the old stuff)
- manually reran the SMSUsage dataset refresh
- verified that we no longer have duplicate rows in the SMSUsage dataset

remaining: refresh the "Notifications with SMS pricing" dataset. This is a 45 minute join of the full notifications dataset with the SMSUsage dataset - I decided to leave this to the nightly refresh.

**Comment by sastels** [comment]
- Notifications with SMS pricing refreshed in prod overnight
- verified that there are no duplicate notification_ids in the dataset
- read for someone else to QA

**Comment by ben851** [comment]
@Jimmy has assigned it to himself to QA

**Comment by jimleroyer** [comment]
I downloaded the sanitized report for June 9th and there were no duplicate message IDs sitting in the file, using a quick duplicate finder script. So this is all ✅.
