### ISSUE TITLE
Move Hasura To Helmfile

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#328]
# Description

As a developer of notify, I would like all of our kubernetes deployments to be managed by Helmfile so that all of our kubernetes code is in one location.

## WHY are we building?

- Provides the ability to deploy dynamic environments
- Provides the ability to run "diff" commands against environments
- Reduces the amount of code that Notify has to manage
- Keeps code DRY

## WHAT are we building?

- [ ] Install Hasura using the [official helm chart](https://hasura.io/docs/latest/deployment/deployment-guides/kubernetes-helm/)
- [ ] Make sure any secrets required by hasura are stored in terraform 
- [ ] Make sure that any secrets required by hasura are accessed at runtime using a kubernetes secret

## VALUE created by our solution

- Increased reliability via reduced chance of accidental changes during releases
- Increased velocity due to reduction in maintenance

# Acceptance Criteria

- [ ] Hasura is deployed and managed with helmfile
- [ ] All secrets required by hasura are stored in terraform and accessed using a kubernetes secret
- [ ] A github workflow managing hasura has been created
- [ ] Hasura is accessible behind VPN

# QA Steps

- [ ] Hasura deploys to an existing environment
- [ ] Hasure deploys to a new environment
- [ ] Hasura is accessible behind VPN

**Comment by jimleroyer** [comment]
This will not be necessary as we are moving away from Hasura.
