### ISSUE TITLE
Move Kube State Metrics to Helmfile

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#335]
# Description

As a developer of notify, I would like all of our kubernetes deployments to be managed by Helmfile so that all of our kubernetes code is in one location.

## WHY are we building?

- Provides the ability to deploy dynamic environments
- Provides the ability to run "diff" commands against environments
- Reduces the amount of code that Notify has to manage
- Keeps code DRY

## WHAT are we building?

- [ ] Install Kube State Metrics using the [official helm chart](https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics)
- [ ] Make sure any secrets required by Kube State Metrics are stored in terraform 
- [ ] Make sure that any secrets required by Kube State Metrics are accessed at runtime using a kubernetes secret

## VALUE created by our solution

- Increased reliability via reduced chance of accidental changes during releases
- Increased velocity due to reduction in maintenance

# Acceptance Criteria

- [ ] the Kube State Metrics is deployed and managed with helmfile
- [ ] All secrets required by the Kube State Metrics  are stored in terraform and accessed using a kubernetes secret
- [ ] A github workflow managing the Kube State Metrics has been created
- [ ] Kube State Metrics is still reporting

# QA Steps

- [ ] the Kube State Metrics deploys to an existing environment
- [ ] the Kube State Metrics deploys to a new environment
- [ ] Kube State Metrics still works

**Comment by jimleroyer** [comment]
Moving the task back to priortized, [PR still open for now](https://github.com/cds-snc/notification-manifests/pull/2545).

**Comment by sastels** [comment]
Pond to QA

**Comment by P0NDER0SA** [comment]
QA'ed!  working perfectly in production.  Moving to done.
