### ISSUE TITLE
Move K8s Event Logger to Helmfile

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#336]
# Description

As a developer of notify, I would like all of our kubernetes deployments to be managed by Helmfile so that all of our kubernetes code is in one location.

## WHY are we building?

- Provides the ability to deploy dynamic environments
- Provides the ability to run "diff" commands against environments
- Reduces the amount of code that Notify has to manage
- Keeps code DRY

## WHAT are we building?

- [x] Install Kubernetes Event Logger using the [official helm chart](https://artifacthub.io/packages/helm/deliveryhero/k8s-event-logger)
- [x] Make sure any secrets required by Kubernetes Event Loggers are stored in terraform 
- [x] Make sure that any secrets required by Kubernetes Event Logger are accessed at runtime using a kubernetes secret

## VALUE created by our solution

- Increased reliability via reduced chance of accidental changes during releases
- Increased velocity due to reduction in maintenance

# Acceptance Criteria

- [x] the Kubernetes Event Logger is deployed and managed with helmfile
- [x] All secrets required by the Kubernetes Event Logger  are stored in terraform and accessed using a kubernetes secret
- [x] A github workflow managing the Kubernetes Event Logger has been created
- [x] Kubernetes Event Logger is still reporting

# QA Steps

- [x] the Kubernetes Event Logger deploys to an existing environment
- [x] the Kubernetes Event Logger deploys to a new environment
- [x] Kubernetes Event Logger still works

**Comment by ben851** [comment]
Merged to staging

**Comment by ben851** [comment]
Will release to prod today. Also going to create a quick dashboard

**Comment by sastels** [comment]
logs coming into dev
