### ISSUE TITLE
Move Notify Documentation to Helmfile

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#339]
# Description

As a developer of notify, I would like all of our kubernetes deployments to be managed by Helmfile so that all of our kubernetes code is in one location.

## WHY are we building?

- Provides the ability to deploy dynamic environments
- Provides the ability to run "diff" commands against environments
- Reduces the amount of code that Notify has to manage
- Keeps code DRY

## WHAT are we building?

- [ ] Create a notify documentation helm chart
- [ ] Make sure any secrets required by notify documentation are stored in terraform 
- [ ] Make sure that any secrets required by notify documentation are accessed at runtime using a kubernetes secret

## VALUE created by our solution

- Increased reliability via reduced chance of accidental changes during releases
- Increased velocity due to reduction in maintenance

# Acceptance Criteria

- [ ] notify documentation is deployed and managed with helmfile
- [ ] All secrets required by notify documentation are stored in terraform and accessed using a kubernetes secret
- [ ] A github workflow managing notify documentation has been created
- [ ] notify documentation is still reporting

# QA Steps

- [ ] notify documentation deploys to an existing environment
- [ ] notify documentation deploys to a new environment
- [ ] notify documentation logs still in cloudwatch with no increased cost

**Comment by P0NDER0SA** [comment]
rebuilt this one using helm create and migrated the required helm values as variables.  It deploys and runs -- needs verification

**Comment by jimleroyer** [comment]
This might be blocked by the broken helm diff. @ben851 is on it this morning.

**Comment by sastels** [comment]
All part of our monster helm PR
https://github.com/cds-snc/notification-manifests/pull/2541
