### ISSUE TITLE
Dedicated long codes not always used

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#348]
## Describe the bug 

Dedicated long codes not always used.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor - notifications still sent (using long code pool) but with the wrong numbers

## To Reproduce

1. Set up a service with a dedicated number
2. upload a csv sending an sms or two to yourself
3. see that the number that is used is not the dedicated number

## Expected behavior

dedicated number always used.

## Impact

Services with dedicated numbers might not have these numbers used.

## Additional context

https://cds-snc.freshdesk.com/a/tickets/17255

**Comment by sastels** [comment]
WIP fix
https://github.com/cds-snc/notification-api/pull/2163

**Comment by P0NDER0SA** [comment]
approved and ready to merge!

**Comment by sastels** [comment]
merged Thursday, will release today

**Comment by sastels** [comment]
released, asked the user that reported the problem to test again.

**Comment by sastels** [comment]
user tested and working now

**Comment by ben851** [comment]
Working - QA'ed by the customer!
