### ISSUE TITLE
Single Source Of Truth For Secrets

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#35]
## Description

As a developer/operator of Notify, I want all secrets for the solution to be stored in a single location, consistently across environments. 

#### WHY
Currently secret manageemnt require a lot of manual work and click ops. These secrets are stored in a bunch of different places, making it difficult to quickly and easily know where to find and where to change different secrets.

#### WHAT
We can go one of two routes, either using AWS Secrets Manager (or Parameter Store), or leveraging the SaaS version of Hashicorp Vault. Both solutions will require R&D to ensure that all components can leverage these secrets. Vault should be preferred since it can do just in time secrets, eliminating the need to to manual secret rollovers in the future, however vault may not integrate as well with first party applications.

#### VALUE
By having a single source of truth for secrets, we will be able to react to secret issues much quicker. In the future when doing manual rollovers, we will be able to greatly speed up the process and be sure that when we change a secret in one location, that it will be propagated to all required services. 

## Acceptance Criteria

- [ ] All secrets are stored in a single location
- [ ] Passwords are no longer tied to to the github repositories as encrypted zip files
- [ ] Last pass password files are no longer required

## Related Research 
- https://developer.hashicorp.com/vault/tutorials/vault-agent/agent-quick-start
- https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar
- https://docs.aws.amazon.com/systems-manager/latest/userguide/integrating_csi_driver.html
- https://medium.com/awesome-cloud/aws-difference-between-secrets-manager-and-parameter-store-systems-manager-f02686604eae

## QA Steps
- [ ] Manual secret rollovers are "one stop shops"
- [ ] New environments can be spun up from secret templates

**Comment by ben851** [comment]
https://developer.1password.com/docs/ci-cd/github-actions/

**Comment by jimleroyer** [comment]
This was closed in favor of #61, bringing details of this one into the latter.
