### ISSUE TITLE
Automation for Destruction of Dev Environment every week

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#352]
# Description

As a developer/operator of GC Notify I would like a reliable way to destroy the necessary artifacts in an AWS account (enough and not too much), so that I can wipe out an environment and rebuild on top of it.

## WHY are we building?

This will ensure that Dev is not in a constant state of mess, and it will provide QA to our Terraform release where we will be able to quickly identify if there are breaking changes to Terraform.

It has been tricky in the past to properly destroy environments, so we need to spend time to refine this destruction processs.

## WHAT are we building?

Create a github action that destroys dev every Friday night

## VALUE created by our solution

- Increased BCP readiness
- Increased development velocity
- Potentially reduced cost in the dev environment (the system can be destroyed on weekends)

# Acceptance Criteria

- [ ] The dev environment is automatically destroyed weekly

# QA Steps

- [x] Run the destruction script by someone other than the person working on this ticket.

**Comment by P0NDER0SA** [comment]
PR: https://github.com/cds-snc/notification-terraform/pull/1333

**Comment by sastels** [comment]
destroy script created and probably works!

**Comment by sastels** [comment]
We will break this card into 2

**Comment by P0NDER0SA** [comment]
This is ready to continue working on it, but with Dev working right now we do not want to spend a full day destroying and rebuilding dev.

**Comment by sastels** [comment]
Will circle back with Ben when he's back to see if there are updates

**Comment by ben851** [comment]
Running into some problems cleaning up some stuff that TF doesn't seem to want to clean up. 
- Quicksight VPC
- EKS Spot Nodes
- EKS created ELBs

**Comment by ben851** [comment]
Got the cleanup jobs working. Working on the creation job!

**Comment by ben851** [comment]
Creation job working up to TF infrastructure deploy. Starting to automate the VPN connection, and then will deploy the app.

**Comment by ben851** [comment]
AWS has a dumb thing where it creates the EKS cluster IAM for only the principle that runs TF. This causes a problem when people try and connect to an EKS cluster that was created in github actions. I had figured out a fix on Friday but it seems to have regressed over the weekend :(

I'm going to quickly peek at this today, and if it's not a quick fix, I'm putting this back into prioritized for now.

**Comment by ben851** [comment]
Opened AWS case:
https://support.console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=172537682800180&language=en

**Comment by ben851** [comment]
Received response from AWS, will need to recreate the bad dev eks to provide them with more info

**Comment by ben851** [comment]
I figured it out!
1. There is a condition with EKS creation where it only creates aws-auth entries for whatever sts identity is used when creating the cluster
2. We have an aws-auth configmap in kustomize that is incorrect
3. This meant that every time I tried to fix it via terraform, it was immediately getting overwritten by kustomize

I'm removing the kustomize aws-auth for dev, and implementing the fix in terraform since this is related to environment creation, not application deployment.

**Comment by ben851** [comment]
Everything is running. Need to do a final destroy/recreate to verify this works before closing. Moving to QA

**Comment by sastels** [comment]
Will QA soon

**Comment by ben851** [comment]
I deleted/recreated dev yesterday - some of the issues were due to env variable management changes, which I have resolved for now but we will need to figure out how to get versioning going in 1Password.

Since @P0NDER0SA is working on environment variable management in dev, I'm switching to sandbox to create a new environment there and see if I can resolve the deletion issues.

**Comment by ben851** [comment]
Working on Sandbox creation -had an issue with ECR not building on my computer but that's resolved. Applying the last few steps, and then will work on aws nuke script.

**Comment by sastels** [comment]
Steve will add some manual Pinpoint steps to https://docs.google.com/document/d/1hEKUl7uH0Ksr_1Qk3tv8O43gNAe14QQVREevrQLodS4/edit#heading=h.2d9mht7003ms

**Comment by jimleroyer** [comment]
Ben working on AWS nuke. We got a script that destroys most except 10%. He needs to go over this list to see what we can do about it.

**Comment by ben851** [comment]
Creating a new aws nuke config with latest version of AWS Nuke.  The SRE aws nuke config has a bunch of bad filters and errors that I've cleaned up. I will be making a PR to their repo for this. I'm currently recreating the environment to test.

**Comment by ben851** [comment]
PR w/ updated delete scripts.

https://github.com/cds-snc/notification-terraform/pull/1567

**Comment by P0NDER0SA** [comment]
PR for the terraform is up and posted.  Waiting to convert it to 'non-draft'.   Should be ready for prime time in the near future.

PR Review Bot has been included.

**Comment by ben851** [comment]
Merged to main, ready to try running against dev. Need to confirm w/ team that I'm good to go.

**Comment by ben851** [comment]
Running delete
https://github.com/cds-snc/notification-terraform/actions/runs/11236834635/job/31237839504

A few minor issues to iron out in a PR relating to Github Actions.

**Comment by ben851** [comment]
They large sized S3 bucket for the cloud based sensor is causing timeouts. I'm manually deleting that to try it again, and then if that works, I'll add an extra step in the TF side to kill that s3 bucket.

**Comment by ben851** [comment]
I had to write a python script to delete the S3 buckets, ran that yesterday and it worked, recreating the dev environment again right now and will run a final try.

**Comment by ben851** [comment]
Pond ran the delete script yesterday and it worked. The create script failed due to an unrelated error, that needs to be fixed before we continue QA'ing that part.

**Comment by ben851** [comment]
Ran into some more unrelated issues yesterday. Running create script again. If it passes, QA should be reset and done again.

**Comment by sastels** [comment]
Everything worked (ie terraform applies) but the domain won't validate? should take minutes at most. Ticket in with AWS to figure it out.

**Comment by sastels** [comment]
AWS got back to us - api has changes and need to fix something, will do it in another card.
