### ISSUE TITLE
Alert warning when an external service (API callback) gets past a predefined threshold

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#356]
# Description

As an ops lead,
I need to know when an external service request is timing out (i.e. via API callback),
So that I can take appropriate actions to prevent a slow down of the system
(such as removing the culprit callback).

## WHY are we building?

The API callbacks has the chance of slowing down our overall notifications processing pipelines for Celery tasks that are neighbors to the one for doing the call backs (such as database saving, vital to the health of our overall pipeline). Hence we need to identify when such as scenario occurs so that we can take appropriate actions such as removing the configured callback that might slow down the pipeline).

## WHAT are we building?

An warning alarm that reports back to the #notification-ops Slack channel.

## VALUE created by our solution

Better awareness of potential faulty API callbacks

# Acceptance Criteria

- [x] Warning alarms is configured and reporting back into the #notification-ops Slack channel.

# QA Steps

- [x] Review the alarm by a team member.

**Comment by jimleroyer** [comment]
The NewRelic alarm [is over there](https://one.newrelic.com/alerts-ai/condition-builder/entity/MjY5MTk3NHxBSU9QU3xDT05ESVRJT058NDE1MTQwMTU?account=2691974&duration=259200000&state=c3492efc-5a7e-1f4a-9150-7399c671d2b7) 👈

**Comment by sastels** [comment]
We haven't had a warning triggered yet (ie after lowering the threshold to test) :/

**Comment by jimleroyer** [comment]
The alarm was seen after threshold was lowered. I also modified the query so that the alarm actually reports the URL that is timing out. After change, the alarm was tested with the low threshold. And we tested again successfully. I changed to a higher threshold and we haven't seen the alarm again (expectedly).

**Comment by sastels** [comment]
:+1: looks great!

**Comment by P0NDER0SA** [comment]
refviewed and QA'ed!! :)
