### ISSUE TITLE
Automation for Recreation of the Dev Environment every week

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#357]
# Description

As a developer/operator of GC Notify I would like our dev environment to be refreshed every week so that we always have a new environment on Monday, and we can test our environment recovery scenarios.

## WHY are we building?

This will ensure that Dev is not in a constant state of mess, and it will provide QA to our Terraform release where we will be able to quickly identify if there are breaking changes to Terraform.

## WHAT are we building?

* Enable schedules on the delete/create workflows

## VALUE created by our solution

- Increased BCP readiness
- Increased development velocity
- Potentially reduced cost in the dev environment (the system can be destroyed on weekends)

# Acceptance Criteria

- [ ] The dev environment is automatically created weekly 
- [ ] The database restore is automated 
- [ ] The newly created dev environment "just works" (exclude QuickSight)

# QA Steps

- [ ] The new environment functionality is tested by another developer who didn't work on this.
- [ ] The UI tests are ran against the new environment.
- [ ] The smoke tests are ran against the new environment.
- [ ] The performance tests are ran against the new environment.

**Comment by ben851** [comment]
Dev schedules have been created. Ready for QA

**Comment by ben851** [comment]
It did it's thing and worked!
Here are the runs for QA
Destroy
https://github.com/cds-snc/notification-terraform/actions/runs/11636993555

Create
https://github.com/cds-snc/notification-terraform/actions/runs/11653133509

**Comment by P0NDER0SA** [comment]
Cron job worked!  Moving to Done
