### ISSUE TITLE
Turn on new Pinpoint code in production: initial release

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#361]
# Description

As a Notify user, I need my SMS to be sent from the appropriate numbers

## WHY are we building?

We have brought the pinpoint code back into the code base and it seems to be working. We will now enable it in production.

## WHAT are we building?

Turn on Pinpoint code in production.

## VALUE created by our solution

Will be able to restrict shortcode usage.

# Acceptance Criteria

- [x] initial release of pinpoint only uses pinpoint for a few templates. Rest go through SNS.

# QA Steps (in production)

 - [x] Send an sms using a [staging](https://staging.notification.cdssandbox.xyz/services/3ae2fb6a-bec7-47d6-8f8b-36e2519f7c6d/templates/b06cb566-6b8c-4558-b5a5-cfeca0c8f962) or [production](https://notification.canada.ca/services/a581e959-c698-46da-8d46-58220ef03fd5/templates/afeac4c1-1763-4da5-a00c-1cb266188488) template in the shortcode list. It should be sent from the Pinpoint shortcode pool.
 - [x] Send an sms using a template not in the list. It should be sent by SNS.

**Comment by sastels** [comment]
This PR will allow us to use pinpoint for a few templates and SNS for the rest
https://github.com/cds-snc/notification-api/pull/2184

**Comment by sastels** [comment]
PR merged. Currently (and tested) in staging:
- Send an sms using a template in the SC list. It should be sent by Pinpoint (in the logs you should see AWS Pinpoint request finished in ...)
- Send an sms using a template not in the list. It should be sent from SNS (AWS SNS request finished in ...).

After we release this to prod we will set values for prod `AWS_PINPOINT_SC_POOL_ID` and  `AWS_PINPOINT_SC_TEMPLATE_IDS`. This will bring production to the same state as staging (Pinpoint for certain templates, SNS for the rest).

**Comment by sastels** [comment]
PR merged. Currently (and tested) in staging:
- Send an sms using a template in the SC list. It should be sent by Pinpoint (in the logs you should see AWS Pinpoint request finished in ...)
- Send an sms using a template not in the list. It should be sent from SNS (AWS SNS request finished in ...).

After we release this to prod we will set values for prod `AWS_PINPOINT_SC_POOL_ID` and  `AWS_PINPOINT_SC_TEMPLATE_IDS`. This will bring production to the same state as staging (Pinpoint for certain templates, SNS for the rest).

**Comment by sastels** [comment]
The shortcode pinpoint delivery receipts and the longcode delivery receipts are different. Fix merged:
https://github.com/cds-snc/notification-api/pull/2189

Next: retest in staging, then release to prod tomorrow and test there.

**Comment by ben851** [comment]
The short code doesn't send back the same responses as long codes, and we had to make a change that will be released today.

**Comment by sastels** [comment]
short code delivery receipts processed correctly now :tada:

**Comment by ben851** [comment]
@ben851 to QA

**Comment by ben851** [comment]
Sent two messages, verified that pinpoint was sent by pinpoint, and the other was sent by SNS.
