### ISSUE TITLE
ADR: CI/CD for Kubernetes

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#365]
# Description

As a developer of notify, I would like to have a clear understanding of how the CICD for Kubernetes works, as well as provide a road map for improvements. 

## WHY are we building?

There's no documentation on how CI/CD is done for Kubernetes. Since we are in the process of migrating from Kustomize to Helmfile, it would be a good time to document both the existing process, as well as the changes required to implement helmfile.

## WHAT are we building?

An ADR documenting how our CI/CD works.

## VALUE created by our solution

Increased knowledge at the team level
Easier troubleshooting of environments

# Acceptance Criteria

- [ ] The current CI/CD process is documented
- [ ] Any changes required for Helmfile are documented and approved by the team
- [ ] The team has reviewed the ADR and does not have any questions or concerns.

**Comment by ben851** [comment]
Working on first PR with existing CICD

**Comment by ben851** [comment]
Reworked the existing ADR to include both current and future state for the release process.

**Comment by sastels** [comment]
All should read the ADR and we should discuss

**Comment by ben851** [comment]
Wanting to expand on the ADR diagrams, I decided to look into auto-generated workflow maps. I'm work on a github workflow that will auto-generate this.

**Comment by jimleroyer** [comment]
Jimmy reviewed the ADR and Ben to reply on his comments, questions or suggestions.

**Comment by ben851** [comment]
Started reviewing this yesterday - merged the quick suggestions, will work on the others.

**Comment by ben851** [comment]
Added in diagrams of all the CI/CD processes for PR and merge to main/releases

**Comment by ben851** [comment]
Updated the PR to be a bit more focused in messaging. Ready to be reviewed.

**Comment by ben851** [comment]
Jimmy and Pond reviewed - I will review their review

**Comment by ben851** [comment]
Reviewed their review. Answered a couple questions. Will put the latest revision out to the dev team

**Comment by sastels** [comment]
Steve and Jimmy to do a final read over and approve
