### ISSUE TITLE
CHORE: K8s 1.30 Upgrade

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#366]
# What

Upgrade the EKS clusters to the latest EKS version, 1.30. 

# Why

This removes technical debt, ensures we have the latest features and patches.

# Acceptance Criteria

- [x] Verify that there are no breaking changes
- [x] Dev Upgraded to 1.30
- [x] Staging upgrade to 1.30
- [x] Performance test in staging shows no changes
- [x] Production upgraded to 1.30

# Resources

- https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/
- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.30

# Triggers / Schedule

Should be implemented ASAP after EKS announcement in slack

**Comment by ben851** [comment]
Waiting for the chore template to be merged before updating this.

Dev and staging are k8s 1.30 and I have set Karpenter AMI IDs in terraform as a secret to be read in.

I've also opened a github issue with karpenter asking to support different formats for the AMI ID so that we don't need a separate entry in TF for Karpenter.

https://github.com/aws/karpenter-provider-aws/issues/6318

**Comment by ben851** [comment]
Everything upgraded in dev and staging, waiting till Monday for production

**Comment by sastels** [comment]
will release to prod today

**Comment by ben851** [comment]
Released and working
