### ISSUE TITLE
Create Pinpoint SMS alarms and dashboard

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#368]
# Description

As a Notify developer, I need to be able to evaluate Pinpoint SMS performance so that I can determine system performance and availability.

## WHY are we building?

Need to be able to monitor Pinpoint SMS functions

## WHAT are we building?

Add alarms and dashboards for Pinpoint SMS

## VALUE created by our solution

knowing when system is having issues

# Acceptance Criteria

- [ ] SNS SMS alarms duplicated for Pinpoint as needed
- [ ] dashboards created / modified as needed

# QA Steps

- [ ] send a few Pinpoint SMS and see them in the dashboard

**Comment by sastels** [comment]
PR to add some Pinpoint metrics:
cds-snc/notification-terraform#1354

**Comment by sastels** [comment]
alarms merged in. Now one for a Pinpoint dashboard!
cds-snc/notification-terraform#1369

**Comment by sastels** [comment]
dashboard merged but not all working. Will play with in staging and make a corresponding PR.

**Comment by sastels** [comment]
Fix/pinpoint dashboard:
https://github.com/cds-snc/notification-terraform/pull/1374

**Comment by sastels** [comment]
had issues with the terraform release, so going to wait and merge this to staging Thursday

**Comment by sastels** [comment]
fix for a link in the system dashboard:
https://github.com/cds-snc/notification-terraform/pull/1380

**Comment by jimleroyer** [comment]
Jimmy will review the board once it has been merged!

**Comment by jimleroyer** [comment]
Jimmy reviewed the keywords and it looks good (except for one test artifact)!

**Comment by jimleroyer** [comment]
I checked in production and some data was missing in the widgets, it looked good though for what was there. I would like to wait a bit more once we have pinpoint in production, so that would also be an extra verification step in prod for pinpoint. =)

**Comment by jimleroyer** [comment]
Let's move this to done as we monitored the Pinpoint production enabling through it yesterday and it worked perfect!
