### ISSUE TITLE
Configure IPv4 Geolocate Service to Deploy to Production

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#369]
# Description

As a maintainer of the ipv4-geolocate repository,
I want its workflow to use the new Github VPN that we set up
So that the workflow continues to execute properly.

## WHY are we building?

Keep our GH workflows executing successfully. 

## WHAT are we building?

The workflow needs to connect to the production VPN and deploy the new version of IPv4 Geolocate to prod K8s

## VALUE created by our solution

Aligned with latest security standards (VPN to protect our kubernetes endpoints) and our other repository workflows.

# Acceptance Criteria

- [x] The staging GH workflows can roll out a new version of the ipv4-geolocate-webservice.
- [ ] The production GH workflows can roll out a new version of the ipv4-geolocate-webservice.

# QA Steps

- [ ] Verify that the daily job is working (or trigger manually and verify)

**Comment by P0NDER0SA** [comment]
coded!  opening a PR
https://github.com/cds-snc/ipv4-geolocate-webservice/pull/52

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/ipv4-geolocate-webservice/pull/53

**Comment by P0NDER0SA** [comment]
all merged and working. Let's check that the cron job is working tomorrow.

**Comment by ben851** [comment]
@ben851 to QA

**Comment by P0NDER0SA** [comment]
Need to QA this today -- check that it's been running properly and deploying on scheduled cron job

**Comment by ben851** [comment]
I forgot. I will QA today

**Comment by P0NDER0SA** [comment]
This appears to be scheduled for weekly -- it's been 5 days.  If we dont see these run by later this week, something is wrong

**Comment by P0NDER0SA** [comment]
This one is QAed and it's good!
