### ISSUE TITLE
Enable the Pinpoint default pool

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#370]
# Description

As a Notify team member, I need to be able to decide which SMS gets sent **not** using the short code.

## WHY are we building?

Currently we can specify templates that are sent with the shortcode. However the other templates will also often get sent with the shortcode. We would like to have the other templates sent with the long codes.

## WHAT are we building?

Create / turn on the Pinpoint default pool.

## VALUE created by our solution

Fewer messages sent via short code. This will save money and allow us to reserve the short code for high priority messages.

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [x] default pool created
- [x] default pool code added but disabled
- [x] long codes have keywords set appropriately (ie same as short code)
- [x] long codes added to the default pool
- [x] fix the toll free US number in staging (**UPDATE**: new registration "under review")
- [x] default pool enabled and tested in staging
- [x] default pool enabled and tested in production

# QA Steps

## Staging
 - [x] Send an sms using a template in the shortcode list. It should be sent from the Pinpoint shortcode pool.
 - [x] Send an sms using a template not in the list. It should be sent from the Pinpoint default pool.
 - [x] Send an sms using a [service with a dedicated number](https://staging.notification.cdssandbox.xyz/services/2317d68b-f3ab-4949-956d-4367b488db4b). If should be sent through SNS / us-west-2 (and from the dedicated number)
 - [x] Send an sms to a [US number](https://www.proovl.com/test). It should be sent through SNS / us-west-2 (and fail until we sort out our TFN)
 - [x] Send an sms to an [international number](https://www.proovl.com/test). It should be sent by SNS (and received by Proovl!)
 - [x] Send an SMS to a fake Guam number (1 671 555 0123). Should be sent with SNS (but fail since it's a fake number)
 - [x] Send an email to verify that they still work.
 - [x] Unsubscribe via STOP or ARRET and verify that you're on the opt out list.
 - [x] Remove your self from the opt out list.

## Production
 - [x] Send an sms using a template in the shortcode list. It should be sent from the Pinpoint shortcode pool (and the shortcode!).
 - [x] Send an sms using a template not in the list. It should be sent from the Pinpoint default pool.
 - [x] Send an sms using a service with a dedicated number. If should be sent through SNS / us-west-2 (and from the dedicated number)
- [x] Send an sms to a [US number](https://www.proovl.com/test). It should be sent through SNS / us-west-2 
 - [x] Send an sms to an [international number](https://www.proovl.com/test). It should be sent by SNS (and received by Proovl!)
 - [x] Send an SMS to a fake Guam number (1 671 555 0123). Should be sent with SNS (but fail since it's a fake number)
 - [x] Send an email to verify that they still work.
 - [x] Unsubscribe via STOP or ARRET and verify that you're on the opt out list.
 - [x] Wait 10 seconds and then try to send to yourself again. The notification should immediately be marked as opted out.
 - [x] Remove your self from the opt out list.

**Comment by sastels** [comment]
Add the default pool to k8s but set `AWS_PINPOINT_DEFAULT_POOL_ID` to "":
https://github.com/cds-snc/notification-manifests/pull/2668

**Comment by sastels** [comment]
Will release tomorrow. After that, will turn on in staging.

**Comment by sastels** [comment]
WIP PR to set phone number keywords correctly
https://github.com/cds-snc/notification-terraform/pull/1358

**Comment by sastels** [comment]
Default pool enabled in staging, looks pretty good!

One issue: looks like numbers that have opted out (ie in the past) just hang in "sending" rather than throwing an error. More investigation needed.

**Comment by sastels** [comment]
PR to set phone number keywords correctly is ready for :eyes: :
https://github.com/cds-snc/notification-terraform/pull/1358

**Comment by jimleroyer** [comment]
This was merged and moving in QA. Jimmy will review the keywords messages in staging env.

**Comment by sastels** [comment]
Long codes in production have been moved to the default pool and had their keywords set appropriately.

Trying to set the `ARRET` keyword to `OPT_OUT` for the shortcode pool gives the error
```
Error
Conflict Occurred - Reason="RESOURCE_MODIFICATION_NOT_ALLOWED" ResourceType="keyword" ResourceId="ARRET" RequestId: 7b4280c0-c1d5-4950-a40d-da679818a1a9 HttpStatusCode: 400
```

**Comment by sastels** [comment]
Having a bug bash on staging Tuesday.

**Comment by jimleroyer** [comment]
Jimmy reviewed the keywords and these look good!

**Comment by sastels** [comment]
Bug bash went well, no blocvkers foubnd,.

**Comment by sastels** [comment]
Targeting release to production Wednesday June 19, 10:30.
- special [MANIFEST] PR to switch it on (revert this PR to turn back off)
- run through the QA on prod steps ASAP

**Comment by sastels** [comment]
Had a problem sending to non-US international numbers :disappointed:
PR to fix
https://github.com/cds-snc/notification-api/pull/2195

testing in staging.....

**Comment by sastels** [comment]
Also found that in the repo and staging SNS is not allowed to send internationally. It has been manually enabled in the prod database. We should fix this with a migration. At the same time we can probably turn on international sending for Pinpoint.

**Comment by sastels** [comment]
Discovered what the `NO_ORIGINATION_IDENTITIES_FOUND` error is that we were seeing in production
- we were trying to use Pinpoint to send to international numbers
- in Pinpoint or SNS, if you send to a number in a different country (ie a country you don't own a number in), AWS will use one of their own numbers in that country to send. This happens automagically with SNS, but for Pinpoint there's an explicit setting to enable (that is off by default).

**Comment by sastels** [comment]
Enable international sending for SNS and Pinpoint in our provider database:
https://github.com/cds-snc/notification-api/pull/2197

Tweak the pool creation script to enable shared routes

**Comment by sastels** [comment]
ok, everything's been reviewed and approved! Will merge into staging and test today.

**Comment by sastels** [comment]
merged into staging and tested (Pinpoint configured there for default pool)

Next steps:
1. Release to prod (Tues).
2. Verify that [SNS and Pinpoint have supports_international set to True](https://notification.canada.ca/providers).
3. Configure the default pool on prod and QA

**Comment by sastels** [comment]
Will we need to have specific sender ids in pinpoint? :thinking:
https://docs.aws.amazon.com/sms-voice/latest/userguide/sender-id-request.html

**Comment by sastels** [comment]
that didn't work as expected, I put in a support ticket.

I might change back to using Pinpoint for everything except international (and designated numbers) until we get this sorted.

**Comment by sastels** [comment]
Use SNS for international:
https://github.com/cds-snc/notification-api/pull/2204

**Comment by sastels** [comment]
PRs merged, updated and went through staging QA steps again :tada:
Should be ready to turn on in prod again once the "SNS for international" api PR is released.

**Comment by sastels** [comment]
[note from AWS](https://support.console.aws.amazon.com/support/home?region=ca-central-1#/case/?displayId=171950568300051&language=en): to use the default sender id in Pinpoint we need to send without an origination-identity. So, essentially, to send internationally we should not supply a pool.

**Comment by sastels** [comment]
PR to turn on default pool in prod
https://github.com/cds-snc/notification-manifests/pull/2733

**Comment by sastels** [comment]
Turned on in prod and prod QA tests pass. Continuing to monitor...

**Comment by sastels** [comment]
Pinpoint SendTextMessage throws a DESTINATION_PHONE_NUMBER_OPTED_OUT error when a number is opted out, we should handle this without an error
botocore.errorfactory.ConflictException: An error occurred (ConflictException) when calling the SendTextMessage operation: Conflict Occurred - Reason="DESTINATION_PHONE_NUMBER_OPTED_OUT" ResourceType="opt-out-list" ResourceId="Default"
This notification
It's status is "... is opted out", but I think that's because after the Pinpoint celery error it retried with SNS. SNS tries to send it (and charges us) and returns that status. So with Pinpoint we should catch the celery error and update the status without having SNS send it.

**Comment by sastels** [comment]
WIP PR to fix:
https://github.com/cds-snc/notification-api/pull/2207

PR to fix a couple things on the Pinpoint dashboard:
https://github.com/cds-snc/notification-terraform/pull/1415

**Comment by sastels** [comment]
Also I noticed that https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#alarmsV2:alarm/pinpoint-sms-success-rate-warning?~(search~'pinpoint) did not have data - we should look through all the Pinpoint alarms and make sure they all have data as appropriate.

**Comment by sastels** [comment]
We should add a card wrt SNS alarms, ie at least make critical alarm non-paging

**Comment by sastels** [comment]
releasing the opted out numbers fix to prod today

**Comment by sastels** [comment]
released and opted out number tested. Ready for QA!

**Comment by jimleroyer** [comment]
QA notes.

1. Send an sms using a template in the shortcode list. It should be sent from the Pinpoint shortcode pool (and the shortcode!). ✅
1. Send an sms using a template not in the list. It should be sent from the Pinpoint default pool. ✅
    ⚠ I could not see the log for the successful delivery in the pinpoint log when it used the default pool, but I was able for the previous short code check on the other hand. Do we know why it is not logged in there?
1. Send an sms using a service with a dedicated number. If should be sent through SNS / us-west-2 (and from the dedicated number)
1. Send an sms to a US number. It should be sent through SNS / us-west-2
1. Send an sms to an international number. It should be sent by SNS (and received by Proovl!)
1. Send an SMS to a fake Guam number (1 671 555 0123). Should be sent with SNS (but fail since it's a fake number)
1. Send an email to verify that they still work.
1. Unsubscribe via STOP or ARRET and verify that you're on the opt out list.
1. Wait 10 seconds and then try to send to yourself again. The notification should immediately be marked as opted out.
1. Remove your self from the opt out list.

**Comment by P0NDER0SA** [comment]
Jimmy experienced some issues with Proovl (as per the steps above).  Steve says Proovl might have been experiencing issues yesterday, so Jimmy might try again today.

**Comment by jimleroyer** [comment]
I updated the test cases with the results along with some notes. This issue can be considered QA'ed successfully.
