### ISSUE TITLE
The GCNotify service should always use the short code to send SMS

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#377]
# Description

As a product owner of GCNotify,
I want our main service to always use the short code to send SMS,
So that our service is trusted
And that we eat our own food while adopting short code further.

## WHY are we building?

For trust of GCNotify users receiving our SMS and to test bed the short code with our own service first. GCNotify is a perfect candidate for short code sending and its intended usage.

## WHAT are we building?

The GCNotify SMS templates should all be sending using the short code. 

If possible, it would be nice to configure GCNotify service itself to always use the short code as an override to template specific configuration with the short code. 

## VALUE created by our solution

Trust toward our service. More capacity with the short code which has higher sending capacity. Testing our own dog food to test the short code in real world scenarios.

# Acceptance Criteria

- [x] The GCNotify service and related templates always use the short code to send SMS notifications.

# QA Steps

- [ ] Verify that SMS notifications sent using different templates from the GCNotify service are done via the short code pool.
- [ ] Verify that SMS from other services still use the long code pool.

**Comment by sastels** [comment]
Figured this would be quick and a good way to get more stuff to test out the short code pool.
https://github.com/cds-snc/notification-api/pull/2213

**Comment by jimleroyer** [comment]
I will wait for this one to hit production to use the real short code. This should be reliable enough and safe to deploy in production.

**Comment by sastels** [comment]
released to prod, ready for QA

**Comment by jimleroyer** [comment]
Tested the SMS templates of the GCNotify service in production and they all used the short code to send the SMS.

**Comment by P0NDER0SA** [comment]
moving to done!
