### ISSUE TITLE
Use template category to determine Pinpoint pool

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#382]
# Description

As a Notify user, I need to have my SMS sent by the appropriate vehicle (ie shortcode or longcode) 

## WHY are we building?

We want the Pinpoint pool selection to be dynamically based on the template category.

## WHAT are we building?

Use the template category for Pinpoint pool selection.

## VALUE created by our solution

The short code is used appropriately.

# Acceptance Criteria

- [x] Pinpoint pool is chosen based on the category sending vehicle.
- [x] The App team signs off on the change.

# QA Steps

- [x] Bug bash on sending templates for different categories

**Comment by sastels** [comment]
Will finish PR today

**Comment by sastels** [comment]
ready for review
https://github.com/cds-snc/notification-api/pull/2216

**Comment by sastels** [comment]
reviewed by Jimmy and Andrew. I added an `Enum` as suggested by Andrew and waiting for him to give it another look.

**Comment by P0NDER0SA** [comment]
will need another look.. Steve and Andrew will circle back

**Comment by sastels** [comment]
Andrew happy, will merge into staging and test tomorrow...

**Comment by sastels** [comment]
Why didn't I merge Thursday :thinking: Will merge Monday...

**Comment by sastels** [comment]
Oooops celery doesn't have the new feature flag. Let's fix that
https://github.com/cds-snc/notification-manifests/pull/2773

**Comment by sastels** [comment]
in staging and all good now.

**Comment by P0NDER0SA** [comment]
Steve is gonna investigate some celery errors

**Comment by sastels** [comment]
22 duplicate key errors (notification ids) during the nightly performance test. I suspect that notifications were created but then something crashed and they got retried (and threw an error since they were already in the database there). Not related to Pinpoint / categories (and were emails in any case).

**Comment by P0NDER0SA** [comment]
Jimmy might QA this today

**Comment by sastels** [comment]
Jimmy should QA this today.

**Comment by jimleroyer** [comment]
Jimmy organized a bug bash on Thursday morning for al of us to test this feature in staging.

**Comment by P0NDER0SA** [comment]
Bug Bash was done and all is good! Moving to done
