### ISSUE TITLE
Onboard a new sending provider to GCNotify (Twilio)

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#383]
# Description

As an ops lead of GCNotify,
I want to have an additional sending provider,
Because I want a fallback provider in case that AWS cannot send our notifications.

As a product owner of GCNotify,
I want to have an additional provider,
So that I can test features that are not available with the one I already have.

## WHY are we building?

The primary reason to get an additional provider is for reliability.

Another one is for strategic purpose by augmenting the feature set that we can access to with a provider that has better coverage, such as support for RCS / Universal Profile.

## WHAT are we building?

Procure a new provider for GCNotify. There is built-in support for additional ones in GCNotify but we only had one provider in there for most time, with only having both AWS Pinpoint and AWS SNS recently in there.

## VALUE created by our solution

Additional reliability with a fallback option in case our sending capability is impaired with our primary sending providers.

# Acceptance Criteria

- [ ] A new sending provider is procured.

# Out of Scope
- [ ] The code is not integrated within GCNotify, this task is about procurement.

# QA Steps

- [ ] Using the CLI or UI dashboard of the new procured provider, we can send an email and text message to a destination national long code.

# Additional information

From Calvin:

> So it depends on what you are looking to buy, if you are looking to buy just some SaaS I recommend the Guide to requesting low-dollar value unclassified software subscriptions services.
https://docs.google.com/document/d/1Vc3cKhlCvakHylmKQQEHc44tffLO7lozQ74aHHRQq2o/edit#heading=h.49a16cu36wcw
> I think it's still status quo for now here is the SaaS Request Form: 
> https://docs.google.com/forms/d/e/1FAIpQLSdoFwi3_JZGch7j0ju34kpT06DYwawxI-Ajot6OWaUb1-tMuw/viewform

> If it's something that's available through a cloud service provide (Azure, GCP, etc..) that might be a little trickier, we can handle a bit of money spent on Azure with our current commitments but not a lot, so at least we have an easy path forward for testing things out, if it's GCP or other Cloud Service Providers available through the Cloud Framework Agreement (https://cloud-services-infonuagiques.canada.ca/s/gc-cloud-fa?language=en_US) then that's a bit trickier but still possible, if you want to go that route I recommend you engage Sylvia and the SRE team.

**Comment by jimleroyer** [comment]
Yael reviewed yesterday and Melissa will once she is back. We will send to the security team once the document has been reviewed by the team key participants.

**Comment by P0NDER0SA** [comment]
There's a meeting today that might touch on on this to see if it helps move it along

**Comment by P0NDER0SA** [comment]
Meeting was cancelled :) We did determine that we wont have to modify the request to make it production ready.

**Comment by sastels** [comment]
Melissa is back, Jimmy will look into the status of this issue.

**Comment by jimleroyer** [comment]
Jimmy started conversation with Jenn yesterday, needs to talk to Clara today.

**Comment by jimleroyer** [comment]
I will open an account with Twilio today and speak with Kelsey for the CC info on Tuesday (when she is back on vacation).

**Comment by P0NDER0SA** [comment]
Initiated a converstaion with Clara for New Relic.  Jimmy is gonna open a new card for this one (for NR)

**Comment by jimleroyer** [comment]
I spoke to Kelsey today about Twilio and opened an account with Twilio. I also enrolled us to test RCS feature, it seems it is exclusive base unfortunately. I will inquire further.

**Comment by jimleroyer** [comment]
Kelsey sent the Twilio internal request to onboard on the CC to Leanne.

**Comment by jimleroyer** [comment]
Leanne approved! we can put in the CC but I need to figure out if we can have a shared account first. I logged in using my Google account.

**Comment by jimleroyer** [comment]
I created a shared account, stored the credentials in 1password. I asked Yael to test and after that, we will put in financial info in the account.

**Comment by jimleroyer** [comment]
Will put CC info today in the accout.

**Comment by jimleroyer** [comment]
CC info is in the account. I had to register myself as an owner of the org via a gov official ID as well and registering our organization. Next step would be to explore RCS options if available and ask for support if not. That would be in a different task though and not in scope for this task.

**Comment by ben851** [comment]
@ben851 to QA

**Comment by P0NDER0SA** [comment]
QA Completed!  we discussed the QA steps and sending a message is actually out of scope for this card.  I was able to login and verify that our account is there and things look good.  Moving to done.
