### ISSUE TITLE
Prepare the monitoring for priority lanes outliers

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#385]
# What

Monitor the priority lanes for template outliers that are breaking the SLOs and should be moved into a different priority queue.

# Why

As we are reworking how our sending vehicle and priority queues function, some of the templates will lose its current priority lane configuration and will fall back into the defaults of the predefined category template. It is possible that some of these default might not fit with the current SLOs profile and would need a customized priority lane configuration to be brought back to SLOs stability.

# Acceptance Criteria

-[ ] Bring up the [queries that are in the SLOs document](https://docs.google.com/spreadsheets/d/1G8Eno3FkISdaZf_ySgDHiURnUZyJiz0CqErqC7iRCLk/edit?gid=642403157#gid=642403157) into Blazer for live 1-day analysis.
-[ ] Bring up the [queries that are in the SLOs document](https://docs.google.com/spreadsheets/d/1G8Eno3FkISdaZf_ySgDHiURnUZyJiz0CqErqC7iRCLk/edit?gid=642403157#gid=642403157) into QuickSight for ad-hoc analysis (this routine chore).
-[ ] Identify audit mechanism -- check if the template history table can save these changes so we might not have to maintain manually such a document

# QA

- [x] Review the query in Blazer and execute it with different parameters.
- [x] Review the query in Quicksight and execute it with different parameters.

# Resources

* Blazer and its queries
* Auditing document

**Comment by sastels** [comment]
Started porting / writing queries in Blazer

**Comment by sastels** [comment]
[This dashboard](http://localhost:1338/dashboards/15-dashboard-priority-lane-monitoring?start_time=2024-07-08T00%3A00%3A00Z&template_count_threshold=1000) in Blazer shows templates that have taken longer than the 90% SLO to send.
- grouped by days
- puts together all the notifications for the particular template that have taken longer than the 90% SLO
- shows the # of these slow notifications as well as the median time they took
- only shows a template if many of them were slow on a given day

**Comment by P0NDER0SA** [comment]
Jimmy will take a look

**Comment by sastels** [comment]
We'll make a separate card for keeping an eye on dedicated numbers

**Comment by jimleroyer** [comment]
I checked the query and that looks good. 👍

**Comment by sastels** [comment]
Have the corresponding analysis mostly roughed in in QuickSight, just need the new Notifications with categories dataset.

**Comment by sastels** [comment]
Added template category priority lanes to the quicksight query and made a [dashboard](https://ca-central-1.quicksight.aws.amazon.com/sn/dashboards/b3be42bd-171c-4de7-830b-a72d91311db8) in the Notify shared folder.

**Comment by sastels** [comment]
Can we consider this card done by the [Templates breaking SLOs](https://ca-central-1.quicksight.aws.amazon.com/sn/dashboards/b3be42bd-171c-4de7-830b-a72d91311db8) dashboard?

**Comment by P0NDER0SA** [comment]
We're closing this because this task is replaced by a process to be done by the IC each week.
