### ISSUE TITLE
Command to set platform_admin status

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#389]
# Description

As a platform admin, I need to be able to make others platform admins without manually editing the database.

## WHY are we building?

Currently the only way to make someone a platform admin is to open a writeable connection to the database and manually edit the record for that user. This is dangerous.

## WHAT are we building?

A flask command to toggle the platform admin flag for a given user.

## VALUE created by our solution

Improved security and reliability: We no longer have to manually edit the database to do this fairly common task.

# Acceptance Criteria

- [x] A flask command to toggle the platform_admin flag exists.

# QA Steps

- [x] log into an api or celery pod
- [x] run the command `FLASK_APP=application.py flask command admin -u <your email address> --off`
- [x] clear the users cache (or log out and in) and verify that you are no longer an admin!
- [x] run the command `FLASK_APP=application.py flask command admin -u <your email address>`
- [x] log out and into Notify again and verify that you are once more an admin.

**Comment by sastels** [comment]
I had originally build a system to add a toggle to the user's information page in the platform admin view, but decided that this opened us to a potential escalation of privileges attack if endpoints were not sufficiently secure. So I then decided that it would be better as a flask command that could only be run from within the k8s cluster.

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-api/pull/2225

Probably ready to go but I want to see if I can get the command to flush the user cache.

**Comment by P0NDER0SA** [comment]
Pond will attempt to QA this today

**Comment by P0NDER0SA** [comment]
100% working as expected!
