### ISSUE TITLE
Estimate Cost of New Relic with AWS data ingestion

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#390]
# Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

As a system ops of GCNotify and more specifically of NewRelic,
I need the cost estimate of data transfer between AWS data center and NewRelic,
Once we activate NewRelic features to track AWS events,
So that I can weight in the cost benefit overall paired with a NewRelic plan switch.

## WHY are we building?

We need it to weight in cost and benefits of using NewRelic. If we can switch to a compute cost, this will reduce our bill. We might want to leverage it further and find the right balance in terms of cost.

## WHAT are we building?

* Estimate the cost from AWS to NewRelic data transfer. Offer different load of data transfer depending on the desired data and feature we could use in NewRelic.
* Look into the AWS marketplace for buying NewRelic from there and how much credits we would get for data transfer from AWS to NewRelic. 

## VALUE created by our solution

More leverage from NewRelic for its cost.

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] Estimate the cost from AWS to NewRelic data transfer. Offer different load of data transfer depending on the desired data and feature we could use in NewRelic.
- [ ] Look into the AWS marketplace for buying NewRelic from there and how much credits we would get for data transfer from AWS to NewRelic. 
- [ ] The cost analysis has been reviewed by dev lead. 

# QA Steps

No QA steps.

**Comment by ben851** [comment]
Costing is based on Firehose and Metrics streams.

Firehose sent to S3 in GB last 30 days: 26.5GB
Firehose cost per GB: 0.029
Estimated Firehose Cost: $1 USD

Metric Streams: $0.003 per 1,000 metric updates
I'm having trouble finding how many metric updates we do.

**Comment by ben851** [comment]
I think I can greatly reduce our cost by cleaning up the prometheus metrics. Will investigate.

**Comment by P0NDER0SA** [comment]
Ben is investigating linking NR to Staging AWS to see if it's easier to get an idea of the costing metrics

**Comment by P0NDER0SA** [comment]
Ben is still working on this in Staging before he can get these metrics

**Comment by ben851** [comment]
Confirmed no more metrics are being streamed. Will need to wait till end of month to see our NR bill to see how much this cost su

**Comment by sastels** [comment]
We can figure out the NR costs but still need the AWS costs

**Comment by sastels** [comment]
need to check egress data costs in AWS - Jimmy is investigating...

**Comment by P0NDER0SA** [comment]
We rolled back some of this work because it was causing minor residual issues since a couple of weeks ago.  WE'll revisit this as a team next week.

**Comment by ben851** [comment]
After reviewing the AWS cost explorer, I'm thinking that the jump in costs that we thought were for x-ray were actually from new relic polling in staging - specifically from the Get Metric Data jump:
<img width="1774" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e54d4293cf9ef39e69caf0cbfcbeb829a309a5b6/image.png" alt="image.png" />

This is not enabled on production, and our get metric data costs there are very inexpensive ($20-30/month)

I have disabled the new relic polling on all of AWS in staging, we'll need to wait till next month to verify.

**Comment by ben851** [comment]
Metric Streaming should be cheaper than API polling, but the following services are no supported by metric streaming yet:
AWS Billing, AWS CloudTrail, AWS Health, AWS Trusted Advisor, AWS VPC, and AWS X-Ray

I don't think that any of those should be deal breakers (and if they are, we could always turn polling on just for those).

**Comment by ben851** [comment]
Re-enabled AWS metric stream to NR

**Comment by ben851** [comment]
Metric stream cost us $30 on Sept 17 - more expensive than polling

Also had a huge bump in NR data ingestion, but this may be caused by EKS in dev which I will turn off to get a cleaner look. Will leave metrics stream on another day as well.

<img width="569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--daa005e4660aeeb08029f5719bbfce863d0baae3/image.png" alt="image.png" />

**Comment by ben851** [comment]
Metric stream cost for Sept 18 was $20.99, down 1/3. 

Will leave this on till Friday to get a full 24 hr picture without EKS monitoring

**Comment by ben851** [comment]
<img width="569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelRwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75bba2ce8b33fff8fbb91183c612b5ce1e2ed40f/image.png" alt="image.png" />

**Comment by ben851** [comment]
Over the weekend, we averaged $30 per day on metrics streaming, adding up to $900 USD per month to AWS costs

It looks as though adding metrics will add 10-15gb of data per day on new relic side. This will total between $100-150 USD per month.


<img width="569" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDMwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50a6dced34b43f277609788e6f29d5008f6cdbb2/image.png" alt="image.png" />

**Comment by sastels** [comment]
Jimmy and Ben to get together and review

**Comment by ben851** [comment]
<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUllQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5578e391117c918df04031394585db000e217143/image.png" alt="image.png" />

**Comment by P0NDER0SA** [comment]
We can move this to done!
