### ISSUE TITLE
Tracing / correlate requests through Celery (AWS X-Ray)

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#395]
# Description

As an ops lead,
I want to link all requests going through the Notify stack that was triggered by the same user / same origin IP,
So that I can quickly analyze their behavior and actions on our stack.

## WHY are we building?

Better tracing support through our stack.

## WHAT are we building?

Implementing correlation / trace IDs through celery Potentially [using aws x-ray](https://aws.amazon.com/xray/).

## VALUE created by our solution

Quicker support and incident response. Better routing / behavior analysis of the requests made against Notify.

# Acceptance Criteria** (Definition of done) 

- [ ] Filter correlated logs in various Notify components coming from the same request.

# QA Steps

- [ ] Hit Notify with a request for Celery.

# Additional info

* [AWS X-Ray](https://aws.amazon.com/xray/)
* Notify used [zipkin](https://zipkin.io/) in the past and it has traces of it in the code. Look into the [utils component](https://github.com/cds-snc/notification-utils/blob/623d109f9145996d7f32eacdada190384d8a5ffa/notifications_utils/request_helper.py#L16) among others. That might facilitate the implementation as the feature is present for another product. Ideally we can just tweak and enable it.

**Comment by jimleroyer** [comment]
This is a duplicate of #400 (which is completed) so we will close this one.
