### ISSUE TITLE
Push the current SMS limits to 6000 fragments / minute and see what happens

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#396]
# Description

As a system op of GCNotify,
I need to identify current limits of the system,
So that I can get past these once on the map.

As a business owner of GCNotify, 
I need to tell what is the current blocker for scaling up SMS
so that I can actually scale up SMS.

## WHY are we building?

To scale up SMS further more, given that we now have a short code that is capable of sending 100 SMS/s.

## WHAT are we building?

We want to push the limits to around 6,000 SMS/m (100 SMS/s) to fit the short code speed. If there are no errors, then rejoice!

## VALUE created by our solution

Identify which limits of technical issues are holding us back to match the short code speed.

# Acceptance Criteria

Given the SMS stress test, when an error occurs, then we identify it within a task card with potential follow up actions.
- [x] Come up with a testing strategy to test the limits within the GCNotify system (no boto calls)
- [x] Come up with a testing strategy to test the limits with AWS (with boto calls)
- [x] Crank up the SMS speed to 100 fragments/s.
- [x] Identify errors within task cards.

# QA Steps

- [ ] Review stress test results and potential follow up actions by dev lead. 

# Questions about AWS (figure out or ask them)

1. What is the limit that we can make boto calls to send sms through pinpoint?
2. Say we have 100 long codes. This means we should be able to send 100 SMS fragments per second. If we send at a higher rate for a few seconds, is there some slack? ie will AWS just buffer up the extras and send them later?
3. Does sending to numbers that don't exist (ex: fictitious 555-01** numbers) hurt our reputation?

**Comment by sastels** [comment]
with the current limit in staging of 20 celery-sms-send pods we can get up to 1250 SMS / min sends to the internal test number 6135550123. Note that these sends stop BEFORE making the boto call to pinpoint.
<img width="788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXM5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb28c92f60444cf9a03dd4d804204b3e36b06495/image.png" alt="image.png" />

**Comment by sastels** [comment]
Testing pushing up SMS sending on dev:
https://docs.google.com/spreadsheets/d/1pQ9SFQZF9wFzX7I0z_Cjxt2S2URqpzedIHryO82Xl6g/edit?gid=959863917#gid=959863917

**Comment by sastels** [comment]
Didn't work on this Thursday, will do more testing on dev today.

**Comment by sastels** [comment]
Preliminary: changing rate limit from 1/s to 2/s didn't make a difference. But raising to 10/s sped up the throughput :shrug:

Gathering more data...

**Comment by sastels** [comment]
Things are scaling up now. [Tested rate limits of 1/s, 5/s, 10/s, and 100/s.](https://docs.google.com/spreadsheets/d/1pQ9SFQZF9wFzX7I0z_Cjxt2S2URqpzedIHryO82Xl6g/edit?gid=959863917#gid=959863917)

**Comment by sastels** [comment]
Simulate the AWS network call latency for these tests
https://github.com/cds-snc/notification-api/pull/2290

**Comment by sastels** [comment]
Going to rerun some of the 10/s tests on dev with the new network latency sleep().

**Comment by sastels** [comment]
So we can get around 6000 sends / min using 15 scaling pods and 10/s task rate limit.

- We need to figure out what to do around sms vs fragments (we average 2 fragments / sms in prod). If we send 6000 2-fragment sms per minute AWS will not be happy
- We currently have 51 long codes in prod so we only could do 3000 fragments / minute with the long codes. We may want to get another 49 long codes so that we have the same rate as the short code.

**Comment by sastels** [comment]
Another thought: we could use 555-01* numbers to do real tests (ie do the complete send to boto

- could ask AWS if this will impact our reputation
- can request AWS simulator numbers?

**Comment by sastels** [comment]
- had to do a few things to get dev using Pinpoint
  - set Pinpoint pool env vars in send-sms deployments
  - change log arns in configuration set (there was a bug in the initial script that is fixed now)
 
Ran tests using default pool (one number) to 555 numbers to see what happens when we send more than 1 / sec

- sending 20: all sent one per second. So there's some buffering there.
- sending 100: 39 sent, 60 ThrottlingException, 60 retried with SNS and sent (SNS has 9 numbers for some reason)

**Comment by sastels** [comment]
I think we should:
- set pod count to support 3000 sends / minute (and 10/s task rate limit)
- get 49 more long codes so our default pool will support 6000 fragments / second

**Comment by sastels** [comment]
Wrote up scripts to create and delete phone numbers. Will use to test in staging with 100 long codes and roller coaster tests.

**Comment by sastels** [comment]
:/ We have to match the keywords before we can add a phone number to a pool. On dev everything has the default keywords but on staging and prod we've added new keywords and made everything bilingual. Will have to tweak the phone number adding script...

**Comment by sastels** [comment]
Will reply to AWS today and also start bumping up long codes in production.

**Comment by sastels** [comment]
Added a few more long codes in prod. Got back to AWS and waiting on them again.

**Comment by sastels** [comment]
Hit max of 75 numbers in prod, put in request to AWS for more so we can get to 100 in default-pool.

**Comment by sastels** [comment]
for 6000 fragments / min (3000 sms / min) recommend:
- change task rate limit to 10/s
- set in the hpa max 6 scalable celery-sms-send-scalable pods

Monitor system for:
- ThrottlingException warnings
- max sms send rate

**Comment by sastels** [comment]
Looks like hpa of 3 is a bit better (seeing 2675 npm on dev with INTERNAL_TEST number).

**Comment by jimleroyer** [comment]
We got 74 long code at the moment that we can test with. We don't have parity with the production environment so it is a bit more difficult to test.

We got 2 AWS tickets opened in support. One asking to up the number phone numbers in staging. Another one to get a Canadian emulation long code (which transformed into an AWS feature request).

**Comment by sastels** [comment]
Will hopefully release the 2200 npm config today.

**Comment by jimleroyer** [comment]
We will bring up our tests to 4,400 fragments / minute today in staging env. This should trigger a few rate failures because of the number of available long codes we got in our staging env pool.

**Comment by sastels** [comment]
Some notes on testing strategies:
https://docs.google.com/document/d/1Gr7r_1_6vIMCM2BDLJsplJWZM25si05fecgkxjGuPjA

**Comment by sastels** [comment]
We should also figure out what to do about 3-4 fragment SMS. Currently a flood of them will overwhelm our sending capacity and give a lot of ThrottlingExceptions

**Comment by sastels** [comment]
have 99 long codes in prod now. Will leave in 4400 fps config for a week to verify and then bump it up a bit closer to 6000 fpm.

**Comment by P0NDER0SA** [comment]
We've tested this in Staging, things are in the ballpark and things are looking healthy!  We will want to do a nice test in prod to make sure it's healthy as well (because it's already been released to prod).

**Comment by sastels** [comment]
PR to add billable units to Quicksight to allow us to monitor send rates there
https://github.com/cds-snc/notification-terraform/pull/1572

**Comment by sastels** [comment]
Note that in the last 30 days we've averaged 1.2 fragments / sms, **not** 2

<img width="1190" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efd036268a9c3e6f4cdac0bb0ce43a8a4ea0f043/image.png" alt="image.png" />

**Comment by P0NDER0SA** [comment]
almost done :p

**Comment by sastels** [comment]
New related cards:
[Monitor SMS send rate with new config](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/428)
[Max out sms sending without ThrottlingExceptions for 1-4 fragment sms](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/427)

**Comment by P0NDER0SA** [comment]
OK, after reviewing this one we've determined that we've safely QA'ed this and it can be moved to Done.
