### ISSUE TITLE
Fix the dev environment and bring it up to date

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#406]
# Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome.

As a GCNotify developer, 
I need the dev environment working and updated to latest,
So that I can test experimental infrastructure changes ahead without affecting the staging environment.

## WHY are we building?

To have an unstable environment to GCNotify that we can play with without affecting the development pipeline.

## WHAT are we building?

Fix the dev environment which is currently broken.

## VALUE created by our solution

Test isolated experimental changes without affecting the other developers. This allows us to have a quicker velocity on bigger changes.

# Acceptance Criteria

- [x] The dev environment is up running as normal.
- [x] The dev environment is up to date.

# QA Steps

- [ ] Run smoke tests on the dev environment.

**Comment by ben851** [comment]
Ran into a few hiccups with SRE and the sentinel forwarder module.. Working on a solution with them, but everything is proceeding pretty well. Up to RDS creation today.

**Comment by ben851** [comment]
RDS created - running into lambda problems now.

**Comment by ben851** [comment]
Everything working - the database target group didn't get created.

Blocked due to wanting to retry the database target group creation, and needing to blow away the dev environment before that.

**Comment by ben851** [comment]
Everything is up and running

**Comment by P0NDER0SA** [comment]
I was able to deploy this GHA as of Friday and it all passed!  The application was live and running as well.

**Comment by ben851** [comment]
@sastels to QA

**Comment by sastels** [comment]
I'll run the smoke tests today

**Comment by sastels** [comment]
Ran smoke tests
- had to create a `notification-dev-tf-user` user with admin creds that the smoke test could use
- for some reason had to create a new api key rather that the one I was using on staging
- not that the api lambda does not work on dev so used the api k8s server
- also file attachments do not work on dev
