### ISSUE TITLE
Reduce Redundant Environment Code for Terragrunt

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#414]
# Description

As a Dev, I want to streamline Terragrunt Code so that we can make our codebase easier to manage and maintain

## WHY are we building?

More efficient/smaller code base, hence easier maintenance.

## WHAT are we building?

Consolidate the Terragrunt `hcl` files so that these are sourced from the Terraform `tfvars` files instead. We would end up with only one Terragrunt `hcl` file per component instead of one per component and per environment, reducing the combinatorial factor that produces too many artifacts at current time. Afterward, the TFVars/Variables are going to be centralized to 1Password for Terraform Repository.

## VALUE created by our solution

- Easier to maintain code
- Easier to add new modules
- Simpler Secrets management
- More efficient pipelines and CI

## Acceptance Criteria

 - [ ] **Scenario: Reduce redundant environment code for Terragrunt**
  - Given the current state of the project's environment code
  - When the issue is resolved and the changes are implemented
  - Then the codebase should be more efficient, easier to maintain, and have simpler secrets management

**Comment by jimleroyer** [comment]
The work in #410 along with some additional research makes this issue obsolete. We are reducing the code duplication but also, we will still per-environment folders as per the best practices.
