### ISSUE TITLE
Change cds-ai-codereviewer provider from OpenAI to Azure

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#416]
# Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

## WHY are we building?

_Why do we need this?_

## WHAT are we building?

_What does that entail?_

## VALUE created by our solution

_Close to the business, what's the value?_

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert
- [ ] Update the status of related findings, insights, and hypotheses on the Research Airtable
- [ ] Once change/fix/feature is implemented, link relevant Airtable records to design artifacts (Figma)

* Privacy considerations
* Security controls in place
* Measuring success and metrics

# QA Steps

- [ ] Tested in a realistic production scenario

**Comment by jimleroyer** [comment]
PR in progress:
https://github.com/cds-snc/cds-ai-codereviewer/pull/3

**Comment by sastels** [comment]
Some progress has been made, some issues with OpenAPI remain.

**Comment by sastels** [comment]
The action is working locally but not in Github :/

**Comment by jimleroyer** [comment]
I opened a PR on the ai code review gh action to introduce a include parameter. The PR is self testing as I defined the Github action parameter to only review *.ts and *.yml files, which it did!
https://github.com/cds-snc/cds-ai-codereviewer/pull/6

**Comment by P0NDER0SA** [comment]
POND and Steve will take a look today

**Comment by jimleroyer** [comment]
I am about to open a PR for a script that will scrape the PR bot comments and classify these based on reactions that we will on the comments (classifications ranging from Useful, Noisy, Hallucination, Teachable and Plain Wrong, exporting it all into a CSV that we can later dump into a spreadsheet.

**Comment by jimleroyer** [comment]
The PR for the comments export and categorization is merged and closed!
