### ISSUE TITLE
Bug: Lambdas Repository Blazer CI/Actions are Broken

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#420]
## Describe the bug 

CI is non functional for the Notification Lambdas repository:
https://github.com/cds-snc/notification-lambdas

The issue is the linting/testing Action for Blazer Lambda -- that is looking for docker-compose, but it isn't installed and fails every time.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-3

## To Reproduce

Go to this repo:
https://github.com/cds-snc/notification-lambdas

Run actions against any PR and review the failures for Blazer

## Expected behavior

fails when the code has issues and legitimately fails (as it would when running the same tests locally)

## Impact

We can't merge any PRs against this repo without forcing them

**Comment by ben851** [comment]
@ben851 to QA

**Comment by ben851** [comment]
Re-ran the blazer jobs in this PR and verified that they complete successfully:
https://github.com/cds-snc/notification-lambdas/actions/runs/10855102320?pr=81
