### ISSUE TITLE
Pinpoint SMS dashboard not showing all sms errors

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#421]
## Describe the bug 

We can see errors in `PinpointDirectPublishToPhoneNumber` (where all sms results get dumped) but not all show up in `PinpointDirectPublishToPhoneNumber/Failure`

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor doesn't affect users directly but affects our ability to find and fix issues.

## To Reproduce

1. Go to this [PinpointDirectPublishToPhoneNumber query](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-86400~timeType~'RELATIVE~tz~'LOCAL~unit~'seconds~editorString~'fields*20*40timestamp*20as*20Timestamp*2c*20messageId*20as*20MessageID*2c*20messageStatus*20as*20status*2c*20destinationPhoneNumber*20as*20Destination*2c*20messageStatusDescription*20as*20ProviderResponse*2c*20carrierName*0a*23*20fields*20*40timestamp*0a*7c*20filter*20status*20*21*3d*20*27DELIVERED*27*0a*7c*20filter*20status*20*21*3d*20*27SUCCESSFUL*27*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~queryId~'69face6d-21ba-470a-9d8c-3c227bcf7dbc~source~(~'arn*3aaws*3alogs*3aca-central-1*3a296255494825*3alog-group*3asns*2fca-central-1*2f296255494825*2fPinpointDirectPublishToPhoneNumber)))))
2. See some errors if you set the time frame big enough
3. Look at [PinpointDirectPublishToPhoneNumber/Failure](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-43200~timeType~'RELATIVE~tz~'LOCAL~unit~'seconds~editorString~'fields*20*40timestamp*20as*20Timestamp*2c*20messageId*20as*20MessageID*2c*20messageStatus*20as*20status*2c*20destinationPhoneNumber*20as*20Destination*2c*20messageStatusDescription*20as*20ProviderResponse*2c*20carrierName*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~queryId~'8b6f700d-2eae-4baf-b199-fcfc5d10a4d0~source~(~'sns*2fca-central-1*2f296255494825*2fPinpointDirectPublishToPhoneNumber*2fFailure))))) for the same time frame
4. Not all errors show up here.

## Expected behavior

All errors should be saved in PinpointDirectPublishToPhoneNumber/Failure.

## Impact

Makes it hard to find and fix sms sending issues

**Comment by sastels** [comment]
There was a copy/paste error so that one of the Pinpoint error types was missing from the Failures log group filter :/

This PR fixes

Since this is done by a script rather than terraform proper I've click-ops'd in the change to staging and production.

**Comment by P0NDER0SA** [comment]
should be merged today!

**Comment by ben851** [comment]
@pond to QA

**Comment by P0NDER0SA** [comment]
479 vs 444 on my queries.  Good to Go!

**Comment by pond** [comment]
@ben851 I think you meant @P0NDER0SA not @pond - had me confused for a while there, thought this was some new kind of spam LOL `:-)`
