### ISSUE TITLE
Reduce cost of the AI review PR bot

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#422]
# Description

As Calvin,
I want to be within my Azure budget,
Despite GCNotify developers trying new AI tools to improve their code base.

As a GCNotify developer,
I want to keep on trying the AI PR bot for 1 more week,
while being within budget with the Azure account.

## WHY are we building?

* Lower cost of the AI PR bot.
* Polish error handling of the PR bot that it gave in its first week of trial.

## WHAT are we building?

- Trigger the action manually when the PR assignee is ready for the review, or have it only on PR opening events (not its updates). This should lower costs and make it less chatty.
- Change region to have lower costs.
- [Fix the error crashing down the reviews](https://github.com/cds-snc/cds-ai-codereviewer/pull/10), coming from incorrect reported line numbers by the AI.
- Let's use the reactions 👍(useful), 😕(hallucination)👀(noisy)🚀(teachable)👎(incorrect) on the comments to classify AI bot comments.
- Then we can resume testing again of the AI review bot for 1 more week.

## VALUE created by our solution

Trying out the PR review bot one and getting AI recommendations.

# Acceptance Criteria

- [x] Revamped error handling preventing the Github action to crash.
- [x] Changed region for executing the AI PR bot responses, hence lowering the costs.
- [x] Lowered the number of times the Github action will run against the PRs (triggered manually or automatically executed once).

# QA Steps

- [x] Tested against a PR
- [x] Test against the acceptance criteria requirements
- [x] Verify costs have been reduced w/ Calvin

**Comment by jimleroyer** [comment]
I had to add support for the `push` Github workflow trigger as this was unsupported by the script. I refactored afterward the logic as it started to get crowded with duplicate and messy logic. Fortunately, it seems that the new supported `event` works. Unfortunately, we are back with our issue with the logic trying to comment on an inexistent line number in the pull request.

**Comment by jimleroyer** [comment]
I made additional changes to the logic to avoid the error about inexistent line number when commenting on the PR. Unfortunately, it is not easy to re-trigger and I am unsure if that is fixed. I added extra logging to be more prepared next time that it does happen though.
https://github.com/cds-snc/cds-ai-codereviewer/pull/11

**Comment by sastels** [comment]
Steve will take a look!

**Comment by jimleroyer** [comment]
We spent 21c only so far out of the 50$ budget we got:
<img width="1560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzRXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa5b2fac1758575206c8be953e4d84e5ce078881/image.png" alt="image.png" />
