### ISSUE TITLE
Create dashboards and procedures for monitoring the SMS send rate

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#428]
# Description

As a Notify developer I need to be aware of our SMS sending rates so that I can use our resources as efficiently as possible.

## WHY are we building?

Need to see how close to 6000 fragments per minute we can get. With price is right rules (closest without going over). 

## WHAT are we building?

Create a dashboard for monitoring SMS sending.

## VALUE created by our solution

- We are aware of how efficiently we're using our AWS resources and can tweak our SMS configuration as needed.

# Acceptance Criteria

- [x] Create a new dashboard for SMS sending (send rate, send times, normal vs dedicated number usage)
- [x] Dashboard is stored in Terraform
- [x] Introduce a monitor sending rate task for the IC

# QA Steps

- [x] Examine the dashboard in production.

**Comment by sastels** [comment]
[Roughed in dashboard for monitoring SMS sending and bottlenecks](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#dashboards/dashboard/SJA-SMS-send-rate-monitoring)

**Comment by P0NDER0SA** [comment]
Jimmy will take a look!

**Comment by sastels** [comment]
[Uploading... image.png]

**Comment by ben851** [comment]
@jimleroyer to review the dashboard

**Comment by ben851** [comment]
Jimmy scheduled a meeting

**Comment by sastels** [comment]
Revised dashboard in terraform!

https://github.com/cds-snc/notification-terraform/pull/1597

**Comment by sastels** [comment]
merged.
But left a `production` in the dashboard terraform :/
<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b33d9e07ed3cf3126b960d3b8054bbe854f127f/image.png" alt="image.png" />

Will make another PR to fix...

**Comment by sastels** [comment]
Will rescope this card slightly to remove monitoring so we can move this card to done.
