### ISSUE TITLE
Cloudwatch query / alert for success/failure rate by providers

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#431]
# Description

As an ops lead, 
I need to monitor the success/failures rates of SMS by providers,
So that I can quickly identify ongoing issue with telecoms.

## WHY are we building?

To increase our awareness of ongoing telecoms issues.

## WHAT are we building?

* Cloudwatch query to track success and failure rates by providers.
* Alert that raise warning and critical alarms when a certain failure rate threshold is met for a certain provider.
* Let's bring missing SMS queries from Terraform into Terraform.
* Bring forward SMS queries of SNS into Pinpoint (and save into Terraform).

## VALUE created by our solution

Better tracking of SMS providers and earlier detection with faster response to related incidents.

# Acceptance Criteria

- [x] SMS failure metrics by providers.
- [x] Raised warning / critical alarms when met with certain thresholds.
- [x] All SMS CWLI queries are saved into Terraform.
- [x] SMS SNS queries are brought forward into Pinpoint.

# QA Steps

- [x] Monitor the failure SMS rate by providers.
- [x] Test and critical alarms with lowered threshold.
- [x] Check the SMS queries are into CWLI.

**Comment by sastels** [comment]
Moving to blocked for now. On Tuesday Oct 15 will bump up send rate to 6000 fpm

**Comment by jimleroyer** [comment]
Everything is ready in the PR and that's final, feel free to review now:
https://github.com/cds-snc/notification-terraform/pull/1574/files

**Comment by ben851** [comment]
Waiting on a prod release to QA this

**Comment by sastels** [comment]
released to production!

**Comment by jimleroyer** [comment]
Added widgets for SMS failures broken down by carriers:
https://github.com/cds-snc/notification-terraform/pull/1599

**Comment by sastels** [comment]
not merged yet.

**Comment by sastels** [comment]
merged and released! Steve will look at in prod!

**Comment by sastels** [comment]
looks good in prod! charts / query have data.

**Comment by sastels** [comment]
[Rogers alarm](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#alarmsV2:edit/pinpoint-sms-failures-rogers-warning?~(Page~'MetricSelection~AlarmType~'MetricAlarm~AlarmData~(Namespace~'LogMetrics~MetricName~'pinpoint-sms-failures-carriers~Dimensions~(~(Name~'Carrier~Value~'Rogers*20Communications*20Canada*20Inc.))~Period~300~Statistic~'Sum~AlarmName~'pinpoint-sms-failures-rogers-warning~AlarmDescription~'Pinpoint*20SMS*20failures*20are*20more*20than*2050*20for*20Rogers*20Communications*20Canada*20Inc.~ActionsEnabled~true~ComparisonOperator~'GreaterThanThreshold~Threshold~50~DatapointsToAlarm~1~EvaluationPeriods~1~TreatMissingData~'notBreaching~AlarmActions~(~'arn*3aaws*3asns*3aca-central-1*3a296255494825*3aalert-warning)~InsufficientDataActions~(~)~OKActions~(~'arn*3aaws*3asns*3aca-central-1*3a296255494825*3aalert-warning))~AlarmRecommendation~false~MultiTimeSeries~false))

Set period 5m -> 1day, threshold 50 -> 1
