### ISSUE TITLE
ADR for Terraform Secrets/Variable Organization

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#432]
https://github.com/cds-snc/ADR/blob/5b73ec6f0f0a2616cf2bfafff323d155e99f7774/0002_Terraform_Variable_Organization.md

https://github.com/cds-snc/ADR/pull/11

**Comment by ben851** [comment]
We will put this Wednesday, Oct 16 as the "read by" deadline.

**Comment by sastels** [comment]
Will merge today! :tada:
