### ISSUE TITLE
Move Terraform Non-Sensitive Variables into TF Repository from 1Pass

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#433]
# Description

Move Terraform Non-Sensitive Variables into TF Repository from 1Pass
https://github.com/cds-snc/ADR/pull/11

## WHY are we building?

After merging card #410 we have all of our Terraform and Terragrunt variables and secrets encapulated in TFVars files in password.  This poses some challenges when it comes to tracking configuration updates with github.  Traceability was lost.  Some examples of this were K8s Nodes and Database versions.

## WHAT are we building?

Creating env files for each environment in our Terragrunt folder that contains non-secret configurations

## VALUE created by our solution

Improved traceability for versioning of our infrastructure releases

# Acceptance Criteria

All plans and apply jobs pass in our CI on Staging and Production without any outlying/unexpected changes.

# QA Steps

- [x] Verify our Plan and Apply jobs on Staging
- [x] Verify our Plan and Apply jobs on Production

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-terraform/pull/1579

**Comment by ben851** [comment]
Draft PR created, Pond will continue working on the env_var.hcl files for each folder.

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-terraform/pull/1579 is open!  Should have all changes required.  If this merges we can remove the old files and start work on removing old GH secrets.
