### ISSUE TITLE
Move Notify API k8s to Helmfile/AWS Secrets Manager

### ISSUE THREAD

**Issue by P0NDER0SA** [cds-snc/notification-planning-core#444]
# Description

As a developer of notify, I would like all of our kubernetes deployments to be managed by Helmfile so that all of our kubernetes code is in one location.  I would also like to have all secrets automated from a single source of truth (1pass -> AWS Secrets).

## WHY are we building?

- Provides the ability to deploy dynamic environments
- Provides the ability to run "diff" commands against environments
- Reduces the amount of code that Notify has to manage
- Keeps code DRY

## WHAT are we building?

- [ ] Add api entry to the helmfile
- [ ] source secrets for helmfile from AWS Secrets Manager
- [ ] source configuration values from helmfile overrides where necessary
- [ ] adjust GitHub actions to work with these changes

## VALUE created by our solution

- Increased reliability via reduced chance of accidental changes during releases
- Increased velocity due to reduction in maintenance
- better secrets management that falls in line with our OKRs

# Acceptance Criteria

- [x] Notify API is deployed and managed with helmfile on DEV
- [x] All secrets required by api are sourced from 1pass -> terraform -> aws secrets manager and accessed using a kubernetes secret
- [x] Notify API (k8s) still works on DEV

# QA Steps
- [x] Login and use API on Dev

**Comment by sastels** [comment]
Starting on this today.

**Comment by sastels** [comment]
Draft PR in progress

**Comment by P0NDER0SA** [comment]
https://github.com/cds-snc/notification-manifests/pull/3055

**Comment by jimleroyer** [comment]
Will pole in dev with the changes of the PR. We could deploy in staging as the changes will only affect dev and won't affect staging/prod without enabling it. Further changes might get required locally for developers and their `.env` files. We need to discuss.

**Comment by jimleroyer** [comment]
PR about to be merged. Bouncing around on organization of the files.

**Comment by jimleroyer** [comment]
Some things are not working in the dev environment and Ben needs to use his magic wand.
