### ISSUE TITLE
Celery errors not causing alarms to fire

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#445]
## Describe the bug 

We have some workers celery errors in production that don't get triggered

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-2 Major : Stuff could be broken without us knowing about it.

## To Reproduce

Cause errors with a Forked worker I guess? Look at [this time period](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-10-23T12*3a50*3a26.086Z~start~'2024-10-23T12*3a17*3a33.913Z~timeType~'ABSOLUTE~tz~'LOCAL~editorString~'fields*20*40timestamp*2c*20log*2c*20kubernetes.container_name*20as*20app*2c*20kubernetes.pod_name*20as*20pod_name*2c*20*40logStream*0a*7c*20filter*20kubernetes.container_name*20like*20*2f*5ecelery*2f*0a*7c*20filter*20*40message*20like*20*2fERROR*5c*2f.*2aWorker*2f*20or*20*40message*20like*20*2fERROR*5c*2fMainProcess*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020*0a~queryId~'6e83dbc1-06ae-4b00-8414-75835131cbc2~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-production-eks-cluster*2fapplication)))

## Expected behavior

appropriate alarm goes off

## Impact

Won't notice when system is broken.

## QA 

- [x] Trigger an exception with the previously undetected events/pattern.

**Comment by sastels** [comment]
Ben fixed!
https://github.com/cds-snc/notification-terraform/pull/1618

**Comment by ben851** [comment]
The regex for the worker filter on the metric was incorrect, it was *Worker instead of .*Worker. I validated that .*Worker works using regex101.com
