### ISSUE TITLE
Create dryrun test number, and change internal test number back to not calling boto

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#447]
# Description

As a notify dev, I need to be able to test Notify SMS without calling boto.

## WHY are we building?

We switched our INTERNAL_TEST_NUMBER to using dryrun, which lets us test the connection to AWS. However this is rate limited by AWS so we cannot stress test the Notify internals with large sends without triggering throttling errors.

## WHAT are we building?

- Create a DRYRUN_TEST_NUMBER and change the existing code to use dryrun for sends to that number instead of INTERNAL_TEST_NUMBER.
- for sends to INTERNAL_TEST_NUMBER, do not do a boto call at all.
- in both cases, we should send a fake "delivered" receipt (as we've always done for the INTERNAL_TEST_NUMBER).

## VALUE created by our solution

Can load test without triggering the dryrun (which then sends for real with SNS and costs us money)

# Acceptance Criteria

- [x] INTERNAL_TEST_NUMBER changed to not do boto call.
- [x] DRYRUN_TEST_NUMBER added and does dryrun.
- [x] sends to both create a fake delivery receipt.

# QA Steps

- [x] Send to INTERNAL_TEST_NUMBER 16135550123 and see in logs "no boto call to AWS"
- [x] Send to EXTERNAL_TEST_NUMBER 16135550124 and see in logs "Boto call made to AWS, but not send on."
- [x] In both cases the notifications should be marked as delivered.

**Comment by sastels** [comment]
We kinda need this to really test things well :/ 
draft PR https://github.com/cds-snc/notification-api/pull/2333

**Comment by sastels** [comment]
PR done, will give it another local test and move to review.

**Comment by sastels** [comment]
got the ai review but didn't address comments yet, went down a colima rabbit hole instead.

**Comment by P0NDER0SA** [comment]
same update!

**Comment by sastels** [comment]
ready for review and / or suggestions for renaming `INTERNAL_TEST_NUMBER` and `DRYRUN_TEST_NUMBER`:
https://github.com/cds-snc/notification-api/pull/2333

**Comment by sastels** [comment]
maybe `EXTERNAL_TEST_NUMBER` instead of `DRYRUN_TEST_NUMBER`?

**Comment by sastels** [comment]
renamed to `EXTERNAL_TEST_NUMBER` and PR is ready for review.

**Comment by P0NDER0SA** [comment]
Merging today!

**Comment by P0NDER0SA** [comment]
Ben is gonna QA This today

**Comment by ben851** [comment]
QA'ed looks good
