### ISSUE TITLE
[CHORE] Delete and clean up the trvapply-vrtdemande service and related domain

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#448]
# What

Delete the trvapply-vrtdemande  service and its related `trvapply-vrtdemande.apps.cic.gc.ca` domain in Terraform.

# Why

The service has reached end of life. [We got confirmation](https://cds-snc.freshdesk.com/a/tickets/19615) by the service owners.

# Acceptance Criteria

- [x] Delete domain in Terraform.
- [ ] Archive service after domain deletion. 

# QA

- [x] The service DNS configuration is delete from AWS production env.
- [ ] The service is archived within the admin application.

# Resources

# Triggers / Schedule

Once

**Comment by ben851** [comment]
Merged to main, to be released.

**Comment by ben851** [comment]
Ready to be released today.

**Comment by jimleroyer** [comment]
I verified that the service DNS entry was removed in the AWS dashboard. Hence I complete the related QA item around this.

We need to archive the service now. I will take possession of this card and put it back to in progress.

**Comment by P0NDER0SA** [comment]
Jimmy deleted it this morning.  Pond is gonna QA
