### ISSUE TITLE
ADR for Kubernetes Secrets management

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#451]
# Description

As a developer of notify I want to have good documentation on how we implement secrets within Kubernetes so that the team can fully understand the process in managing secrets.

## WHY are we building?

Align with K8s best practices
Document how to manage secrets within Notfiy

## WHAT are we building?

ADR describing the process for managing secrets

## VALUE created by our solution

Improved secrets management
Improved security
Improved team cohesion

# Acceptance Criteria

- [ ] Process is documented
- [ ] ADR has been reviewed and approved by notify team.

**Comment by ben851** [comment]
ADR in progress, here's the PR
https://github.com/cds-snc/ADR/pull/23

**Comment by ben851** [comment]
Draft ADR with 2 options ready for review.

**Comment by P0NDER0SA** [comment]
we will give this until next Thursday to collect any feedback that might be yet to come

**Comment by ben851** [comment]
Security reviewed the ADR and left some notes. Ben to action

**Comment by ben851** [comment]
I added some additional context as per IT Sec's request

**Comment by ben851** [comment]
@Jimmy will review today to approve
