### ISSUE TITLE
Automate the update of Sentinel layers

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#452]
# Description

As a developer of notify, I want our system to automatically update to the latest sentinel lambda image layer so that we don't end up with broken EKS deploys during BCP.

## WHY are we building?

The dev create fails if the sentinel lambda layer is not the latest provided by SRE.

## WHAT are we building?

Implement a method to automate the update of the lambda layer based off of when SRE deploys new versions.

## VALUE created by our solution

BCP readiness

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [x] Sentinel lambda layer is automatically updated (or at least a PR is triggered) based on the SRE release

# QA Steps

- [ ] All Envs create script works consistently when sentinel is updated.

**Comment by ben851** [comment]
Implemented an external data source that executes a script to fetch the latest lambda layer version. Merged to staging.

**Comment by P0NDER0SA** [comment]
Have to check this on Tuesday
