### ISSUE TITLE
Look into VPN Self Signed Certificates with AKID

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#453]
# Description

As a developer of notify, I don't want to spend $400 per environment per month for private certificate authorities. 

## WHY are we building?

AWS deprecated self signed certificates for VPN forcing us to use private certificate authorities. We may have misunderstood however and it may have just been deprecating self signed certs that don't have AKID.

## WHAT are we building?

Look into recreating VPN with AKID self signed cert and see if it still works

## VALUE created by our solution

We don't have to spend $$$ on PCA

# Acceptance Criteria

- [x] VPN works with AKID Self Signed Certs
- [x] We don't have any alerts from AWS
- [x] PCA's are deleted

# QA Steps

- [x] Verify there's no PCAs in the CPN cert
- [x] verify that we can still log into k9s on dev
- [x] Verify there are no warnings in AWS trusted advisor related to the VPN

**Comment by ben851** [comment]
Dev deployed with self signed certs. Waiting a few days to see if we get any alerts from AWS

**Comment by P0NDER0SA** [comment]
We will check this one on Tuesday until after Souvenir day

**Comment by ben851** [comment]
PR to review. 
https://github.com/cds-snc/notification-terraform/pull/1643/

Sat in dev working all last week with no issues

**Comment by ben851** [comment]
Deployed this to staging yesterday, and it works!

**Comment by ben851** [comment]
Released to prod, seems to be working

**Comment by ben851** [comment]
@Pond to QA

**Comment by P0NDER0SA** [comment]
Pond needs QA steps :(

**Comment by pond** [comment]
I don't  know who you intended to reference but it isn't me. I have nothing to do with this project or task. Perhaps you meant @P0NDER0SA ?

**Comment by P0NDER0SA** [comment]
QA'ed!  moving to done.
