### ISSUE TITLE
Move Quicksight to its own release schedule

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#454]
# Description

As a developer of notify I want to schedule quicksight deployments to run overnight so that they don't block the regular release pipeline when doing Terraform releases.

## WHY are we building?

Quicksight releases can be data intensive and cause issues on the production system. This forces us to release quicksight after hours. If there are quicksight changes, this will block any other changes in the system that need to be released including emergency hotfixes. 

## WHAT are we building?

Remove quicksight deploy from TF apply production, create a new github workflow that applies quicksight in prod every night.

## VALUE created by our solution

Increased agility, reliability and lower load on the ops lead.

# Acceptance Criteria

- [x] Quicksight apply removed from TF Prod release pipeline
- [x] A new prod release pipeline with quicksight only deploys based on a cron schedule

# QA Steps

- [x] Verify that quicksight is not part of the TF apply
- [x] Verify that the cron quicksight release fires off successfully.

**Comment by ben851** [comment]
Quicksight release worked

**Comment by sastels** [comment]
Verified from today's release that Quicksight is no longer part of Merge to main (Production).
