### ISSUE TITLE
Move Document Download to Helmfile/AWS Secrets Manager

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#455]
# Description

As a developer of notify, I would like all of our kubernetes deployments to be managed by Helmfile so that all of our kubernetes code is in one location.  I would also like to have all secrets automated from a single source of truth (1pass -> AWS Secrets) and remove our dependency on encrypted .env files

## WHY are we building?

- Provides the ability to deploy dynamic environments
- Provides the ability to run "diff" commands against environments
- Reduces the amount of code that Notify has to manage
- Keeps code DRY

## WHAT are we building?

- [ ] Add Document Download entry to the helmfile
- [ ] source secrets for helmfile from AWS Secrets Manager
- [ ] source configuration values from helmfile overrides where necessary
- [ ] adjust GitHub actions to work with these changes
- [ ] This work is scoped to the DEV environment.

## VALUE created by our solution

- Increased reliability via reduced chance of accidental changes during releases
- Increased velocity due to reduction in maintenance
- better secrets management that falls in line with our OKRs

# Acceptance Criteria

- [x] Notify Document Download are deployed and managed with helmfile
- [x] All secrets required by Document Download are sourced from 1pass -> terraform -> aws secrets manager and accessed using a kubernetes secret
- [x] Notify Document Download still works

# Not in scope

- [ ] Deployment in staging and production: we should only deploy to dev until we figure out the deployment steps.

# QA Steps

- [ ] Smoke test documentation

**Comment by P0NDER0SA** [comment]
Work was merged here -- Moving this card to review for @ben851 to do a QA Pass
cds-snc/notification-manifests#3084

**Comment by ben851** [comment]
Quick PR to fix a small issue, otherwise QA OK
https://github.com/cds-snc/notification-manifests/pull/3113

**Comment by P0NDER0SA** [comment]
Merged. Moving to QA

**Comment by sastels** [comment]
Ben QA'd yesterday - will leave it here till he's back to sign off.
