### ISSUE TITLE
[CHORE] Upgrade K8s nodes to 1.31.0-20241109

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#456]
# What

Upgrade k8s nodes to latest AMI 1.31.0-20241109

# Why

Security patching

# Acceptance Criteria

-[ ] Smoke test in staging, staging good for 24 hrs

# QA

- [ ] Verify that the nodes are upgraded
# Resources

# Triggers / Schedule

Describe the schedule or trigger for this chore. When should it be done?

- [ ] List any resources associated with this chore (ex. K8s release notes, AWS AMI changes)

**Comment by ben851** [comment]
PR for production
https://github.com/cds-snc/notification-terraform/pull/1659

**Comment by sastels** [comment]
Pond will verify that the correct version is deployed

**Comment by P0NDER0SA** [comment]
Pond! Has! QA'ed!!
