### ISSUE TITLE
Upgrading New Relic Python agent past v8.10 on API causes crash loop in K8s

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#458]
## Describe the bug 

Upgrading past New Relic v8.10.0+ leads to the Kubernetes pods to get into a crash loop.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 

SEV-2 - Slower bootup -- potentially infinite deployment crash loop

## To Reproduce

Upgrade New Relic with version 8.10.1+. Observe deployment failures leading to continual crash loop.

## Expected behavior

New Relic can be upgraded to a more recent version than 8.10.1 without issues.

## Impact

We are stuck with New Relic 8.10 for the time being and that might prevent us from upgrading Python, and monitoring our systems with latest New Relic features. The Python agent version might get outdated and lead to troubles as well. If we upgrade without fixing the issue, then we get a slower deployment time for our k8s pods and that potentially leads to instability with these. 

If applicable

Impact on Notify users:

Impact on Recipients:

Impact on Notify team: 

## QA

- [x] Verify that New Relic has been upgraded to latest version (or after 8.10+).
- [x] Verify that the API pods can deploy with no issues with the upgraded New Relic, avoiding the potential deployment crash loop.

## Additional context

See issue #313 which led the investigation to the root cause of the New Relic python agent performance issues.

**Comment by jimleroyer** [comment]
PR to add a CloudWatch Logs Insights query to track Gunicorn total running time in API:
https://github.com/cds-snc/notification-terraform/pull/1665

**Comment by jimleroyer** [comment]
The admin was upgraded to latest New Relic Python agent v10.3.0. Ready to get QA'ed and deployed in production.

**Comment by sastels** [comment]
new api pods deployed on prod,
```
# pip list | grep relic
newrelic                    10.3.0
```
