### ISSUE TITLE
Embiggen Redis Cluster

### ISSUE THREAD

**Issue by jzbahrai** [cds-snc/notification-planning-core#46]
# Description

As a sysops of GCNotify,
I want Redis to have enough memory to operate under stress load,
So that the system does not crash,
As Redis contains buffer queues that are important for normal operation of GCNotify.

As a user we will be using the Redis Instance more with the addition of keys due to bounce rate. Currently the redis instance uses 500mb of a 1gb Redis instance. 

## Why

We do not want GCNotify to crash on bigger loads that will increase Redis memory and get an out of memory error.

## How

Embiggen the Redis cluster to bigger instances.

## Value

Reliability.

# Acceptance Criteria:

- [ ] Upgrade Redis to a larger size

# QA Steps

- [ ] Run a performance test on the redis cluster to ensure it can handle larger amounts of reads and writes.

**Comment by sastels** [comment]
It's probably either a quick change or a "ok we have to do some sort of redis migration to a new instance like we did before" - be good to quickly sort out which of these it will be sooner rather than later.

**Comment by sastels** [comment]
[Started a PR to investigate upgrading](https://github.com/cds-snc/notification-terraform/pull/716). Terraform plan says it will change in place, but should investigate if there is downtime or not.

**Comment by sastels** [comment]
https://aws.amazon.com/blogs/aws/elasticache-for-redis-update-upgrade-engines-and-scale-up/
> You can now scale up to a larger node type while ElastiCache preserves (on a best-effort basis) your stored information. While ElastiCache for Redis has always allowed you to upgrade the engine version, you can now do so while preserving the stored information. You can apply both changes immediately or during the cluster’s maintenance window.
>
>Behind the scenes, ElastiCache for Redis uses several different strategies to scale up and to upgrade engines. Scaling is based on Redis replication. Engine upgrades use a foreground snapshot (SAVE) when Multi-AZ is turned off, and replication followed by a DNS switch when it is on.

We're multi-az so sounds like it'll just swap the new ones in without data loss or downtime? hopeful.

**Comment by jimleroyer** [comment]
@smcmurtry [ran an analysis of the projected memory usage](https://github.com/cds-snc/notification-attic/pull/31) once bounce rate comes in. He estimated that 500K would take approx. 50M. We have a production limit of 2M emails at the moment so the bounce rate would be 200M of Redis memory maximum, based on these projections.

We should be good for now with the 500M Redis memory instance.

**Comment by jimleroyer** [comment]
Let's monitor redis usage when the bounce rate feature will hit production 100%. Then we can consider this card done / archived.

**Comment by ben851** [comment]
Bounce rate release happening today at 9:30 and we will review the monitoring

**Comment by jimleroyer** [comment]
The bounce rate feature release was delayed. It will come up more gradually under an A/B test.

**Comment by jimleroyer** [comment]
The bounce rate feature has been released. The Redis memory so far only takes up to 10% max. I will wait a bit more before closing this, to monitor big activity. We'll have such an event tomorrow morning with a send of 250K.

**Comment by ben851** [comment]
* We have verified that at its busiest over the past week, redis was only using 19% memory
* We have memory and cpu performance warnings for the redis db

**Comment by ben851** [comment]
* alerts released to staging
* @ben851 to QA 
    * Check rds log retention period
    * Check that alerts are in staging

**Comment by ben851** [comment]
Verified that log retention period is in the rds parameter group and that the alerts are in cloudwatch.
