### ISSUE TITLE
Add New Relic to DD-API

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#460]
# Description

As a sysops,
I want to monitor the DD-API application with New Relic,
So I have a holistic view of the system.

## WHY are we building?

Add the dd-api component to New Relic to have a complete picture of our system.

## WHAT are we building?

Add New Relic Python agent to the dd-api component.

## VALUE created by our solution

Observability and reliability.

# Acceptance Criteria

- [x] DD-API reports back to New Relic in staging.
- [ ] DD-API reports back to New Relic in production. 

# QA Steps

- [x] Look into New Relic for DD-API in both staging and prod environments.

**Comment by jimleroyer** [comment]
PR to add New Relic to DD-API:
https://github.com/cds-snc/notification-document-download-api/pull/201

**Comment by jimleroyer** [comment]
I have to check for new env variables for DD-API regarding New Relic.

**Comment by jimleroyer** [comment]
The DD-API entity is not present in New Relic for the staging environment.

<img width="1271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVR2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bca97b9e02fd65c6441c7c61f1cabd97666afb05/image.png" alt="image.png" />

**Comment by ben851** [comment]
I see DD api in staging and prod in NR
