### ISSUE TITLE
Upgrade admin to Python 3.12

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#463]
# Description

As a software developer working on GCNotify stack,
I want the Python stack to be upgraded at latest supported version,
So that I can leverage the latest features of the language and better/safer code.

As a system ops working on GCNotify stack,
I want the Python stack to be upgraded at latest supported version,
So that I can leverage the latest performance improvement
And process notifications faster.

## WHY are we building?

To get latest performance improvements, features and security updates of the Python language/runtime.

## WHAT are we building?

Upgrade the stack to the latest possible version of Python. A few considerations:

* It is possible that we cannot upgrade to the latest of the latest (3.12 at the time of this writing for the stable version), as this might be blocked by a dependency library that did not release a version supporting the latest. For example, we might have to upgrade from version 3.10 to version 3.11, and wait a bit longer to migrate to version 3.12.
* The lambdas might have additional considerations that might limit the possible maximum Python version we can use, such as supported runtime and also monitoring libraries that need to support that environment (such as New Relic). Consider doing this work in #354 .

## VALUE created by our solution

Better performance, security and reliability.

# Acceptance Criteria

- [x] Admin running on Python 3.12.
- [x] test locally
- [x] test on dev
- [x] document in tricks and tips how we can deploy branches to dev

# QA Steps

- [ ] poke around in admin

**Comment by sastels** [comment]
Upgraded to 3.12.7
https://github.com/cds-snc/notification-admin/pull/1996

**Comment by sastels** [comment]
Working locally (devcontainer) with other apps.

**Comment by sastels** [comment]
Ready for review
cds-snc/notification-admin#1996

**Comment by P0NDER0SA** [comment]
Pond will review

**Comment by P0NDER0SA** [comment]
Looks ok!  Steve can merge this and move to QA

**Comment by sastels** [comment]
in staging, looks good

**Comment by P0NDER0SA** [comment]
QA'ed!!
