### ISSUE TITLE
When Freshdesk is down, failover to helpdesk@cds-snc.ca

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#47]
# Description

As an support of GCNotify,
I still want to receive tickets from users if Freshdesk is down,
So that I don't miss any support that we need to deliver.

## WHY are we building?

More reliability of our support process within GCNotify.

## WHAT are we building?

Redirect the support ticket to a Google user group as a fallback.

## VALUE created by our solution

Fault tolerance, reliability, better support.

# Acceptance Criteria

- [x] The support tickets are redirected to the helpdesk@cds-snc.ca Google group when Freshdesk is down.

# QA Steps

- [ ] Break Freshdesk connectivity somehow and send a ticket to see if the support ticket is sent to the Google user group.
- [ ] Also look for log statements when the ticket is redirected `Emailing contact us form to...`.

**Comment by jimleroyer** [comment]
* Steve to merge into staging.

**Comment by sastels** [comment]
merged!
