### ISSUE TITLE
bug-bogue - New Relic Lambda permissions are not in Terraform

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#49]
## Describe the bug 

When deploying to a new environmment, the new relic lambda integration fails with a 403. This is because the required permissions for the new relic layer to send telemetry to new relic are not in the infrastructure as code. 

## [Bug Severity]
SEV-3

## To Reproduce

1. Deploy the notification-terraform to a new AWS account. The lambda function will fail with New Relic 403 errors.

## Expected behavior

Lambda telemetry should be sent to new relic without any click ops or manual intervention.

## Impact

Impact on Notify users:
None

Impact on Recipients:
None

Impact on Notify team: 
This will affect Disaster Recovery and troubleshooting in new environmments.

**Comment by ben851** [comment]
These are the permissions that must be added to the lambda iam tf:
  statement {
    effect = "Allow"
    actions = [
      "cloudwatch:GetMetricStatistics",
      "cloudwatch:ListMetrics",
      "cloudwatch:GetMetricData",
      "config:BatchGetResourceConfig",
      "config:ListDiscoveredResources",
      "tag:GetResources",
      "lambda:GetAccountSettings",
      "lambda:ListFunctions",
      "lambda:ListAliases",
      "lambda:ListTags",
      "lambda:ListEventSourceMappings"
    ]
    resources = ["*"]
  }

**Comment by jimleroyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-Core-6411dfb7c95fb80014e0cab0/issues/cds-snc/notification-planning-core/49?planning-poker) with Zenhub @ben851 @sastels

**Comment by jimleroyer** [comment]
That was pushed to production and didn't break anything. Ben to verify / QA.

**Comment by ben851** [comment]
I can verify that the permissions are now set in production and staging, and that we are still receiving data in new relic for the lambda functions.
