### ISSUE TITLE
Refactor Smoke Tests to reduce SMS spending

### ISSUE THREAD

**Issue by whabanks** [cds-snc/notification-planning-core#53]
Currently our smoke tests send 6 SMS messages per run. We could reduce this to 1  to reduce costs in AWS. As the team expands, development ramps up, and more PRs are created in a given month so will the SMS costs of running smoke tests as they are usually run along side most PRs.

[Link to the discussion that prompted this initiative](https://gcdigital.slack.com/archives/CV38DBNVA/p1680032618325889).

**Comment by sastels** [comment]
Smoke tests now use the internal test number that doesn't actually send.
