### ISSUE TITLE
Write an ADR to decide what is the hard limit for sending per second

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#54]
# Description

Depending on how many k8s pods we have, we need to determine sending rate per pod to improve reliability of emails/sms.

We need to cover horizontal scaling as well with the celery workers setup in Kubernetes. We can look into solutions on how to have fixed sending rate on GCNotify side.

This should align with the rate per second of AWS calls we can make to SES.

## WHY are we building?

Properly assess our current requirements, constraints and how to get past these.

## WHAT are we building?

Build documentation on our current challenge for future selves.

## VALUE created by our solution

Community/team review and alignment. Determine how to deal with sending rates in the future.

# Acceptance Criteria** (Definition of done) 

- [x] ADR written and reviewed.
- [x] Run performance test in staging and test the limits.
- [x] Test the AWS limits and see how sensitive these are.

**Comment by sastels** [comment]
Added an "internal test" email address that will go though the system right to the end, and then **not** get sent to SES. This will allow us to test how many notifications Notify can push through our system per minute.
https://github.com/cds-snc/notification-api/pull/1911

**Comment by sastels** [comment]
start of adr
https://github.com/cds-snc/notification-adr/pull/44

**Comment by sastels** [comment]
moving back to Prioritized while I'm on support this week...

**Comment by sastels** [comment]
...and now back to In Progress!

**Comment by sastels** [comment]
[add statsd around send_email() and send_sms()](https://github.com/cds-snc/notification-api/pull/1926)

**Comment by sastels** [comment]
ran a load test and added graphs and conclusions to the [ADR](https://github.com/cds-snc/notification-adr/pull/44)

**Comment by jimleroyer** [comment]
I will review the ADR today and polish if necessary.

**Comment by sastels** [comment]
Steve to review and followup.

**Comment by sastels** [comment]
Hope / plan is to finish this ADR by the end of the week

**Comment by ben851** [comment]
Need to integrate perf test results into ADR.

**Comment by ben851** [comment]
Perf Test Results to Integrate

https://docs.google.com/spreadsheets/d/1bAoaO8YDRHq_J158e3y6sxGTNltHPg-QQSvVBTeGcVQ/edit#gid=0

**Comment by sastels** [comment]
Demo talk on scaling so far
https://docs.google.com/presentation/d/1uM5CF2pwi3JhBGW3iP8DqToioHibfnFI08MHf30442w

**Comment by jimleroyer** [comment]
Jimmy to investigate the performance drop, identify time ranges and correlate with performance test results.

**Comment by jimleroyer** [comment]
A graph of response time and sending email time was produced:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHhFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d0f53f88f8f13b522ee528fce18eb5a1178a1276/image.png)

The source code will be uploaded in a PR for the attic. 

Investigation of the commits that might have introduced the performance gap will persue with local tests. I will check for the commits on May 5th, 2022 to begin with.

**Comment by jimleroyer** [comment]
I installed both API and Admin from back around May 5th. I will run the stress tests locally while advancing the commits to see if any of these indicate a performance drop.

**Comment by jimleroyer** [comment]
Jimmy to include the investigation results in the ADR. Let's see if we can merge current state in main, and re-open a new PR for polishing afterward.

**Comment by sastels** [comment]
Jimmy still investigating

**Comment by sastels** [comment]
blocked until the investigation is done

**Comment by jimleroyer** [comment]
We should review the ADR one more time with the goal of merging. 

Create new cards for:

1. Investigating the performance drop that we noticed.
1. Have a reference google doc on current limits that the team and management can refer to.

**Comment by jimleroyer** [comment]
I apparently created the issue for #2 last week, i.e, *reference google doc on current limits that the team and management can refer to*:
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/320

And we have #1 covered with #178.

**Comment by ben851** [comment]
Jimmy to do one last pass on reviewing this

**Comment by sastels** [comment]
Steve will read and reply to Jimmy's comments!

**Comment by sastels** [comment]
Filled in some of the missing info. Still a bit to do.

**Comment by jimleroyer** [comment]
Steve to update the tasks table today and a cleanup.

**Comment by jimleroyer** [comment]
The ADR work was implemented and we reached our targets. I just merged the ADR and will create subsequent tasks listed in it that was not implemented and still worth it.
