### ISSUE TITLE
Add logging around "No row was found" errors

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#57]
## Describe the bug 

We get a lot of "no row was round when one was required" errors. This happens when we do a database query for an id that does not exist (so the query succeeds with an empty result), then we say "give me one of them" and there isn't any.

There are several places where this can occur. We should add more logging to help determine why. If it's as a result of a user querying the status of a notification that doesn't exist yet, we should also send back a better error message.

According to [stackoverflow](https://stackoverflow.com/questions/24985989/check-if-one-is-empty-sqlalchemy) we could use `.first()` instead of `.one()` in the code. `first()` does not raise an error when there were no results, rather it returns `None` that we could handle better.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4

### Scenario 1:

1. make up a notification id uuid and check for the status of this non existant uuid.

### Scenario 2:
1. Login to admin
2. Go to a service you have access to
3. Navigate to a non-existent job:
    - `/service/{your-service-id}/job/2xxx7870-68xa-4x07-a8xb-73x595x10555`
4.  User receives error page
## Expected behavior
- User should get a page saying job not ready or does not exist

## Impact

confusion for us and system users

**Comment by jimleroyer** [comment]
* Steve worked on it and opened a PR.

**Comment by sastels** [comment]
merged to staging
