### ISSUE TITLE
Review existing alarms that has no treat_missing_data as ignore

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#59]
# Description

As a Notify dev, I need to have our alarms Slack channel not cluttered with irrelevant messages

## WHY are we building?

- some critical alarms trigger an "OK" in slack when they move from no data to ok.

## WHAT are we building?

- Review alarms that will not ignore a breach of data and make a list out of it.
- Eventually, add `treat_missing_data  = "notBreaching"` to more alarms after review

## VALUE created by our solution

- less noise in the #notification-ops channel

## Acceptance Criteria

- [x] Make a list of alarms that do not set 'treat_missing_data`
- [x] Review the list with the team.
- [x] (Optional) Configure the alarms in TF during a meeting.

## QA Steps

- [x] We have a list to review!
- [x] no more OK messages when going from INSUFFICIENT_DATA -> OK

**Comment by sastels** [comment]
Question: are there any alarms that we **don't** want `treat_missing_data = "notBreaching"` ?

**Comment by sastels** [comment]
Alarms without treat_missing_data

resource "aws_cloudwatch_metric_alarm" "ses-bounce-rate-warning" {
resource "aws_cloudwatch_metric_alarm" "ses-bounce-rate-critical" {
resource "aws_cloudwatch_metric_alarm" "ses-complaint-rate-warning" {
resource "aws_cloudwatch_metric_alarm" "ses-complaint-rate-critical" {

resource "aws_cloudwatch_metric_alarm" "sqs-sms-stuck-in-queue-warning" {
resource "aws_cloudwatch_metric_alarm" "sqs-sms-stuck-in-queue-critical" {
resource "aws_cloudwatch_metric_alarm" "sqs-throttled-sms-stuck-in-queue-warning" {
resource "aws_cloudwatch_metric_alarm" "sqs-throttled-sms-stuck-in-queue-critical" {

resource "aws_cloudwatch_metric_alarm" "sqs-priority-queue-delay-warning" {
resource "aws_cloudwatch_metric_alarm" "sqs-priority-queue-delay-critical" {
resource "aws_cloudwatch_metric_alarm" "sqs-email-queue-delay-warning" {
resource "aws_cloudwatch_metric_alarm" "sqs-email-queue-delay-critical" {
resource "aws_cloudwatch_metric_alarm" "sqs-bulk-queue-delay-warning" {
resource "aws_cloudwatch_metric_alarm" "sqs-bulk-queue-delay-critical" {

resource "aws_cloudwatch_metric_alarm" "sqs-send-throttled-sms-tasks-receive-rate-warning" {

resource "aws_cloudwatch_metric_alarm" "document-download-bucket-size-warning" {
resource "aws_cloudwatch_metric_alarm" "scan-files-document-download-bucket-size-warning" {

resource "aws_cloudwatch_metric_alarm" "admin-pods-high-cpu-warning" {
resource "aws_cloudwatch_metric_alarm" "api-pods-high-cpu-warning" {
resource "aws_cloudwatch_metric_alarm" "celery-pods-high-cpu-warning" {
resource "aws_cloudwatch_metric_alarm" "celery-sms-pods-high-cpu-warning" {

resource "aws_cloudwatch_metric_alarm" "admin-pods-high-memory-warning" {
resource "aws_cloudwatch_metric_alarm" "api-pods-high-memory-warning" {
resource "aws_cloudwatch_metric_alarm" "celery-pods-high-memory-warning" {
resource "aws_cloudwatch_metric_alarm" "celery-sms-pods-high-memory-warning" {

resource "aws_cloudwatch_metric_alarm" "redis-elasticache-high-db-memory-warning" {
resource "aws_cloudwatch_metric_alarm" "redis-elasticache-high-connection-warning" {

resource "aws_cloudwatch_metric_alarm" "lambda-ses-delivery-receipts-errors-warning" {
resource "aws_cloudwatch_metric_alarm" "lambda-ses-delivery-receipts-errors-critical" {



Not that
resource "aws_cloudwatch_metric_alarm" "redis-elasticache-medium-cpu-warning" {
has set to breaching


Recently these have popped up INSUFFICIENT_DATA -> OK on #notification-ops for

sqs-priority-queue-delay-critical
lambda-image-sns-delivery-receipts-errors-warning
lambda-image-sns-delivery-receipts-errors-critical (several times)
lambda-ses-delivery-receipts-errors-warning

**Comment by jimleroyer** [comment]
PR to bring changes after team review:
https://github.com/cds-snc/notification-terraform/pull/712/files

**Comment by jimleroyer** [comment]
This was approved; let's merge in staging after today's release to test it in staging for a day.
