### ISSUE TITLE
Notify services should continue to work on Kubernetes v1.24+ once Dockershim has been removed

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning-core#6]
## Description

As a developer,
I want to confirm that AWS EKS dropping support for `Dockershim` does not impact Notify,
so we don't have service instability when we upgrade to AWS EKS 1.24.

## Acceptance Criteria** (Definition of done) 

- [x] All Notify services checked to ensure they do not rely on `Dockershim`.
- [x] All GitHub workflows checked to ensure they do not rely on `Docker` runtime on the EKS worker nodes.
- [x] All supporting project scripts checked to ensure they do not rely on `Docker` runtime on the EKS worker nodes.

## Additional context
* [Check if dockershim deprecation affects you](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you/)
* [Dockershim FAQ](https://kubernetes.io/blog/2022/02/17/dockershim-faq/)
* [AWS dockershim deprecation](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html)

**Comment by sastels** [comment]
AWS is going to upgrade this on us if we don't

>"Amazon EKS has deprecated Kubernetes version 1.22 and this version will no longer be supported on June 4, 2023. Starting that day, you will no longer be able to create new 1.22 clusters, and all EKS clusters running Kubernetes version 1.22 will be updated to the latest available platform version of Kubernetes version 1.23."

**Comment by sastels** [comment]
@patheard Have we heard any more about a replacement for `amazon-cloudwatch`? Is this still blocking us from upgrading k8s?

**Comment by sastels** [comment]
Also, on staging I now get
```
$ kubectl dds

NAMESPACE		TYPE		NAME			STATUS
amazon-cloudwatch	daemonset	cloudwatch-agent	mounted
kube-system		daemonset	aws-node		mounted
```

**Comment by sastels** [comment]
1.23 still supports dockershim and End of Support is October 11, 2023. Going to this will likely be easier and buy us some more time.

**Comment by patheard** [comment]
No updates yet. I'd try updating to Fluent Bit and then opening a support case about the `aws-node` dependency on Docker.

**Comment by jimleroyer** [comment]
@ben851 to maybe take this task today - spin a AWS scratch account and proceed with the upgrade in there.

**Comment by ben851** [comment]
I verified that everything runs correctly in K8s v1.23 using my scratch account.

**Comment by ben851** [comment]
* PR for CW Agent in prod is open and approved - will release today
* HPA conversion is in staging, and can be pushed to prod today as well.
