### ISSUE TITLE
Inform of available Postgresql database upgrade in Slack

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning-core#64]
# Description

As an ops lead,
I would like to know if there are database upgrades available
and should get reminded when I know but let it slide,
So that I can bring the latest database version to the product.

## WHY are we building?

Reminding ourselves that we have important db upgrade to perform.

## WHAT are we building?

A slack notification to the #notify-dev channel for reporting the latest database version available, very similar to the [GitHub action we have for Kubernetes cluster upgrade check](https://github.com/cds-snc/notification-terraform/blob/62318dfe0afe128362da2658e4974fc1f169b92a/.github/workflows/check_eks_cluster_update.yml).

## VALUE created by our solution

Aware of latest version and get ourselves accountable.

# Acceptance Criteria

- [x] A Slack notification informs us every Monday of latest database upgrade.

# QA Steps

- [x] Run and observe the Slack notification in the #notify-dev Slack channel.

# 🚩🚩🚩

1. If we move directly to Aurora, and they manage upgrades for us, this task would be rendered obsolete.
1. We need a command to know the database versions. Quick googling (not tested) would return: 

```
aws rds describe-db-engine-versions --engine postgres --query 'DBEngineVersions[*].ValidUpgradeTarget[*].{EngineVersion:EngineVersion}' --output text --region ca-central-1
```

**Comment by patheard** [comment]
Fix is working as expected now 🎉 

Here's an example of the database update message:
https://gcdigital.slack.com/archives/CV38DBNVA/p1697461550755139
