### ISSUE TITLE
upgrade terraform aws provider

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#71]
# Description

As a Notify dev, I need to use recent terraform features

## WHY are we building?

- We are currently using [aws provider version 3.0](https://github.com/cds-snc/notification-terraform/blob/58e3c892f9221f45a220da79013952a5555342f6/env/terragrunt.hcl#L27)
- as of 4.62 terraform has started building up support for QuickSight
- we want to set up QuickSight for Notify
- terraform would be the best way to do this

## WHAT are we building?

upgrade our aws provider to 4.62.0 or whatever's the most recent. See the [upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade).

## VALUE created by our solution

Can setup QuickSight in terraform later

# Acceptance Criteria

- [ ] We are using the 4.62 aws provider
- [ ] everything applied and working on staging 

# QA Steps

- [ ] Prod is working fine

**Comment by ben851** [comment]
* TF Provider updated to 4.0 in both staging and production.

**Comment by jimleroyer** [comment]
Terragrunt version and plan should spit out the version to do QA on this one.

**Comment by sastels** [comment]
Verified that we are now using 4.64.0
