### ISSUE TITLE
Tune celery workers to increase SMS send rate

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#79]
## Description

As an owner of Notify, I need to be able to know how capable Notify is at sending SMS so that I can scale the system appropriately.

- we switched from using AWS shared pool to our own dedicated pool.
- in theory, we should have the same send rate / latency as before (10 message parts / sec, a few seconds of latency)
- we should test this
- we don't have a global celery throttle, rather we have throttles on the individual workers.
- one idea: could we just use one celery worker dedicated to SMS so we just have to throttle that one?

## Acceptance Criteria (Definition of done) 

- [x] we know how to scale our resources to double our send rate

## QA Steps

- [x] Verify that the scaled system yields the desired results

**Comment by sastels** [comment]
If we're going to move sms to its own celery pods then they'll need to be on their own queues. [Looking at a week of prod data from 8/2/2023 to 8/9/2023](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-604800~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20log*2c*20kubernetes.labels.app*20as*20app*2c*20kubernetes.pod_name*20as*20pod_name*2c*20*40logStream*0a*7c*20filter*20pod_name*20like*20*2f*5ecelery*2f*0a*7c*20filter*20log*20like*20*2fqueue*20for*20delivery*2f*0a*7c*20filter*20log*20like*20*2fsms*20*2f*0a*7c*20filter*20log*20not*20like*20*2fsend-throttled-sms-tasks*2f*0a*7c*20parse*20log*20*2f.*2asent*20to*20the*20*28*3f*3cqueue*3e.*2a*29*20queue*20for*20delivery*2f*0a*7c*20stats*20count*28*2a*29*20as*20total*20by*20queue*0a~queryId~'db015112-c736-4ec6-831a-1de9f9528f41~source~(~'*2faws*2fcontainerinsights*2fnotification-canada-ca-production-eks-cluster*2fapplication))) we see the following queues used to run `deliver_sms`:

| queue | total |
| --- | --- |
| priority-tasks | 19497 |
| send-sms-tasks | 12784 |
| research-mode-tasks | 21 |
| bulk-tasks | 30 |


We could map those queues to new sms queues (perhaps leaving research-mode-tasks alone)

**Comment by sastels** [comment]
SMS now rate limited differently on staging (10/s) and prod (1/2). Will run some tests to see how the pods scale using the internal test number.

**Comment by sastels** [comment]
provisioned 30 more phone numbers, so the AWS send rate limit is now 50 fragments / second.

**Comment by sastels** [comment]
scaled staging to 40 celery, 20 sms-send pods, tested.
Next step is to [deploy this to prod](https://github.com/cds-snc/notification-manifests/pull/2071).

Note that we'll need to first put celery back on karpenter pods.

**Comment by jimleroyer** [comment]
More load testing on the way to stress the staging environment.

**Comment by sastels** [comment]
[Tested with 200K emails, 30K SMS](https://gcdigital.slack.com/archives/C05K8349YCR/p1696949717368499).
- send rates roughly as expected
- had to redeploy celery part way through to fix CWAgent bug

[Tested again Wednesday](https://gcdigital.slack.com/archives/C05K8349YCR/p1697044944531829), this time the CWAgent errors were fixed. send rates as expected, no stalled messages.

**Comment by sastels** [comment]
Can merge
cds-snc/notification-manifests#2071
whenever celery is back in karpenter and scaling again.

**Comment by jimleroyer** [comment]
Karpenter is back in production! But let's give it a few days to make sure this is stable.

**Comment by sastels** [comment]
ready to bump sms pods up to 20 max. works in staging, will release to prod likely today.
