### ISSUE TITLE
Update Elasticache Cluster

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#84]
# Description

As a developer/operator of Notify, I would like to ensure that our infrastructure is up to date with latest patching, and that AWS is not forcefully putting updates in. 

## WHY are we building?

AWS Reached out to let us know that they are going to automatically apply a cluster update because we are passed the grace period.

## WHAT are we building?

Patching elasticache in staging and production

## VALUE created by our solution

A better, more secure GC Notify

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] Elasticache cluster upgrade works in staging and production with no downtime

# QA Steps

- [ ] Verify in staging before releasing to production

**Comment by ben851** [comment]
Hello,
This is to notify you that the “recommended apply by date” for ElastiCache update elasticache-20230315-001 applicable to your one or more clusters is now past due. You can still apply the update to the applicable clusters. However, if you do not take any action, ElastiCache will schedule to auto-apply the update in your clusters’ upcoming maintenance windows. You will receive a separate notification with actual date and time of the auto-update schedule per cluster.
For more information on such updates including risk assessment, cluster impact analysis and whether to apply them or not, see ElastiCache Service Updates FAQs https://aws.amazon.com/elasticache/elasticache-maintenance/.
To get started click here https://console.aws.amazon.com/elasticache/home?region=ca-central-1#service-updates:aws. You can also use AWS CLI or ElastiCache API instead. For more information, see our public documentation on ElastiCache Software Updates https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Self-Service-Updates.html.
If you have any questions or concerns, please contact the AWS Support Team at http://aws.amazon.com/support.
Sincerely,
Amazon Web Services
Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210.

**Comment by jimleroyer** [comment]
* Upgraded the Redis cluster in the staging environment. 
* Will upgrade production tomorrow morning.
