### ISSUE TITLE
Fix existing tag on our infrastructure in AWS

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#9]
It is CDS standard to tag each resource (created by terraform) with something like
```
Terraform = true
CostCentre = "notification-canada-ca-${var.env}"
```
(see https://github.com/cds-snc/opa_checks/blob/main/aws_terraform/tags.rego)

We recently added a CI test that will check for these if a module is changed

https://github.com/cds-snc/notification-terraform/pull/331

We should do a pass through Notify's modules and verify that these tags are set.

Note that many of our modules are tagged with `CostCenter` (rather than `CostCentre`) oddly enough.

**Comment by jimleroyer** [comment]
Seems like a duplicate of 
https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/38

**Comment by sastels** [comment]
as discussed IRL we tweaked [#38](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/38) to just be concerned with automatically tagging resources on creation.

**Comment by sastels** [comment]
Closing as this will be done as part of [Improve the AWS tagging in Terraform](https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/38), since when we can implement default tagging they will be applied to existing resources as well as new ones.
