### ISSUE TITLE
Add last_used_date to lifecycle ignore in Terraform for IAM roles

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#90]
# Description

As a developer/operator of GC Notify, I would like my terraform plan/apply outputs to be as clean as possible.

## WHY are we building?

Cleaner outputs allow us to better identify issues and increase agility.

## WHAT are we building?

Add lifecycle ignore last used date to IAM roles in Terraform

## VALUE created by our solution

Cleaner code, better traceability, and increased agility

# Acceptance Criteria

Given some context, when (X) action occurs, then (Y) outcome is achieved.

- [ ] Terragrunt plan/apply suppresses date used outside changes

# QA Steps

- [ ] Tested in staging

**Comment by P0NDER0SA** [comment]
going to verify if this was done, or do this with our BCP work.

**Comment by ben851** [comment]
We did not come across this at all in the BCP on initial run through. 
We should run a plan in every folder and see what changes are shown to verify.

**Comment by ben851** [comment]
We went through the plan on all TF steps after creation and did not come across this. Moving to resolved.
