### ISSUE TITLE
Polish the next steps section in the secrets ADR.

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#91]
# Description

As a Notify dev, I need to document ways to improve our secrets management.

## WHY are we building?

Document potential secrets management improvements that we noticed during our secrets rotation but were considered out of scope.

## WHAT are we building?

Documentation of ways to improve our secrets management.

## VALUE created by our solution

We have ideas for improvements that we can pick up in the future.

# Acceptance Criteria

- [ ] Information added to the secrets ADR.

# QA Steps

- [ ] Additions make sense.

**Comment by sastels** [comment]
Edited the[ Next steps](https://docs.google.com/document/d/1RXlbgIlYzVY5DMWix81vIZluTp-FBLMz8HCYi-v7I7s/edit#heading=h.4p2n7e1nrep9) section of the Secrets ADR to reflect the impact of moving to Vault.

**Comment by ben851** [comment]
@ben851 to review

**Comment by ben851** [comment]
Reviewed and looks good.
