### ISSUE TITLE
Update S3 log buckets to SRE Terraform Modules

### ISSUE THREAD

**Issue by ben851** [cds-snc/notification-planning-core#92]
# Description

As a developer/operator of GC Notify, I want to simplify my deployments while also aligning to GoC security requirements. 

## WHY are we building?

AWS has modified how S3 buckets are created in terraform, and the existing log bucket declarations no longer work when creating new resources. In order to build environments from scratch, they must be migrated to the new deployment model. Rather than doing this manually, we can leverage the CDS SRE terraform modules for S3 log buckets that automatically configure and manage the security settings for the buckets.

## WHAT are we building?

[Change all references to s3 log buckets to the s3 log bucket module.](https://github.com/cds-snc/terraform-modules/tree/main/S3_log_bucket)

## VALUE created by our solution

We will be better aligned with security controls for GoC, and be able to create new environments dynamically.

# Acceptance Criteria

- [x] All s3 log buckets are migrated to the s3 log bucket module
- [x] Existing log data is not affected
- [x] Log data continues to be sent to these buckets after the apply

# QA Steps

- [x] Verify logs are still being stored after apply

**Comment by ben851** [comment]
* Deployed to staging, testing to ensure that logs are still being sent.

**Comment by ben851** [comment]
#### Staging:
* Verified document download logs are still being sent to s3
* Verified athena logs are still being sent to s3
* Verified bulk send logs are still being sent to s3
* Verified csv upload logs are still being sent to s3

**Comment by ben851** [comment]
#### Production:

* State file synchronized. Changes will be applied on next infra release.

**Comment by jimleroyer** [comment]
Just need to release the changes in production.

**Comment by jimleroyer** [comment]
@sastels to do QA and verify the buckets.

**Comment by sastels** [comment]
Verified log buckets in production contain both old and new logs
