### ISSUE TITLE
Resigning data at rest when SECRET_KEY changes

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning-core#96]
# Description

As a Notify developer, I need to be able to easily rotate our signing key

## WHY are we building?

Need to be able to rotate our signing key without downtime

## WHAT are we building?

Code to allow the signing key to be rotated and any signed database fields resigned.

## VALUE created by our solution

Can rotate the signing key without downtime

# Acceptance Criteria

- [ ] We are following the [best practices recommended by the itsdangerous library](https://itsdangerous.palletsprojects.com/en/2.1.x/concepts/#key-rotation).
- [ ] We can rotate the signing key without downtime.
- [ ] Update the secrets rotation documentation with the latest command line tool for rotating the dangerous secret key.

# QA Steps

- [ ] Tested locally.
- [ ] Tested in staging.

**Comment by sastels** [comment]
Made some improvements to the code and in particular the testing. Ready for exhaustive local testing.

**Comment by sastels** [comment]
changed the resigner tests to leave the CryptoSigners in their original state

**Comment by sastels** [comment]
https://github.com/cds-snc/notification-api/pull/1789 tested locally

**Comment by jimleroyer** [comment]
@ben851 to QA pair with @sastels

**Comment by ben851** [comment]
* To be done during the core group session

**Comment by ben851** [comment]
Validated locally with @sastels, approved PR.
